// P21 - Anti-Patterns
function generateP21(w) {
  const lines = [
    '### 21.1 Solutioneering',
    '',
    '**Symptom:** Engineers jump to a technical solution before fully understanding the problem.',
    '',
    '**Example:** A team spends 3 months building a microservices architecture before validating that the product needs it. The product fails because it does not solve user problems, not because of the architecture.',
    '',
    '**Prevention:** Require problem definition before solution discussions. Use hypothesis-driven development. Timebox technical spikes. Always ask: "What user problem does this solve?"',
    '',
    '### 21.2 Analysis Paralysis',
    '',
    '**Symptom:** Endless discovery, data analysis, and validation at the expense of shipping.',
    '',
    '**Example:** A team conducts 40 customer interviews, runs 8 surveys, analyzes 12 competitors, and builds 5 prototypes before writing any code. By the time they ship, the market has shifted.',
    '',
    '**Prevention:** Set timeboxes for discovery phases. Define what "enough" evidence looks like before starting. Move to delivery when critical assumptions are validated. Accept that some unknowns can only be resolved by shipping.',
    '',
    '### 21.3 HiPPO-Driven Decisions',
    '',
    '**Symptom:** Decisions are made based on the highest-paid person\'s opinion rather than data.',
    '',
    '**Example:** The CEO wants a feature based on a conversation with one customer. Despite data showing low demand, the team builds it. The feature launches to low adoption.',
    '',
    '**Prevention:** Require data for all significant decisions. Use structured prioritization frameworks. Create a culture where challenging authority with data is encouraged. Surface data before opinions in discussions.',
    '',
    '### 21.4 Everything is P0',
    '',
    '**Symptom:** Every feature is classified as top priority, leading to team overwhelm and lack of focus.',
    '',
    '**Example:** A product roadmap has 15 features all labeled "Must Have." The team is working 60-hour weeks and still missing deadlines. Quality suffers. Burnout increases.',
    '',
    '**Prevention:** Force rank priorities. Limit Must Haves to 60% of capacity. Use MoSCoW explicitly. Require trade-off decisions when adding new priorities. Protect team capacity.',
    '',
    '### 21.5 Building the Wrong Thing',
    '',
    '**Symptom:** Features are built based on assumptions that are not validated with users.',
    '',
    '**Example:** A team builds a sophisticated notification system with machine learning prioritization. Users are overwhelmed by notifications and turn them all off. The feature actually reduces engagement.',
    '',
    '**Prevention:** Validate problems before solutions. Test solutions with prototypes before full build. Run experiments with MVPs. Instrument everything to measure actual impact. Kill features that do not work.',
    '',
    '### 21.6 Technical Debt Amnesia',
    '',
    '**Symptom:** The team accumulates technical debt without tracking it or planning to repay it.',
    '',
    '**Example:** Every sprint has "quick fixes" that take shortcuts. After 6 months, the codebase is so fragile that a simple change takes 3x longer than it should. The team is spending 50% of capacity on bugs.',
    '',
    '**Prevention:** Maintain a technical debt register. Budget 20% of each sprint for debt reduction. Refuse shortcuts without documenting them. Connect debt to product impact. Regularly review debt with product stakeholders.',
    '',
    '### 21.7 Premature Scaling',
    '',
    '**Symptom:** Building for scale before validating product-market fit.',
    '',
    '**Example:** A startup builds a microservices architecture, Kubernetes infrastructure, and multi-region deployment before their first 100 users. They run out of money before finding product-market fit.',
    '',
    '**Prevention:** Choose the simplest architecture that works. Defer scalability investments until validated. Use proven technologies. Optimize for learning speed, not scale. Raise the scaling bar only when current architecture limits growth.',
    '',
    '### 21.8 Siloed Engineering and Product',
    '',
    '**Symptom:** Engineering and product teams work in isolation, leading to misaligned priorities.',
    '',
    '**Example:** Product defines a roadmap without engineering input. Engineering estimates are inaccurate because they lacked context. Engineers build features differently than product expected. Delays and friction result.',
    '',
    '**Prevention:** Involve engineers in product discovery. Include product in technical decisions with user impact. Use cross-functional teams. Share roadmap, progress, and metrics transparently. Hold joint planning sessions.',
    '',
    '### 21.9 Gold-Plating',
    '',
    '**Symptom:** Building more features or polish than necessary for the current stage.',
    '',
    '**Example:** A team building an MVP spends 2 weeks on animation polish, dark mode, and keyboard shortcuts. The core feature does not work well. Users try it, find it broken, and never return.',
    '',
    '**Prevention:** Define MVP scope explicitly. Ask "what is the minimum to test the hypothesis?" Cut anything that does not directly support the core value proposition. Ship when the core works, not when everything is polished.',
    '',
    '### 21.10 Ignoring Non-Functional Requirements',
    '',
    '**Symptom:** Building features without considering performance, security, reliability, or scalability.',
    '',
    '**Example:** A team launches a file-sharing feature that works great for 50 users. When 500 users try it, the server crashes because unoptimized image processing overwhelms the system. Users lose trust.',
    '',
    '**Prevention:** Define non-functional requirements alongside functional ones. Include performance and security in acceptance criteria. Load test before launch. Monitor production metrics. Plan for scale from day one.',
    '',
    '### 21.11 Over-Engineering',
    '',
    '**Symptom:** Building for hypothetical future needs that never materialize.',
    '',
    '**Example:** A team builds a plugin architecture for a feature that has 3 use cases. The plugin API takes 3 months to build. In 2 years, only 1 plugin is ever created. The abstraction added complexity without value.',
    '',
    '**Prevention:** Build for current needs with an eye toward extension. Avoid abstractions until you see the duplication. YAGNI (You Ain\'t Gonna Need It). Prefer simple solutions that are easy to change later.',
    '',
    '### 21.12 Feature Factory',
    '',
    '**Symptom:** The team continuously ships features without measuring whether they create value.',
    '',
    '**Example:** A team ships 50 features in a year. Only 5 are used by more than 10% of users. The rest are waste. The team is rewarded for shipping, not for impact. Velocity is the only metric that matters.',
    '',
    '**Prevention:** Measure feature adoption and impact. Reward outcomes, not output. Kill features that are not used. Build only what is validated. Connect every feature to a metric. Review feature performance quarterly.',
    '',
    '### 21.13 Product Arrogance',
    '',
    '**Symptom:** Engineers overriding product decisions based on technical opinions.',
    '',
    '**Example:** An engineer insists on building a feature in a specific way because it is "technically cleaner" even though the product team has data showing users prefer a different approach. The technically clean version flops.',
    '',
    '**Prevention:** Respect role boundaries while challenging ideas. Make technical recommendations with rationale, but accept product decisions. Use experiments to resolve disagreements. Let data be the tiebreaker.',
    '',
    '### 21.14 Not Measuring Impact',
    '',
    '**Symptom:** Features are built without instrumentation to measure their impact.',
    '',
    '**Example:** A team ships a redesigned dashboard. Nobody knows if it improved user engagement because no events were tracked. The team cannot justify the investment or learn from the outcome.',
    '',
    '**Prevention:** Require instrumentation for every feature. Define success metrics before building. Track feature adoption, usage patterns, and business impact. Review feature performance post-launch. Kill or improve based on data.',
    '',
    '### 21.15 Stakeholder Communication Black Hole',
    '',
    '**Symptom:** Stakeholders do not know what engineering is working on or why.',
    '',
    '**Example:** An engineering team works for 3 months on a major architecture migration. Stakeholders expected new features and are surprised and frustrated when they see the migration instead. Trust erodes.',
    '',
    '**Prevention:** Communicate technical work in product terms. Share roadmap and progress regularly. Align on priorities before starting. Surface trade-offs explicitly. Use status reports, demos, and updates.',
    '',
    '### 21.16 Ignoring Customer Feedback',
    '',
    '**Symptom:** Engineering makes decisions without talking to customers.',
    '',
    '**Example:** A team builds a complex feature that nobody in engineering uses or understands. When released, users find it confusing and useless. The team could have learned this with 3 customer interviews.',
    '',
    '**Prevention:** Engineers participate in customer interviews. Review support tickets and feedback regularly. Use the product yourself. Watch session recordings. Talk to customers before and after building.',
  ];
  lines.forEach(l => w(l));
}

// P22 - Quality Gates
function generateP22(w) {
  const lines = [
    '### 22.1 What Are Quality Gates',
    '',
    'Quality gates are checkpoints that work must pass before proceeding to the next stage. They ensure that product engineering work meets standards for quality, alignment, and readiness.',
    '',
    '### 22.2 Discovery Quality Gate',
    '',
    '**Before building, verify:**',
    '- Problem statement defined and agreed upon',
    '- Solution hypothesis documented with success criteria',
    '- Riskiest assumptions identified and tested',
    '- Customer need validated (not just assumed)',
    '- Technical feasibility assessed',
    '- Effort estimate provided (± uncertainty range)',
    '',
    '**Gate question:** "Do we have enough evidence that this is worth building?"',
    '',
    '### 22.3 Design Quality Gate',
    '',
    '**Before implementing, verify:**',
    '- Technical design reviewed by at least one peer',
    '- Architecture decision recorded (ADR) for significant choices',
    '- Non-functional requirements defined (performance, security, scale)',
    '- Dependencies identified and planned',
    '- Integration points documented',
    '- Acceptance criteria written and reviewed with product',
    '',
    '**Gate question:** "Is the design ready for implementation?"',
    '',
    '### 22.4 Implementation Quality Gate',
    '',
    '**Before merging, verify:**',
    '- Code reviewed by at least one peer',
    '- Automated tests pass (unit, integration, lint)',
    '- Test coverage meets team threshold (>80% for critical paths)',
    '- Feature flags in place for controlled rollout',
    '- Event tracking implemented for all key user actions',
    '- Documentation updated (or ticket created)',
    '- Security review completed for sensitive features',
    '',
    '**Gate question:** "Is the code ready to be merged?"',
    '',
    '### 22.5 Release Quality Gate',
    '',
    '**Before deploying to production, verify:**',
    '- Staging environment tests pass',
    '- Performance regression tests pass',
    '- Database migration plan reviewed and tested',
    '- Rollback plan documented',
    '- Monitoring and alerting configured',
    '- Release notes written (internal and external)',
    '- Stakeholders informed of release timing',
    '',
    '**Gate question:** "Is this ready for production?"',
    '',
    '### 22.6 Launch Quality Gate',
    '',
    '**Before full rollout, verify:**',
    '- Canary or phased rollout plan defined',
    '- Experiment metrics and success criteria defined',
    '- Guardrail metrics configured and alerting set',
    '- Customer support briefed on new feature',
    '- Documentation published (help center, FAQs)',
    '- Feature flagged for controlled release',
    '- Rollback tested and confirmed working',
    '',
    '**Gate question:** "Is this ready for users?"',
    '',
    '### 22.7 Post-Launch Quality Gate',
    '',
    '**After launch, verify within 2 weeks:**',
    '- Feature adoption metrics reviewed',
    '- Experiment results analyzed (if A/B tested)',
    '- Bug reports reviewed and prioritized',
    '- Performance impact assessed',
    '- Customer feedback reviewed',
    '- Success criteria evaluated (did it achieve the goal?)',
    '- Learnings documented for future work',
    '',
    '**Gate question:** "Did this work achieve its intended outcome?"',
    '',
    '### 22.8 Quality Gate Exceptions',
    '',
    'Quality gates can be bypassed in exceptional circumstances, but the bypass must be intentional and documented:',
    '',
    '**Valid exceptions:**',
    '- Emergency hotfix for production incident',
    '- Security vulnerability patch',
    '- Time-critical competitive response (with executive approval)',
    '- Experimental feature where speed of learning trumps quality',
    '',
    '**Exception process:**',
    '1. Document which gates are being bypassed and why',
    '2. Get explicit approval from tech lead or engineering manager',
    '3. Create follow-up tickets to address skipped gates',
    '4. Review bypassed gates in retrospective',
    '',
    '### 22.9 Quality Gate Automation',
    '',
    'Automate as many gates as possible:',
    '',
    '**Automated gates:**',
    '- CI/CD pipeline tests',
    '- Code style and lint checks',
    '- Test coverage thresholds',
    '- Security vulnerability scanning',
    '- Performance regression tests',
    '- API contract tests',
    '- Infrastructure as code validation',
    '',
    '**Manual gates (require human judgment):**',
    '- Code review (architectural and logic quality)',
    '- Design review',
    '- Acceptance criteria review with product',
    '- Customer validation',
    '- Release timing coordination',
    '',
    '### 22.10 Quality Gate Ownership',
    '',
    '**Engineering owns:**',
    '- Code quality gates (tests, lint, review)',
    '- Technical design quality',
    '- Performance and reliability gates',
    '- Security gates',
    '- Instrumentation quality',
    '',
    '**Product owns:**',
    '- Problem definition and hypothesis',
    '- Success criteria and metrics',
    '- Customer validation',
    '- Acceptance criteria',
    '- Launch readiness (support, docs)',
    '',
    '**Shared ownership:**',
    '- Release timing and coordination',
    '- Post-launch review',
    '- Prioritization decisions',
    '- Trade-off decisions',
    '',
    '### 22.11 Quality Gate Metrics',
    '',
    'Track quality gate effectiveness:',
    '',
    '**Process metrics:**',
    '- Percentage of work passing each gate on first attempt',
    '- Time spent in each gate (review cycle time)',
    '- Number of exceptions granted',
    '- Common reasons for gate failures',
    '',
    '**Outcome metrics:**',
    '- Production incident rate',
    '- Feature adoption rate',
    '- Bug rate in new features',
    '- Revert rate',
    '- Customer satisfaction with new features',
    '',
    'Use these metrics to continuously improve quality gates. If a gate consistently passes everything, it may be too lenient. If it consistently blocks everything, the criteria may be too strict or unclear.',
  ];
  lines.forEach(l => w(l));
}

module.exports = { generateP21, generateP22 };
