// P11 - Rapid Experimentation
function generateP11(w) {
  const lines = [
    '### 11.1 The Experimentation Mindset',
    '',
    'Experimentation is the practice of using data to make decisions rather than relying on opinion, hierarchy, or intuition. For product engineers, this means treating features as hypotheses to be tested, not solutions to be delivered.',
    '',
    '**Core principles:**',
    '1. Every feature that can be tested should be tested',
    '2. Test the riskiest assumption first',
    '3. Small experiments are better than long debates',
    '4. Data beats opinions',
    '5. Fail fast, learn faster',
    '6. Statistical rigor matters',
    '',
    '### 11.2 A/B Testing Infrastructure',
    '',
    '**Feature flag system:**',
    '- Ability to turn features on/off for specific user segments',
    '- Percentage-based rollouts',
    '- Targeting by user attributes (plan, region, device, behavior)',
    '- Kill switch for immediate rollback',
    '',
    '**Experiment framework:**',
    '- Define experiment parameters (hypothesis, audience, duration, metric)',
    '- Random assignment to control and treatment groups',
    '- Statistical analysis engine',
    '- Results dashboard with go/no-go criteria',
    '',
    '**Event tracking pipeline:**',
    '- Instrument feature usage at the component level',
    '- Track conversion events and user actions',
    '- Real-time and batch event processing',
    '- Data quality monitoring',
    '',
    '### 11.3 Feature Flag Best Practices',
    '',
    '**Types of feature flags:**',
    '',
    '| Type | Purpose | Lifespan |',
    '|---|---|---|',
    '| Release toggles | Control feature rollout | Short (days to weeks) |',
    '| Experiment toggles | A/B test assignment | Short (weeks to months) |',
    '| Ops toggles | Kill switches | Permanent |',
    '| Permission toggles | Feature access by user tier | Permanent |',
    '| Migration toggles | Transition between systems | Short to medium |',
    '',
    '**Anti-patterns:**',
    '- Dead flags never cleaned up',
    '- Flag spaghetti - multiple interacting flags creating complexity',
    '- Flag dependencies - features depending on other flag states',
    '- Missing defaults - flags without sensible default behavior',
    '',
    '**Flag lifecycle:**',
    '1. Create with metadata (owner, purpose, expected lifespan)',
    '2. Deploy to codebase',
    '3. Test in each state',
    '4. Roll out gradually',
    '5. Monitor impact on metrics',
    '6. Clean up - remove conditional code',
    '',
    '### 11.4 Experiment Design',
    '',
    '**Hypothesis formulation:**',
    '"We believe that [change] for [user segment] will result in [metric change]. We will consider this successful if [criterion]."',
    '',
    '**Experiment checklist:**',
    '1. Clear hypothesis with directional prediction',
    '2. Primary metric defined',
    '3. Secondary and guardrail metrics defined',
    '4. Minimum detectable effect (MDE) calculated',
    '5. Sample size calculated',
    '6. Experiment duration determined',
    '7. Randomization unit defined',
    '8. Statistical significance threshold set (95%)',
    '9. Stop conditions defined',
    '',
    '**Sample size calculation depends on:**',
    '- Baseline conversion rate',
    '- Minimum detectable effect',
    '- Statistical power (typically 80%)',
    '- Significance level (typically 5%)',
    '',
    '**Duration considerations:**',
    '- Account for day-of-week effects (run at least 1 business cycle)',
    '- Account for novelty effect (2-4 weeks for consumer, 4-8 for enterprise)',
    '- Account for seasonality',
    '- Never stop an experiment early (peeking invalidates significance)',
    '',
    '### 11.5 Statistical Significance',
    '',
    '**P-value:** Probability of observing the result if there were no real difference. p < 0.05 = significant.',
    '',
    '**Confidence interval:** Range where true effect lies with 95% confidence.',
    '',
    '**Type I error (false positive):** Concluding effect when none exists. Controlled by significance level.',
    '',
    '**Type II error (false negative):** Concluding no effect when one exists. Controlled by statistical power.',
    '',
    '**Common tests:**',
    '- Two-sample t-test: Comparing means',
    '- Chi-squared test: Comparing proportions',
    '- Mann-Whitney U test: Non-parametric for ordinal data',
    '- Bayesian A/B testing: Probability distributions',
    '',
    '**Guidelines:**',
    '- Never peek and stop early',
    '- Pre-register hypothesis and analysis plan',
    '- Use sequential testing if monitoring continuously',
    '- Correct for multiple comparisons',
    '',
    '### 11.6 Novelty Effect',
    '',
    'The tendency for users to engage more with a new feature simply because it is new.',
    '',
    '**Detecting:** Look for initial spike followed by decay. Compare early vs. late adopters. Run experiments long enough for novelty to wear off.',
    '',
    '**Mitigation:** Run experiments long enough, segment by new vs. existing users, use holdout groups, track repeat usage.',
    '',
    '### 11.7 Guardrail Metrics',
    '',
    'Metrics that should not be negatively impacted by the experiment:',
    '- Page load time: Should not increase',
    '- Error rate: Should not increase',
    '- Revenue: Should not decrease',
    '- User satisfaction: Should not decrease',
    '- Support ticket volume: Should not increase',
    '',
    'Define acceptable degradation thresholds, monitor alongside primary metrics, stop experiment if guardrails breached.',
    '',
    '### 11.8 Experiment Sizing',
    '',
    '**High-traffic:** Can detect small effects quickly, manage experiment interaction.',
    '',
    '**Medium-traffic:** Prioritize by impact, need longer run times, consider faster methods.',
    '',
    '**Low-traffic:** Often cannot reach significance. Use qualitative methods, Bayesian approaches, aggregate experiments.',
    '',
    '### 11.9 Experiment Operations (SOP)',
    '',
    '**Design:** Define hypothesis and success criteria, design experiment, review with team.',
    '',
    '**Implementation:** Add feature flags and event tracking, implement treatment, write tests, code review, QA in staging.',
    '',
    '**Launch:** Deploy flag off, enable small percentage to test, verify data quality, ramp to 50/50 split.',
    '',
    '**Monitoring:** Monitor primary metric daily, monitor guardrails, check data quality. Do not peek at significance.',
    '',
    '**Decision:** At pre-determined end date, analyze results. Ship, iterate, or kill. Document learnings.',
    '',
    '**Cleanup:** If shipped - clean up flag code. If killed - remove feature code. Archive results.',
    '',
    '### 11.10 Experimentation Culture',
    '',
    '**Psychological safety:** Failure is learning, not blame. "Failed" experiments celebrated for knowledge. No punishment for negative results.',
    '',
    '**Incentives:** Engineers rewarded for running experiments, PMs rewarded for validated learning, teams rewarded for moving metrics.',
    '',
    '**Practices:** Regular experiment reviews, experiment post-mortems, experiment backlog, experimentation training.',
  ];
  lines.forEach(l => w(l));
}

// P12 - Product Metrics
function generateP12(w) {
  const lines = [
    '### 12.1 Why Engineers Should Care About Metrics',
    '',
    'Product metrics are how engineers know whether their work is having the intended impact. Without metrics, engineering is a black box - code goes in, but nobody knows what comes out.',
    '',
    '**Metrics enable engineers to:**',
    '1. Measure the impact of their work',
    '2. Make data-driven decisions about what to build next',
    '3. Detect problems early (performance regressions, behavior changes)',
    '4. Communicate value to stakeholders',
    '5. Prioritize effectively',
    '6. Validate assumptions',
    '',
    '### 12.2 The North Star Metric',
    '',
    'The single metric that best captures the value your product delivers to users and the business.',
    '',
    '**Characteristics:** Leading indicator, user value, actionable, sustainable, understandable.',
    '',
    '**Examples:**',
    '- Spotify: Time spent listening',
    '- Airbnb: Nights booked',
    '- Slack: Messages sent',
    '- Facebook: Daily active users',
    '- Medium: Total reading time',
    '- Uber: Rides completed',
    '',
    '**For engineers:** Understand how your work connects to the North Star, instrument to measure contributions, use it to prioritize.',
    '',
    '### 12.3 The AARRR Framework (Pirate Metrics)',
    '',
    '**Acquisition:** How users discover your product. Metrics: Website visits, app downloads, sign-ups, traffic sources. Engineering: SEO, page load time, social sharing, landing page performance.',
    '',
    '**Activation:** Users experience the "aha moment." Metrics: Sign-up completion rate, first key action, time to first value. Engineering: Onboarding flow, account setup UX, guided tutorials.',
    '',
    '**Retention:** Users keep coming back. Metrics: D1/D7/D30 retention, churn rate, session frequency. Engineering: Notifications, personalization, habit-forming features, performance.',
    '',
    '**Referral:** Users tell others. Metrics: Invites sent, acceptance rate, viral coefficient. Engineering: Share functionality, referral program, collaboration features.',
    '',
    '**Revenue:** Users pay. Metrics: MRR, ARPU, LTV, conversion rate. Engineering: Billing infrastructure, pricing page, upgrade flows, payment processing.',
    '',
    '### 12.4 Activation Metrics',
    '',
    'Activation is typically defined as a user completing actions that correlate with long-term retention.',
    '',
    '| Product Type | Activation Event | Example |',
    '|---|---|---|',
    '| SaaS B2B | Team member invited or first workflow | Slack: 2+ users sending 5+ messages |',
    '| SaaS B2C | Core action completed | Evernote: Created 3 notes in first session |',
    '| E-commerce | First purchase | Amazon: First order |',
    '| Marketplace | First transaction | Airbnb: First booking |',
    '| Social | Connection made | Instagram: Followed 5+ accounts |',
    '',
    '**Engineering:** Instrument activation path, optimize time-to-value, build progressive onboarding, A/B test improvements, monitor by segment.',
    '',
    '### 12.5 Retention Metrics',
    '',
    '**Retention curves:** Flat = sticky (ideal), Decaying = losing interest (warning), Inverted = crash (red flag).',
    '',
    '**Metrics:** D1/D7/D30 retention, WAU/MAU, churn rate, stickiness (DAU/MAU).',
    '',
    '**Engineering:** Build habit-forming features, monitor performance, implement re-engagement, track feature-level retention, build personalization.',
    '',
    '### 12.6 Revenue Metrics',
    '',
    '**Key metrics:** MRR, ARR (MRR x 12), ARPU (revenue/users), LTV (lifetime value), CAC (acquisition cost), LTV/CAC ratio (> 3 healthy), Gross MRR churn, Net MRR churn.',
    '',
    '**Engineering:** Billing infrastructure, pricing page A/B testing, upgrade/downgrade flows, usage metering, payment processing, invoice generation.',
    '',
    '### 12.7 Engagement Metrics',
    '',
    '**Metrics:** DAU/MAU, sessions/user/day, session duration, actions/session, feature adoption rate, power user rate.',
    '',
    '**Engineering:** Build daily use cases, reduce friction, improve performance, personalization algorithms, engagement loops.',
    '',
    '### 12.8 Cohort Analysis',
    '',
    'Groups users by signup date and tracks behavior over time.',
    '',
    '**Why it matters:** Detects whether product changes improve behavior, separates time from cohort effects, identifies if retention is improving.',
    '',
    '**Engineering:** Instrument signup date and activity timestamps, build cohort dashboard, automate comparison, alert on degradation.',
    '',
    '### 12.9 Instrumentation Best Practices',
    '',
    '**Principles:**',
    '1. Define a taxonomy: [entity].[action] - user.signup, document.created',
    '2. Track actions and states',
    '3. Include context: user_id, session_id, timestamp, version',
    '4. Track the full funnel, not just conversion',
    '5. Avoid instrumentation debt',
    '',
    '**Event properties:** user_id, session_id, timestamp, event_name, app_version, platform, experiment_id.',
    '',
    '**Data quality:** Monitor event volume anomalies, missing properties, unexpected values, timestamps, duplicates.',
    '',
    '### 12.10 Vanity vs. Actionable Metrics',
    '',
    '| Vanity Metrics | Actionable Metrics |',
    '|---|---|',
    '| Total registered users | Active users (DAU/MAU) |',
    '| Total downloads | Installs that lead to activation |',
    '| Page views | Pages per session |',
    '| Total revenue | Revenue per user or LTV |',
    '| Number of features | Feature adoption rate |',
    '',
    '**Vanity:** Always increase, look impressive, do not drive decisions.',
    '**Actionable:** Directly influenced, unit economics, leading indicators, specific.',
    '',
    '### 12.11 Metrics Tree / Goal Tree',
    '',
    'A metrics tree breaks down the North Star into sub-metrics individual teams can influence.',
    '',
    '**Engineering use:** Identify which sub-metric your work impacts, instrument to measure it, use the tree to communicate how work connects to the North Star.',
  ];
  lines.forEach(l => w(l));
}

// P13 - Roadmapping
function generateP13(w) {
  const lines = [
    '### 13.1 The Roadmap as a Shared Artifact',
    '',
    'The product roadmap is a shared artifact reflecting both product and engineering input.',
    '',
    '**Engineering input:** Technical feasibility, effort estimation, technical dependencies, technical risk, architectural guidance, opportunity identification, innovation.',
    '',
    '### 13.2 Effort Estimation for Roadmap Items',
    '',
    '**T-shirt sizing:** S (< 2 weeks), M (2-4 weeks), L (1-3 months), XL (3-6 months), XXL (6+ months).',
    '',
    '**Three-point estimation:** Optimistic, Most Likely, Pessimistic. Weighted: (O + 4M + P) / 6.',
    '',
    '**Relative estimation (story points):** Fibonacci (1, 2, 3, 5, 8, 13, 21), focus on relative size.',
    '',
    '**Best practices:** Separate estimation from commitment, include all phases, account for overhead, flag assumptions, review past estimates, re-estimate as you learn.',
    '',
    '### 13.3 Technical Dependencies Mapping',
    '',
    '**Dependency types:** Infrastructure, platform, third-party, data, knowledge, sequencing.',
    '',
    '**Communication:** Share dependency maps during planning, flag critical dependencies early, propose alternatives, track in the same system as product tasks.',
    '',
    '### 13.4 Technical Feasibility Assessment',
    '',
    '**Levels:**',
    '- **Proven:** Built similar features before. Low risk.',
    '- **Plausible:** Approach well-understood but not built this exact feature. Medium risk.',
    '- **Speculative:** Uncertainty or new technology. High risk.',
    '- **Unknown:** Cannot determine without spike. Very high risk.',
    '',
    '### 13.5 Technical Risk Register',
    '',
    '| ID | Feature | Risk | Probability | Impact | Mitigation | Owner |',
    '|---|---|---|---|---|---|---|',
    '| R01 | Real-time sync | API scale limits | Medium | High | Spike to test | Alice |',
    '| R02 | Mobile app | No iOS experience | High | Medium | Hire contractor | Bob |',
    '',
    '**Strategies:** Avoid, Mitigate, Transfer, Accept.',
    '',
    '### 13.6 Roadmap Contribution Workflow',
    '',
    '**Before planning:** Review technical debt, identify opportunities, prepare feasibility assessments, gather capacity data.',
    '',
    '**During planning:** Present feasibility and estimates, flag dependencies and risks, propose approaches, identify sequencing, advocate for technical health.',
    '',
    '**After planning:** Break down into epics/stories, identify cross-team needs, update risk register, communicate commitments.',
    '',
    '### 13.7 Communicating Engineering Capacity',
    '',
    '**Best practices:** Show capacity allocation (80/20 for features/tech health), use throughput data, account for overhead, highlight trade-offs, be transparent about uncertainty, update as circumstances change.',
    '',
    '### 13.8 Roadmap Presentation to Engineering',
    '',
    '**What engineers need:** What we are building and why, what success looks like, timeline with uncertainty ranges, trade-offs made, technical challenges anticipated, how individual work connects to outcomes.',
    '',
    '### 13.9 Roadmap Adjustment',
    '',
    '**When to adjust:** Technical discovery changes feasibility, user feedback invalidates assumptions, competitive shifts, business priorities change, capacity changes, debt reaches critical levels.',
    '',
    '**Process:** Identify the change, assess impact, propose alternatives, communicate with rationale, update the document.',
  ];
  lines.forEach(l => w(l));
}

// P14 - Requirements Engineering
function generateP14(w) {
  const lines = [
    '### 14.1 From Product Needs to Technical Requirements',
    '',
    'Requirements engineering is the bridge between product strategy and technical implementation.',
    '',
    '**Translation process:**',
    '1. Product need: A user problem or market opportunity',
    '2. Product requirement: A specific capability the product should have',
    '3. Technical requirement: How the system must behave',
    '4. Acceptance criteria: Specific, testable conditions that define done',
    '',
    '### 14.2 Writing Good Technical Requirements',
    '',
    '**Characteristics:** Unambiguous, testable, atomic, necessary, implementation-independent, feasible, traceable.',
    '',
    '**Template:**',
    '### REQ-[ID]: [Title]',
    '**Description:** [What the system must do]',
    '**Rationale:** [Why this is needed - connect to product need]',
    '**Acceptance Criteria:** [Criterion 1], [Criterion 2]',
    '**Technical Notes:** [Implementation considerations, constraints, dependencies]',
    '**Verification Method:** [Automated test | Manual test | Review]',
    '',
    '### 14.3 Acceptance Criteria Patterns',
    '',
    '**Given-When-Then (BDD):** Given [context], When [action], Then [outcome].',
    '',
    '**Rule-based:** "The system shall [behavior] when [condition]."',
    '',
    '**Boundary-based:** Edge cases explicitly. "Passwords of at least 8 and at most 128 characters."',
    '',
    '**Error-based:** Expected behavior for failure modes. "When network is unavailable, queue changes locally."',
    '',
    '**Performance-based:** "Document editor shall load within 2 seconds for documents under 100KB."',
    '',
    '### 14.4 Non-Functional Requirements',
    '',
    '**Performance:** Response time, throughput, capacity.',
    '**Reliability:** Uptime (99.9%), availability, data durability (99.999999%).',
    '**Security:** Authentication, authorization, encryption at rest and in transit, audit logging.',
    '**Scalability:** Support 2x traffic, horizontal scaling.',
    '**Maintainability:** Zero-downtime deployments, 80% test coverage.',
    '**Usability:** Common tasks in 3 clicks or fewer, keyboard shortcuts.',
    '**Compliance:** GDPR, audit logs for 7 years.',
    '',
    '### 14.5 Requirements Verification',
    '',
    '| Requirement Type | Verification Method |',
    '|---|---|',
    '| Functional behavior | Automated integration test |',
    '| UI behavior | Automated UI test |',
    '| Performance | Performance test |',
    '| Security | Security test / penetration test |',
    '| Reliability | Load test / chaos engineering |',
    '| Compliance | Audit / certification |',
    '',
    '### 14.6 Requirements Validation',
    '',
    '**Techniques:** Customer review, prototyping, acceptance test-driven development (ATDD), user story mapping, requirements walkthrough.',
    '',
    '### 14.7 Requirements Change Management',
    '',
    '**Process:** Capture the change, assess impact, estimate cost, evaluate trade-off, decide, communicate, update.',
    '',
    '**Categories:** Scope change (formal), Clarification (minimal), Technical change (engineering decision).',
    '',
    '### 14.8 Requirements Traceability',
    '',
    'Connects requirements to implementation, tests, and verification. Enables impact analysis, gap identification, audit and compliance.',
    '',
    '### 14.9 Requirements Engineering Anti-Patterns',
    '',
    '| Anti-Pattern | Solution |',
    '|---|---|',
    '| Analysis paralysis | Write good enough, iterate |',
    '| Requirements by anecdote | Validate with data |',
    '| Gold-plating | Challenge every requirement |',
    '| Frozen requirements | Embrace change with process |',
    '| Copycat requirements | Understand why competitors built it |',
  ];
  lines.forEach(l => w(l));
}

// P15 - Stakeholder Communication
function generateP15(w) {
  const lines = [
    '### 15.1 Why Stakeholder Communication Matters',
    '',
    'Stakeholder communication is the difference between a respected engineering team and an invisible one. Effective communication builds trust, aligns expectations, and ensures engineering contributions are understood and valued.',
    '',
    '**Key stakeholders:** Product managers, engineering leadership, designers, business stakeholders, executives, external stakeholders.',
    '',
    '### 15.2 Product Demos',
    '',
    '**When to demo:** Sprint reviews, before major releases, milestone demos, technical demos.',
    '',
    '**Best practices:**',
    '1. Prepare context - problem being solved, before/after state',
    '2. Focus on outcomes, not effort',
    '3. Prepare for failure - backup recordings, main path only',
    '4. Structure: 1 min context, 3 min walkthrough, 1 min technical highlights, 2 min next steps, 3 min Q&A',
    '',
    '### 15.3 Technical Updates',
    '',
    '**Written (weekly/bi-weekly):** Accomplishments, current work, blockers, metrics, technical highlights.',
    '',
    '**Standup (daily):** Yesterday, today, blockers.',
    '',
    '**Sprint reviews (2 weeks):** Demo, goals vs. actuals, team metrics.',
    '',
    '**Technical reviews (monthly/quarterly):** Health assessment, debt review, architecture changes, technology radar.',
    '',
    '**Update principles:** Most important first, bullet points, include metrics, be honest about challenges, keep brief, consistent format.',
    '',
    '### 15.4 Status Reporting',
    '',
    '**Traffic light:** Green (on track), Yellow (concerns), Red (needs intervention).',
    '',
    '**Template:**',
    '## Project: [Name]',
    '**Status:** Green/Yellow/Red',
    '**Last period:** [Planned]',
    '**This period:** [Accomplished]',
    '**Next period:** [Planned]',
    '**Key accomplishments:** [Metric/impact]',
    '**Risks:** [Risk - Impact - Mitigation - Owner]',
    '**Metrics:** [Target vs. current with trend]',
    '',
    '### 15.5 Escalation Communication',
    '',
    '**When to escalate:** Timeline risk, scope risk, technical risk, resource risk, external dependency.',
    '',
    '**Best practices:** Early (not late), provide options, quantify impact, be specific, follow up in writing.',
    '',
    '**Template:**',
    '## Escalation: [Title]',
    '**What is happening:** [Description]',
    '**Impact:** [Effect on timeline, budget, quality, users]',
    '**Root cause:** [What caused this]',
    '**Options:** [Option A with trade-offs, Option B with trade-offs]',
    '**Recommendation:** [What we recommend]',
    '**Decision needed by:** [Date]',
    '',
    '### 15.6 Communicating Bad News',
    '',
    '**Principles:** Be transparent, be timely, be solution-oriented, take ownership, be specific.',
    '',
    '**Template:**',
    '## Update: [What happened]',
    '**What happened:** [Factual description]',
    '**Impact:** [Who affected and how]',
    '**Why it happened:** [Root cause]',
    '**What we are doing:** [Immediate actions]',
    '**Prevention:** [How we prevent recurrence]',
    '**Timeline:** [Resolution date]',
    '',
    '### 15.7 Technical Decisions Communication',
    '',
    '**Template:**',
    '## Technical Decision: [Title]',
    '**What we decided:** [Plain language]',
    '**Why:** [Business rationale]',
    '**Product impact:** [User-facing changes, performance impact]',
    '**Timeline impact:** [How this affects delivery]',
    '**Trade-offs accepted:** [What we chose not to do]',
    '**Risks:** [Likelihood/impact]',
    '',
    '### 15.8 Stakeholder Mapping',
    '',
    '**Manage Closely (High Interest, High Influence):** Regular detailed communication. Involve in decisions.',
    '',
    '**Keep Satisfied (Low Interest, High Influence):** Key milestones, outcomes focus, quarterly reviews.',
    '',
    '**Keep Informed (High Interest, Low Influence):** Regular updates, monthly, sprint reviews.',
    '',
    '**Monitor (Low Interest, Low Influence):** Minimal communication, annual updates.',
    '',
    '### 15.9 Meeting Culture',
    '',
    '**As participant:** Review agenda, come prepared, stay on topic, take notes, follow up.',
    '',
    '**As facilitator:** Start with goal, stick to agenda, ensure everyone speaks, summarize decisions, send follow-up.',
    '',
    '**Meeting types:** Daily standup (15 min), Sprint planning (1-2 hours), Sprint review (1 hour), Retrospective (1 hour), Product refinement (1 hour), Technical design review (1 hour), One-on-one (30 min), Ad-hoc decisions (30 min).',
  ];
  lines.forEach(l => w(l));
}

module.exports = { generateP11, generateP12, generateP13, generateP14, generateP15 };
