// P1 - Persona: The Product Engineer
function generateP1(w) {
  const lines = [
    '### 1.1 Who Is a Product Engineer',
    '',
    'A product engineer is a software engineer who embraces product outcomes as a primary driver of technical decisions. Unlike pure platform engineers who optimize for technical excellence in isolation, or feature engineers who implement specifications without questioning product rationale, the product engineer operates at the intersection of what is technically possible and what is product-valuable.',
    '',
    'The product engineer does not wait for perfectly specified requirements. They actively participate in problem definition, challenge assumptions, propose alternatives, and push back when technical shortcuts will damage long-term product health. They speak the language of business outcomes, user needs, and technical trade-offs fluently.',
    '',
    '### 1.2 Key Distinctions',
    '',
    '| Aspect | Traditional Engineer | Product Engineer |',
    '|--------|---------------------|------------------|',
    '| Primary question | "How should we build this?" | "Should we build this, and if so, how?" |',
    '| Requirements | Accepts PRD as gospel | Challenges, refines, collaborates on PRD |',
    '| Prioritization | Works from assigned backlog | Participates in priority decisions |',
    '| User contact | Rare | Regular customer conversations |',
    '| Success metric | Code shipped, velocity | Product outcomes, impact |',
    '| Technical debt | Avoids discussion | Quantifies in product terms |',
    '| Roadmap input | Effort estimates | Feasibility + product judgment |',
    '',
    '### 1.3 Core Competencies',
    '',
    'A product engineer must develop proficiency across these dimensions:',
    '',
    '1. **Technical product intuition:** The ability to look at a product requirement and immediately sense which approaches have high technical leverage, which paths lead to maintenance nightmares, and where the product is asking for something that will be expensive to change later.',
    '',
    '2. **Customer empathy:** The willingness to speak with users, watch session recordings, analyze support tickets, and internalize user pain points as a personal driver of engineering quality.',
    '',
    '3. **Business acumen:** Understanding how the product makes money, what the key business metrics are, who the competitors are, and what market forces shape the product roadmap.',
    '',
    '4. **Communication agility:** The ability to explain technical concepts to non-technical stakeholders, translate business requirements into technical designs, and facilitate productive conversations between engineering and product.',
    '',
    '5. **Experimentation mindset:** A bias toward testing assumptions with data, running experiments to validate hypotheses, and using evidence rather than opinion to drive decisions.',
    '',
    '6. **Strategic thinking:** The ability to look beyond the current sprint or quarter and consider how technical decisions compound over time, shaping the product\'s future capabilities and constraints.',
    '',
    '### 1.4 The Product Engineer\'s Daily Questions',
    '',
    'Every day, a product engineer should ask themselves:',
    '',
    '- What user problem am I solving today, and why does it matter?',
    '- What is the smallest thing I can build that moves the product metric?',
    '- Am I optimizing for the right trade-off between speed and quality?',
    '- Have I validated my assumptions, or am I building on guesses?',
    '- Does the product team know what I am working on and why?',
    '- What is the cost of delay for the work I am prioritizing?',
    '',
    '### 1.5 When Product Engineering Goes Wrong',
    '',
    'Four common failure modes for engineers adopting a product mindset:',
    '',
    '1. **Solutioneering:** Jumping to technical solutions before understanding the problem. The product engineer falls in love with a technology or architecture and retrofits product justifications around it.',
    '',
    '2. **Analysis paralysis:** Spending too much time in discovery, data analysis, and validation at the expense of shipping. Product engineering requires judgment about when enough analysis is enough.',
    '',
    '3. **Product arrogance:** Overriding product manager decisions with technical opinions. The product engineer respects role boundaries while challenging ideas constructively.',
    '',
    '4. **Technical neglect:** Prioritizing product concerns so heavily that code quality, architecture, and engineering fundamentals degrade. The product engineer balances product impact with technical health.',
    '',
    '### 1.6 Career Progression',
    '',
    'The product engineering path typically evolves as follows:',
    '',
    '- **Junior Product Engineer:** Focuses on implementing well-defined features with product awareness. Participates in customer interviews. Learns to estimate effort and communicate progress.',
    '',
    '- **Mid-Level Product Engineer:** Owns feature areas end-to-end. Contributes to product discovery. Makes technical trade-off decisions with product input. Leads refinement sessions.',
    '',
    '- **Senior Product Engineer:** Shapes the product roadmap through technical insight. Leads discovery for complex initiatives. Mentors others in product thinking. Drives technical strategy aligned with product direction.',
    '',
    '- **Staff Product Engineer:** Defines product engineering practices across the organization. Influences product strategy at the company level. Builds platforms that enable product experimentation. Drives technical bets that create product moats.',
    '',
    '### 1.7 The Product Engineer\'s Toolkit',
    '',
    'Essential tools and practices:',
    '',
    '- **Metrics dashboards:** Daily habit of checking product metrics',
    '- **Session replay tools:** Regular review of user sessions',
    '- **Customer interview protocol:** Structured approach to user research',
    '- **Experiment framework:** Template for designing and evaluating tests',
    '- **Prioritization matrix:** Shared framework for engineering-product prioritization',
    '- **Technical debt register:** Living document of debt items with product impact',
    '- **Decision log:** Record of significant technical decisions and their rationale',
  ];
  lines.forEach(l => w(l));
}

// P2 - Philosophy
function generateP2(w) {
  const lines = [
    '### 2.1 Engineering-Product Partnership',
    '',
    'The engineering-product partnership is the most critical relationship in product development. When it works well, the result is products that are technically excellent, ship on time, and deliver real user value. When it breaks down, the result is missed deadlines, technical debt, and products that satisfy neither users nor engineers.',
    '',
    '**Principles of effective partnership:**',
    '',
    '1. **Shared outcomes, not handoffs:** Engineering and product share responsibility for product outcomes, not just deliverables. The product manager does not "throw requirements over the wall" and the engineering team does not "throw code over the wall."',
    '',
    '2. **Mutual respect for expertise:** The product manager respects engineering judgment on technical feasibility, effort, and architecture. The engineer respects product judgment on user needs, market timing, and business priorities.',
    '',
    '3. **Early and continuous involvement:** Engineering is involved in product discovery from the beginning, not just during implementation. Product is involved in technical decisions that affect user experience or delivery timelines.',
    '',
    '4. **Transparent trade-off communication:** Both sides surface trade-offs early and explicitly. Engineering communicates technical debt and its product impact. Product communicates business constraints and timeline pressures.',
    '',
    '5. **Shared language:** Both sides invest in building a shared vocabulary that bridges technical and product concepts. This includes common metrics, prioritization frameworks, and escalation criteria.',
    '',
    '### 2.2 Shared Ownership',
    '',
    'Shared ownership means that both engineering and product feel responsible for the success or failure of what they build together. This manifests in several behaviors:',
    '',
    '**For engineers:**',
    '- Proactively flagging technical risks that could affect product timelines',
    '- Participating in product discovery and customer interviews',
    '- Suggesting simpler solutions that meet the same user need',
    '- Taking ownership of product metrics, not just code quality',
    '- Contributing to product strategy discussions',
    '',
    '**For product managers:**',
    '- Understanding technical constraints before committing to timelines',
    '- Involving engineers in customer conversations',
    '- Protecting engineering time for technical health work',
    '- Sharing product context and market data freely',
    '- Advocating for engineering needs with stakeholders',
    '',
    '### 2.3 Technical Product Decisions',
    '',
    'Engineers make hundreds of decisions every day that affect the product. Some are obviously product-relevant (choosing what to build), others seem purely technical but have downstream product impact (choosing a database, designing an API, selecting a framework).',
    '',
    '**Types of technical decisions with product impact:**',
    '',
    '1. **Architecture decisions:** Monolith vs. microservices affects how fast new features can be shipped. Database choice affects query capabilities that product may need later. API design affects what client experiences are possible.',
    '',
    '2. **Technology choices:** Framework and language decisions affect hiring, development speed, and long-term maintenance cost. These translate directly to product delivery velocity.',
    '',
    '3. **Implementation decisions:** How thoroughly to handle edge cases, how much validation to include, how much instrumentation to add. These affect product quality, debuggability, and the ability to measure impact.',
    '',
    '4. **Scale decisions:** How much to optimize now vs. later. Premature optimization wastes product time. Insufficient optimization causes product pain when usage grows.',
    '',
    '### 2.4 Trade-off Communication with Product',
    '',
    'When communicating trade-offs with product stakeholders, follow this framework:',
    '',
    '1. **State the product impact first:** "This architecture choice will let us ship new recommendation features in days instead of weeks." Or: "This technical debt is causing a 500ms delay on every checkout page, which we estimate costs us 3% conversion."',
    '',
    '2. **Give options with trade-offs:** Never present a single solution. Always offer at least two approaches with clear trade-offs between speed, cost, quality, and future flexibility.',
    '',
    '3. **Quantify when possible:** Use data to support trade-off communications. "Approach A costs $X in engineering time and ships in Y weeks. Approach B costs 2X but enables Z capability that we know we will need in Q3."',
    '',
    '4. **Use product vocabulary:** Frame technical decisions in terms of user experience, time to market, feature velocity, reliability, and cost rather than abstract technical metrics.',
    '',
    '5. **Document decisions:** Record significant trade-off decisions with their rationale, who was involved, and what assumptions were made. This prevents revisiting the same debate repeatedly.',
    '',
    '### 2.5 Building Product Intuition as an Engineer',
    '',
    'Product intuition is not innate; it is built through deliberate practice:',
    '',
    '1. **Use your own product:** Become a power user of your own product. Log your friction points. Compare with competitors. Note what delights and frustrates you.',
    '',
    '2. **Watch users:** Regularly observe user sessions, support tickets, and feedback channels. Pattern-recognize recurring problems.',
    '',
    '3. **Study metrics:** Develop fluency in your product\'s metrics. Understand what moves them and what does not. Correlate technical changes with metric movements.',
    '',
    '4. **Talk to customers:** Participate in user interviews, customer calls, and on-site visits. Hear problems directly rather than through filtered summaries.',
    '',
    '5. **Read the market:** Follow competitors, adjacent products, and industry trends. Understand what users are comparing your product to.',
    '',
    '6. **Learn the business:** Understand your company\'s business model, revenue drivers, cost structure, and strategic priorities.',
    '',
    '### 2.6 The Product Engineer\'s Decision-Making Framework',
    '',
    'When faced with any decision, the product engineer runs through this sequence:',
    '',
    '1. **What is the user problem?** (Not the feature request, but the underlying need)',
    '2. **What outcome do we want?** (Measurable change in user behavior or business metric)',
    '3. **What is the smallest test?** (Minimum experiment to validate the approach)',
    '4. **What is the cost of being wrong?** (How expensive is it to reverse this decision?)',
    '5. **What does the data say?** (Existing metrics, user research, industry benchmarks)',
    '6. **What do we not know?** (Key assumptions that need validation)',
    '7. **What is the opportunity cost?** (What else will we not build because of this?)',
    '',
    '### 2.7 Engineering Velocity vs. Product Impact',
    '',
    'Velocity is a means, not an end. The goal is not to ship more code; the goal is to ship more product impact per unit of engineering effort. This reframing changes how engineers think about their work:',
    '',
    '**High velocity, low impact:** Building many features that users do not use or value. This is waste.',
    '',
    '**Low velocity, high impact:** Taking too long to ship critical features. This is opportunity cost.',
    '',
    '**High velocity, high impact:** Rapidly shipping features that move product metrics. This is the goal.',
    '',
    '**Low velocity, low impact:** Building unimportant features slowly. This is where organizations fail.',
    '',
    'The product engineer constantly asks: "Is this the highest-impact use of my time right now?"',
    '',
    '### 2.8 The Build-Measure-Learn Loop in Engineering',
    '',
    'The Lean Startup\'s build-measure-learn loop applies directly to engineering work:',
    '',
    '- **Build:** Ship the smallest possible version of a feature',
    '- **Measure:** Instrument the feature to track usage and outcomes',
    '- **Learn:** Analyze the data to determine whether the feature achieved its goal',
    '- **Repeat:** Use learnings to inform the next build iteration',
    '',
    'Engineers own the "measure" part through proper instrumentation. A feature without instrumentation is a feature whose impact cannot be assessed. Every feature should ship with: event tracking, performance monitoring, error tracking, and business metric correlation.',
    '',
    '### 2.9 Technical Leverage',
    '',
    'Technical leverage is the concept that certain technical investments multiply the effectiveness of future engineering work.',
    '',
    '**Low-leverage work:** Fixing bugs in a brittle system, maintaining poorly designed code, working around architectural constraints.',
    '',
    '**High-leverage work:** Building platforms that enable many features, improving developer tooling, paying down targeted technical debt, designing extensible architectures, creating reusable components.',
    '',
    'The product engineer allocates time to high-leverage work because it compounds over time. The key is communicating the product impact of leverage: "This platform investment will let us ship three features per quarter instead of one."',
    '',
    '### 2.10 Managing Technical Risk in Product Context',
    '',
    'Technical risk management is a product concern, not just an engineering concern:',
    '',
    '1. **Identify risks early:** During discovery, flag technical unknowns that could affect feasibility or timeline.',
    '',
    '2. **Quantify probability and impact:** "There is a 30% chance that this approach will not scale past 10,000 users, which would require a rewrite."',
    '',
    '3. **Mitigate through prototypes:** Build technical spikes or proofs-of-concept to retire risk before committing to full implementation.',
    '',
    '4. **Communicate risk in product terms:** "This dependency on an external API means we cannot guarantee checkout uptime during their maintenance windows."',
    '',
    '5. **Maintain risk register:** Track technical risks alongside product risks and revisit them during planning.',
  ];
  lines.forEach(l => w(l));
}

// P3 - Prioritization
function generateP3(w) {
  const lines = [
    '### 3.1 Why Prioritization Matters',
    '',
    'Every engineering organization has more ideas than capacity. Prioritization is the process of determining which ideas to invest engineering time in and in what order. Without a systematic prioritization approach, organizations default to: the loudest stakeholder wins, the most recent idea gets built, or everything becomes a priority (which means nothing is a priority).',
    '',
    'Product engineers participate actively in prioritization because they have critical input: technical feasibility, effort estimates, and architectural dependencies.',
    '',
    '### 3.2 RICE Framework',
    '',
    'RICE is a prioritization framework developed by Intercom that scores initiatives based on four factors:',
    '',
    '**Reach - How many users will this affect in a given time period?**',
    '- Measured in number of users, transactions, or sessions per time period',
    '- Example: "This feature will reach 1,000 users per month"',
    '',
    '**Impact - How much will this affect each user?**',
    '- Typically scored on a scale (massive=3, high=2, medium=1, low=0.5, minimal=0.25)',
    '- Example: "This fix has massive impact on affected users because it unblocks their workflow"',
    '',
    '**Confidence - How confident are we in our estimates?**',
    '- High=100% (we have data), Medium=80% (we have strong proxies), Low=50% (we have weak proxies), Minimal=20% (we are guessing)',
    '- Example: "We have high confidence in reach because we have analytics data, but low confidence in impact because we have not validated the problem"',
    '',
    '**Effort - How much engineering time will this require?**',
    '- Measured in person-months or person-weeks',
    '- Example: "This will require 3 weeks of engineering time"',
    '',
    '**RICE Score = (Reach x Impact x Confidence) / Effort**',
    '',
    '**When to use:** Comparing disparate initiatives across different product areas. Good for quarterly or annual planning.',
    '',
    '**When not to use:** Sprint-level planning or deciding between very similar options.',
    '',
    '**Engineering considerations:**',
    '- Effort estimates must include all costs: design, development, testing, deployment, documentation, and ongoing maintenance',
    '- Confidence should reflect technical uncertainty, not just product uncertainty',
    '- Reach estimates benefit from analytics data that engineers can provide',
    '',
    '### 3.3 ICE Framework',
    '',
    'ICE is a simpler prioritization framework often used in growth engineering:',
    '',
    '**Impact - How much impact will this have on the key metric?** Score 1-10',
    '',
    '**Confidence - How confident are we in the outcome?** Score 1-10',
    '',
    '**Ease - How easy is this to implement?** Score 1-10 (10 = easiest)',
    '',
    '**ICE Score = (Impact + Confidence + Ease) / 3**',
    '',
    '**When to use:** Growth experiments, quick bets, and rapid testing scenarios where speed matters more than precision.',
    '',
    '**When not to use:** Large strategic initiatives with significant investment.',
    '',
    '**Engineering considerations:**',
    '- Ease should account for technical complexity, testing requirements, and deployment risk',
    '- Confidence from an engineering perspective includes technical feasibility confidence',
    '',
    '### 3.4 MoSCoW Framework',
    '',
    'MoSCoW is a stakeholder alignment framework used extensively in agile:',
    '',
    '- **M - Must Have:** Critical for launch. Without this, the solution is invalid.',
    '- **S - Should Have:** Important but not critical. Can be delivered without a second release if necessary.',
    '- **C - Could Have:** Desirable but less important. Only included if time and resources permit.',
    '- **W - Won\'t Have (this time):** Explicitly excluded from this scope.',
    '',
    '**Best practices:**',
    '- Must Haves should be no more than 60% of total effort',
    '- All stakeholders must agree on the classification',
    '- Revisit classification when new information emerges',
    '- "Won\'t Have" is as important as "Must Have" - it manages expectations',
    '',
    '**Engineering considerations:**',
    '- Engineers provide effort estimates that inform whether a feature fits within the Must Have budget',
    '- Technical dependencies often determine which features must be included',
    '- Engineers should flag when a "Could Have" has high technical leverage',
    '',
    '### 3.5 Kano Model',
    '',
    'The Kano Model categorizes features based on how they affect user satisfaction:',
    '',
    '**Basic Needs (Dissatisfiers):** Features users expect by default. Their absence causes dissatisfaction, but their presence does not increase satisfaction. Example: Login functionality, data persistence, basic reliability. **Engineering implication:** These are non-negotiable.',
    '',
    '**Performance Features (Satisfiers):** Features where more is better. Their presence linearly increases satisfaction. Example: Faster performance, more features, better UI. **Engineering implication:** These are where competitive advantage comes from.',
    '',
    '**Delighters (Attractors):** Unexpected features that create positive surprise. Example: Animated transitions, thoughtful micro-interactions. **Engineering implication:** Low-cost, high-impact opportunities.',
    '',
    '**Indifferent Features:** Features users do not care about. **Engineering implication:** Avoid building these.',
    '',
    '**Reverse Features:** Features that some users want and others hate. **Engineering implication:** Need careful configuration and user control.',
    '',
    '**Using the Kano Model:**',
    '1. Survey users with functional and dysfunctional questions',
    '2. Categorize features based on response patterns',
    '3. Prioritize: Basic Needs first, then Performance Features, then Delighters',
    '',
    '### 3.6 Value vs. Effort Matrix',
    '',
    'A two-by-two matrix that plots initiatives by business value and engineering effort:',
    '',
    '**Quadrant strategies:**',
    '- **Quick Wins (High Value, Low Effort):** Do these first. They deliver maximum impact for minimum cost.',
    '- **Big Bets (High Value, High Effort):** Invest if strategically aligned. Break into smaller pieces if possible.',
    '- **Fill-ins (Low Value, Low Effort):** Do when higher-priority work is blocked. Good for junior engineers.',
    '- **Money Pits (Low Value, High Effort):** Avoid or challenge. These waste engineering resources.',
    '',
    '**Engineering considerations:**',
    '- Effort must include maintenance cost over the feature\'s lifetime, not just initial build cost',
    '- Value should be quantified in product metrics where possible',
    '- Strategic value that is not captured by immediate metrics should be noted separately',
    '',
    '### 3.7 Opportunity Scoring',
    '',
    'Developed by Anthony Ulwick, opportunity scoring identifies the gap between how important a feature is and how satisfied users are:',
    '',
    '1. Survey users on two dimensions: Importance (1-10) and Satisfaction (1-10)',
    '2. Calculate: Opportunity Score = Importance + max(Importance - Satisfaction, 0)',
    '3. Prioritize outcomes with the highest opportunity scores',
    '',
    '**Interpretation:**',
    '- High importance + low satisfaction = High opportunity (build this)',
    '- High importance + high satisfaction = Maintain (do not invest further)',
    '- Low importance + low satisfaction = Ignore (users do not care)',
    '- Low importance + high satisfaction = Over-delivered (reduce investment)',
    '',
    '### 3.8 Cost of Delay and WSJF',
    '',
    'Weighted Shortest Job First (WSJF) is a prioritization method that uses Cost of Delay divided by job duration:',
    '',
    '**Cost of Delay Components:**',
    '1. User-business value: Revenue impact, user satisfaction, market share',
    '2. Time criticality: How does value decay over time?',
    '3. Risk reduction and opportunity enablement: What does this unlock?',
    '',
    '**WSJF = Cost of Delay / Job Duration**',
    '',
    '**When to use:** When you have a clear queue of features all ready to build.',
    '',
    '**Engineering considerations:**',
    '- Job duration estimates must be accurate enough to distinguish between options',
    '- Duration includes total cycle time, not just development time',
    '- WSJF prioritizes smaller, high-value items - usually correct but can underweight strategic initiatives',
    '',
    '### 3.9 Combining Frameworks',
    '',
    'No single framework is perfect. Product engineers often combine frameworks:',
    '',
    '**Typical synthesis approach:**',
    '1. Use RICE for high-level prioritization across initiatives',
    '2. Use Value vs. Effort Matrix to visualize the portfolio',
    '3. Use Kano Model to understand how features will be perceived',
    '4. Use MoSCoW to set scope for a specific release',
    '5. Use WSJF to sequence the backlog',
    '',
    '**Framework selection guide:**',
    '- Quarterly planning: RICE or WSJF',
    '- Release planning: MoSCoW',
    '- Experiment prioritization: ICE',
    '- Feature categorization: Kano Model',
    '- Portfolio visualization: Value vs. Effort Matrix',
    '- Improvement prioritization: Opportunity Scoring',
    '',
    '### 3.10 Prioritization Anti-Patterns',
    '',
    '| Anti-Pattern | Symptoms | Correction |',
    '|---|---|---|',
    '| HiPPO (Highest Paid Person\'s Opinion) | Priorities set by seniority, not data | Use structured frameworks, surface data |',
    '| Everything is P0 | No clear priorities, team is overwhelmed | Force rank, limit Must Haves |',
    '| Recency bias | Latest request jumps to top | Queue-based system, cool-off period |',
    '| Pet feature syndrome | Engineer or PM builds what they personally want | Validate with customers and data |',
    '| Scope creep | Must Haves keep expanding | Fixed timebox, defer scope to Won\'t Have |',
    '| Analysis paralysis | Endless prioritization without action | Set timebox for decision, iterate |',
    '| Engineering pet projects | Interesting but low-value technical work | Surface opportunity cost explicitly |',
    '',
    '### 3.11 Effort Estimation for Prioritization',
    '',
    'Engineers provide effort estimates that feed prioritization. Best practices:',
    '',
    '1. **Three-point estimation:** Provide optimistic, most likely, and pessimistic estimates. Use the weighted average: (O + 4M + P) / 6',
    '',
    '2. **Include all phases:** Design, implementation, testing, documentation, deployment, monitoring, post-launch support.',
    '',
    '3. **Account for uncertainty:** Flag areas of technical uncertainty with confidence levels.',
    '',
    '4. **Reference class forecasting:** Compare estimates to similar past projects rather than building from scratch.',
    '',
    '5. **Avoid anchoring:** Provide estimates without knowing what the PM wants to hear.',
    '',
    '6. **Update estimates as you learn:** Initial estimates should be refined as discovery progresses.',
  ];
  lines.forEach(l => w(l));
}

// P4 - Build vs Buy
function generateP4(w) {
  const lines = [
    '### 4.1 Core Framework',
    '',
    'The build vs. buy vs. partner decision is one of the most consequential product engineering decisions. Getting it wrong means wasting months or years of engineering time on non-differentiating work, or committing to external dependencies that become strategic liabilities.',
    '',
    '**The core question:** Is this capability core to our product\'s value proposition, or is it context (necessary but not differentiating)?',
    '',
    '### 4.2 Strategic Fit Assessment',
    '',
    '**Core capabilities** (build):',
    '- Directly differentiate your product in the market',
    '- Are central to your value proposition',
    '- Create intellectual property or data moats',
    '- Are tightly integrated with your user experience',
    '- Require deep product-specific domain knowledge',
    '',
    '**Context capabilities** (consider buy):',
    '- Are necessary but not differentiating',
    '- Are well-solved in the market',
    '- Would require ongoing maintenance that is not core to your team\'s mission',
    '- Have compliance or regulation requirements that are expensive to build',
    '- Are available as commodity services',
    '',
    '### 4.3 Total Cost of Ownership (TCO) Analysis',
    '',
    '**Build costs (3-5 year horizon):**',
    '1. Initial development: Engineering time for design, implementation, testing',
    '2. Ongoing maintenance: Bug fixes, security patches, dependency updates, platform changes',
    '3. Infrastructure: Compute, storage, bandwidth, monitoring',
    '4. Operational overhead: On-call, incident response, capacity planning',
    '5. Opportunity cost: What you could have built instead',
    '6. Technical debt: Future cost of design decisions made under time pressure',
    '',
    '**Buy costs (3-5 year horizon):**',
    '1. Licensing/subscription fees',
    '2. Integration cost: Engineering time to integrate, customize, and connect',
    '3. Migration cost: Data migration, user training, process changes',
    '4. Vendor management: Contract negotiation, vendor evaluation, relationship management',
    '5. Vendor risk: Price increases, vendor acquisition, sunsetting, security incidents',
    '6. Customization costs: Workarounds for features the vendor does not support',
    '7. Exit cost: Cost to migrate away if the vendor relationship ends',
    '',
    '### 4.4 Build Decision Framework',
    '',
    'Build if:',
    '',
    '1. **Differentiation is high:** The capability is core to your product\'s competitive advantage',
    '2. **Control is required:** You need deep customization, integration, or performance optimization',
    '3. **Data moat potential:** Building creates proprietary data or algorithms that improve over time',
    '4. **Existing investment:** You already have significant investment in this area that builds on',
    '5. **Market is immature:** No existing solution adequately solves the problem',
    '6. **Strategic importance:** The capability is central to your long-term product strategy',
    '7. **Scale economics:** At sufficient scale, building is cheaper than buying',
    '',
    '### 4.5 Buy Decision Framework',
    '',
    'Buy if:',
    '',
    '1. **Commodity capability:** The need is well-solved by mature vendors',
    '2. **Non-differentiating:** The capability does not create competitive advantage',
    '3. **Time to market matters:** You need the capability faster than you can build it',
    '4. **Compliance burden:** Regulation, certification, or compliance requirements are costly to build',
    '5. **Specialized expertise:** The capability requires domain expertise you lack',
    '6. **Low integration cost:** The solution is easy to integrate and maintain',
    '7. **Vendor ecosystem:** A thriving ecosystem reduces vendor lock-in risk',
    '',
    '### 4.6 Partner Decision Framework',
    '',
    'Partner if:',
    '',
    '1. **Co-creation opportunity:** Both parties benefit from joint development',
    '2. **Complementary capabilities:** Each party brings different strengths',
    '3. **Market access:** Partner provides distribution, credibility, or market access',
    '4. **Risk sharing:** Shared investment reduces individual risk',
    '5. **Technology access:** Partner has proprietary technology you need',
    '6. **Standards influence:** Partnership allows influence over emerging standards',
    '',
    '**Risks of partnerships:**',
    '- Misaligned incentives over time',
    '- Split priorities and resource contention',
    '- Intellectual property disputes',
    '- Cultural and process mismatches',
    '- Partner lock-in that is harder to escape than vendor lock-in',
    '',
    '### 4.7 Integration Cost Assessment',
    '',
    'Integration cost is often underestimated in buy decisions:',
    '',
    '**Integration cost factors:**',
    '1. API complexity: Number of endpoints, authentication, rate limiting, data formats',
    '2. Data synchronization: Real-time vs. batch, conflict resolution, data transformation',
    '3. User experience: How seamlessly does the external solution fit into your product?',
    '4. Error handling: How do vendor outages and errors affect your users?',
    '5. Monitoring: How do you monitor vendor health and performance?',
    '6. Compliance: Data residency, privacy, security review requirements',
    '7. Testing: Integration test suites, staging environments, sandbox accounts',
    '8. Documentation and support quality, SDK maturity, community size',
    '',
    '**Integration cost estimation:**',
    '- Simple integration (well-documented API, standard use case): 2-4 weeks',
    '- Moderate integration (customization, data sync, auth): 4-12 weeks',
    '- Complex integration (deep customization, real-time sync, compliance): 12-26 weeks',
    '',
    '### 4.8 Vendor Evaluation Criteria',
    '',
    'When evaluating vendors, score each candidate on:',
    '',
    '1. **Functional fit:** How well does the solution meet your requirements? (Weight: 30%)',
    '2. **Technical fit:** API quality, integration ease, performance, reliability (Weight: 20%)',
    '3. **Total cost:** Licensing, overages, professional services, future cost increases (Weight: 15%)',
    '4. **Vendor health:** Financial stability, market position, funding, leadership (Weight: 10%)',
    '5. **Support and SLAs:** Response times, support quality, uptime guarantees, credits (Weight: 10%)',
    '6. **Security and compliance:** SOC2, GDPR, HIPAA, data residency, penetration testing (Weight: 10%)',
    '7. **Ecosystem and community:** Third-party integrations, community, documentation (Weight: 5%)',
    '',
    '### 4.9 Build-Buy Decision Examples',
    '',
    '**Scenario 1: Authentication system**',
    '- Core differentiation? No (users expect auth, it does not differentiate)',
    '- Well-solved market? Yes (Auth0, Clerk, Supabase Auth, AWS Cognito)',
    '- Compliance burden? Yes (SOC2, GDPR, password policies)',
    '- **Decision: Buy** - Use an auth provider, integrate once, move on.',
    '',
    '**Scenario 2: Core recommendation engine**',
    '- Core differentiation? Yes (the quality of recommendations is your product)',
    '- Well-solved market? Partially (generic algorithms exist but domain-specific tuning is key)',
    '- Data moat potential? Yes (proprietary user data and feedback loops improve your algorithm)',
    '- **Decision: Build** - This is your core IP. Invest in custom algorithms.',
    '',
    '**Scenario 3: Payment processing**',
    '- Core differentiation? No (payments are table stakes)',
    '- Well-solved market? Yes (Stripe, Braintree, Adyen)',
    '- Compliance burden? Yes (PCI-DSS is expensive to certify)',
    '- **Decision: Buy** - Use Stripe or similar. PCI compliance alone justifies buying.',
    '',
    '**Scenario 4: Internal reporting dashboard**',
    '- Core differentiation? For internal tools, no',
    '- Well-solved market? Yes (Tableau, Metabase, Looker, Mode)',
    '- **Decision: Buy** - Unless your product is an analytics tool, buy a BI platform.',
    '',
    '**Scenario 5: Real-time collaboration features**',
    '- Core differentiation? Depends on product',
    '- Well-solved market? Partially (Liveblocks, Yjs, PartyKit exist but space is evolving)',
    '- **Decision: Depends on strategy** - If collaboration is core, build. Otherwise buy or partner.',
    '',
    '### 4.10 Migration Cost: The Hidden Factor',
    '',
    '**Migration cost components:**',
    '1. Data migration: Export, transform, validate, import from existing system',
    '2. Feature parity: Ensuring the new system supports all existing user workflows',
    '3. User retraining: Documentation, tutorials, support during transition',
    '4. Parallel running: Period of running both systems during cutover',
    '5. Integration rewrites: Updating all systems that integrate with the old system',
    '6. Testing: Comprehensive regression testing of the migration',
    '7. Rollback plan: Ability to revert if migration fails',
    '',
    '**Migration cost rule of thumb:** Migration costs 50-100% of annual maintenance cost for the current system.',
    '',
    '### 4.11 Making the Recommendation',
    '',
    'When presenting a build vs. buy recommendation, structure it as:',
    '',
    '1. **Executive summary:** What we recommend and why in one paragraph',
    '2. **Requirements summary:** What we need the solution to do',
    '3. **Options considered:** Build option + 2-3 vendor options scored',
    '4. **TCO comparison:** 3-year total cost of ownership for each option',
    '5. **Strategic assessment:** How each option aligns with product strategy',
    '6. **Risk assessment:** Key risks for each option and mitigation strategies',
    '7. **Recommendation:** Clear recommendation with justification',
    '8. **Implementation plan:** If build - timeline and resourcing. If buy - integration plan.',
    '9. **Success metrics:** How we will measure whether the decision was correct',
  ];
  lines.forEach(l => w(l));
}

module.exports = { generateP1, generateP2, generateP3, generateP4 };
