// P5 - Technical Product Decisions
function generateP5(w) {
  const lines = [
    '### 5.1 The Interface Between Technical and Product Decisions',
    '',
    'Technical decisions and product decisions are not separate universes. Every significant technical decision has product implications, and every product decision has technical implications. The product engineer is the bridge between these two domains.',
    '',
    '**Categories of technical product decisions:**',
    '',
    '1. **Architecture decisions with product impact:** The shape of the system constrains what product can do and how quickly.',
    '2. **Implementation decisions with product impact:** How specific features are built affects user experience and future flexibility.',
    '3. **Infrastructure decisions with product impact:** Where and how the system runs affects reliability, performance, and cost.',
    '4. **Data decisions with product impact:** How data is stored, modeled, and accessed affects what insights can be generated.',
    '',
    '### 5.2 Architecture Decisions with Product Impact',
    '',
    '**Monolith vs. Microservices**',
    '',
    'Product impact of monolith:',
    '- Faster feature development in early stages (no service boundaries)',
    '- Simpler deployment and testing (one pipeline to maintain)',
    '- Higher risk of deployment conflicts with larger teams',
    '- Harder to scale specific parts of the system independently',
    '- Better for products where the domain is well-understood and stable',
    '',
    'Product impact of microservices:',
    '- Independent deployability enables faster iteration on specific features',
    '- Team autonomy reduces coordination overhead at scale',
    '- Service boundaries force clean API contracts, which improve reliability',
    '- Higher operational complexity reduces overall velocity initially',
    '',
    '**Decision framework:** Start with a monolith. Extract services when the team grows beyond 2-3 teams, deployment conflicts become a bottleneck, or you need independent deployability.',
    '',
    '**Database Selection**',
    '',
    'Product impact of database choice:',
    '- SQL databases (PostgreSQL, MySQL): Strong consistency, complex queries - good for finance, compliance, inventory',
    '- NoSQL databases (MongoDB, DynamoDB): Flexible schema, horizontal scaling - good for early-stage products',
    '- Search databases (Elasticsearch): Full-text search, analytics - needed for any product with search features',
    '- Time-series databases (InfluxDB, TimescaleDB): Time-series analytics - needed for monitoring, IoT, finance',
    '- Graph databases (Neo4j): Relationship-heavy queries - needed for social networks, recommendation engines',
    '',
    '### 5.3 API Design Decisions with Product Impact',
    '',
    '**REST vs. GraphQL vs. gRPC**',
    '',
    'Product impact of REST: Universal compatibility, simple caching, well-understood, but over-fetching impacts mobile performance.',
    'Product impact of GraphQL: Clients get exactly what they need - critical for mobile, strong typing, but complex caching.',
    'Product impact of gRPC: High performance, low latency, strong contract enforcement, but poor browser support.',
    '',
    '**Decision framework:** Public API: REST. Mobile-first: GraphQL. Internal services: gRPC. Simple CRUD: REST.',
    '',
    '### 5.4 Real-time Decisions',
    '',
    '**WebSockets vs. Server-Sent Events vs. Polling**',
    '',
    '- Polling: Simplest but increases latency and server load. OK for non-time-sensitive features.',
    '- Server-Sent Events: One-way real-time from server to client. Good for notifications, live feeds.',
    '- WebSockets: Bidirectional real-time communication. Needed for collaborative editing, live chat, gaming.',
    '',
    '### 5.5 State Management Decisions',
    '',
    'Product impact: Real-time features need CRDT-based solutions (Yjs, Automerge). Offline-first needs local-first libraries (Replicache, PowerSync, RxDB). Undo/redo is easier with certain patterns.',
    '',
    '### 5.6 Communicating Technical Decisions to Product',
    '',
    'When a technical decision has product implications, use this template:',
    '',
    '**Template:**',
    '## Decision: [Brief title]',
    '### Product Impact Summary',
    '[One paragraph explaining what this means for the product, users, and roadmap]',
    '### Options Considered',
    '1. [Option A] - [Pros and cons in product terms]',
    '2. [Option B] - [Pros and cons in product terms]',
    '### Recommendation',
    '[Which option we recommend and why]',
    '### Product Implications',
    '- User experience: [What users will notice]',
    '- Timeline: [How this affects delivery dates]',
    '- Future features: [What this enables or prevents]',
    '- Cost: [Infrastructure or operational cost changes]',
    '- Risk: [Technical risks and their product impact]',
    '',
    '### 5.7 Architecture Decision Records (ADRs)',
    '',
    'ADRs capture significant architecture decisions and their rationale:',
    '',
    '**ADR Format:**',
    '# ADR-NNN: [Title]',
    '## Status [Proposed | Accepted | Deprecated]',
    '## Context [What is the problem? What constraints are at play?]',
    '## Decision [What did we decide?]',
    '## Consequences (Product-Relevant)',
    '- Positive: [Benefits in product terms]',
    '- Negative: [Trade-offs in product terms]',
    '- Risks: [Technical risks and their product impact]',
    '## Alternatives Considered',
    '',
    '### 5.8 Technical Spikes for Product Decisions',
    '',
    'When a decision has significant product implications and technical uncertainty, run a technical spike:',
    '',
    '**Spike process:**',
    '1. Define the question: What specific technical unknowns need resolution?',
    '2. Timebox: Limit the spike to a fixed duration (1-5 days typically)',
    '3. Build a prototype: Not production-quality code, but enough to answer the questions',
    '4. Evaluate: Test the approach against the criteria that matter for product decisions',
    '5. Document: Write up findings including implications for product timeline and architecture',
    '6. Decide: Use spike results to inform the product decision',
    '',
    '**When to spike:** Evaluating new technology, assessing feasibility with uncertain cost, comparing architectural approaches, understanding scaling characteristics.',
    '',
    '### 5.9 Technology Radar for Product Awareness',
    '',
    '- **Adopt:** Technologies we have high confidence in. Low risk, predictable outcomes.',
    '- **Trial:** Technologies we are exploring. Higher risk, budget for learning curve.',
    '- **Assess:** Technologies we are watching. Inform future capabilities.',
    '- **Hold:** Technologies we have tried and are not investing further.',
    '',
    'Review the radar quarterly with product stakeholders.',
    '',
    '### 5.10 When to Escalate Technical Product Decisions',
    '',
    '**Escalate to product when:**',
    '- The decision affects user-facing behavior or experience',
    '- The decision changes delivery timeline for a committed feature',
    '- The decision requires trade-offs between multiple product goals',
    '- The decision enables or disables future product capabilities',
    '',
    '**Do not escalate to product when:**',
    '- The decision is purely internal (coding standards, test framework, CI/CD tool)',
    '- The decision has no user-facing impact',
    '- The decision is easily reversible',
  ];
  lines.forEach(l => w(l));
}

// P6 - Customer Development
function generateP6(w) {
  const lines = [
    '### 6.1 Why Engineers Should Talk to Customers',
    '',
    'Many engineers resist customer interviews, believing that customer contact is the product manager\'s job. This is a mistake. Engineers who talk to customers:',
    '',
    '1. Build deeper empathy for user problems, which improves their technical decision-making',
    '2. Hear problems directly rather than through filtered interpretation',
    '3. Ask better technical questions about existing workarounds, integrations, and constraints',
    '4. Develop product intuition that leads to better prioritization decisions',
    '5. Feel more motivated and connected to the product mission',
    '6. Can identify quick technical wins that product managers might miss',
    '',
    '### 6.2 The Engineer\'s Role in Customer Development',
    '',
    '**Mode 1: Observer** - Sit in on customer interviews, take notes on technical implications, ask follow-up questions. Time: 1 hour per session.',
    '',
    '**Mode 2: Participant** - Co-conduct interviews with product managers, lead the technical portion. Time: 2-3 hours per session.',
    '',
    '**Mode 3: Lead** - Plan and conduct independent customer interviews, focus on technical validation. Time: 4-6 hours per session.',
    '',
    '**Mode 4: Embedded** - Regular structured customer engagement, build ongoing relationships with key customers. Time: 2-4 hours per week.',
    '',
    '### 6.3 Problem Validation Interviews',
    '',
    '**Interview structure:**',
    '',
    '1. **Warm-up (5 min):** Build rapport. Explain context. Confirm recording consent.',
    '',
    '2. **Storytelling (20 min):** Ask about the last time they encountered the problem.',
    '   - "Tell me about the last time you had to [do this task]."',
    '   - "Walk me through exactly what you did, step by step."',
    '   - "What tools did you use? What was frustrating?"',
    '',
    '3. **Current solutions (10 min):** Understand what they do today.',
    '   - "How do you solve this problem currently?"',
    '   - "What do you like about your current approach?"',
    '   - "What frustrates you about it?"',
    '',
    '4. **Impact assessment (10 min):** Quantify the problem.',
    '   - "If you could wave a magic wand, what would the ideal solution look like?"',
    '   - "How much money/time does this problem cost you per month?"',
    '   - "Have you already paid for a solution to this? Would you?"',
    '',
    '**Red flags:** Customer cannot recall a specific instance, has a working workaround, cannot quantify impact, describes the solution not the problem.',
    '',
    '### 6.4 Solution Validation Interviews',
    '',
    '**Interview structure:**',
    '',
    '1. **Reframe the problem (5 min):** Ensure they remember the problem we discussed.',
    '',
    '2. **Present the solution (10 min):** Show a low-fidelity prototype, emphasize this is a concept.',
    '',
    '3. **Gather reactions (15 min):**',
    '   - "What is your initial reaction to this idea?"',
    '   - "What do you like about it?"',
    '   - "What concerns or questions do you have?"',
    '   - "Would this solve the problem we discussed?"',
    '',
    '4. **Probe specifics (10 min):**',
    '   - "Who else would need to be involved in using this?"',
    '   - "Where would this fit in your workflow?"',
    '   - "What features did you expect that are missing?"',
    '',
    '5. **Prioritize (5 min):**',
    '   - "If we could only build one feature, which would it be?"',
    '   - "Would you be willing to pay for this? How much?"',
    '',
    '**Red flags:** Customer is too polite, cannot articulate workflow fit, suggests major structural changes, compares unfavorably to existing solutions.',
    '',
    '### 6.5 Usability Testing for Engineers',
    '',
    '**Test structure:**',
    '',
    '1. Set up scenarios: Define specific tasks. Do not explain how the product works.',
    '2. Observe silently: Let the user struggle. Note hesitation, confusion, clicks.',
    '3. Measure: Time on task, errors, success rate.',
    '4. Think-aloud protocol: "What are you thinking right now? What do you expect to happen?"',
    '',
    '**Usability testing metrics:**',
    '- Task success rate: Percentage of users who complete the task',
    '- Time on task: Average time to complete',
    '- Error rate: Number of errors per task',
    '- SUS Score: System Usability Scale',
    '- NPS: Would you recommend this?',
    '',
    '**Common usability issues:**',
    '- Inconsistent terminology between UI and user mental model',
    '- Hidden functionality that users cannot find',
    '- Confusing error messages or unhelpful error states',
    '- Too many steps for common tasks',
    '- Lack of feedback after actions',
    '',
    '### 6.6 Recruiting for Customer Interviews',
    '',
    '**Recruitment sources:** Support tickets, in-app surveys, email lists, social media, customer success, user advisory board, paid recruitment (User Interviews, Respondent.io).',
    '',
    '**Screening criteria:** Persona match, recency of experience, willingness to be critical, diversity of usage patterns.',
    '',
    '**Compensation:** Consumers $25-50, Professionals $75-150, Enterprise $150-300+.',
    '',
    '### 6.7 Interview Best Practices',
    '',
    '**Do:** Ask open-ended questions, listen 80% of the time, ask "why" repeatedly (5 Whys), probe on specifics, stay neutral, take notes, focus on behavior not opinions.',
    '',
    '**Do not:** Pitch your solution, confuse a compliment with validation, lead the witness, defend ideas when criticized, ask "Would you use this?" (they will say yes).',
    '',
    '**Common mistakes:**',
    '1. Asking hypothetical questions instead of behavioral questions',
    '2. Confirming your bias - only hearing what supports your hypothesis',
    '3. The nod-and-smile trap - polite positive feedback that is not real',
    '4. Expert blind spot - assuming users think like engineers',
    '',
    '### 6.8 Synthesizing Customer Insights',
    '',
    '1. **Capture raw notes:** Transcribe or summarize each interview immediately.',
    '2. **Extract key quotes:** Identify verbatim quotes that capture important insights.',
    '3. **Identify patterns:** Look for recurring themes across interviews.',
    '4. **Create an affinity map:** Group insights into themes.',
    '5. **Assess confidence:** How many users expressed this? How strong was the evidence?',
    '6. **Prioritize insights:** Severity, frequency, strategic fit, technical feasibility.',
    '7. **Share findings:** One-page summary, video clips of key moments, recommendations.',
    '',
    '### 6.9 Integrating Customer Development into Engineering Cadence',
    '',
    '**Weekly:** Review support tickets (15 min), check session recordings (15 min), review feedback (5 min).',
    '',
    '**Monthly:** Participate in at least one customer interview (1 hour), review product analytics (30 min).',
    '',
    '**Quarterly:** Conduct problem interviews for upcoming initiatives (4-8 hours), usability testing (2-4 hours), present insights to team (1 hour).',
  ];
  lines.forEach(l => w(l));
}

// P7 - Product Discovery
function generateP7(w) {
  const lines = [
    '### 7.1 What Is Product Discovery',
    '',
    'Product discovery is the process of determining what to build before committing significant engineering resources. It answers two questions:',
    '',
    '1. **Will users use it?** (Value risk - does anyone want this?)',
    '2. **Can we build it?** (Feasibility risk - can we deliver this?)',
    '',
    'Product discovery reduces the risk of building the wrong thing. It is an ongoing practice that continues through delivery.',
    '',
    '### 7.2 Problem Space vs. Solution Space',
    '',
    '**Problem space:** The user\'s world - their goals, frustrations, context, and constraints.',
    '',
    '**Solution space:** The product interventions we build.',
    '',
    'Many teams jump directly to solution space without fully exploring problem space. This leads to building solutions that do not address the real problem.',
    '',
    '**Discovery process:**',
    '1. Explore problem space (divergent): Understand the problem broadly',
    '2. Define the problem (convergent): Scope the specific problem to solve',
    '3. Explore solution space (divergent): Generate multiple solution approaches',
    '4. Define the solution (convergent): Select and validate the best approach',
    '',
    '### 7.3 The Discovery Process',
    '',
    '**Phase 1: Problem Exploration**',
    'Goal: Understand the problem deeply before considering solutions.',
    'Activities: Customer interviews, user observation, data analysis, competitive analysis, market research, stakeholder interviews.',
    'Output: Problem statement, user personas, jobs-to-be-done mapping, assumptions list.',
    '',
    '**Phase 2: Solution Exploration**',
    'Goal: Generate and test potential solutions.',
    'Activities: Brainstorming, rapid prototyping, solution interviews, technical spikes, business model testing.',
    'Output: Solution hypotheses, prototypes, technical feasibility assessment, implementation options.',
    '',
    '**Phase 3: Assumption Testing**',
    'Goal: Identify and test the riskiest assumptions before committing to build.',
    'Activities: Assumption mapping, experiment design, landing page tests, concierge tests, Wizard of Oz tests.',
    'Output: Validated assumptions, invalidated assumptions, updated confidence levels, go/no-go decision.',
    '',
    '**Phase 4: Validation**',
    'Goal: Confirm the solution is valuable, usable, and feasible before building at scale.',
    'Activities: Usability testing, A/B testing, beta release, customer pilot programs.',
    'Output: Validated product hypothesis, backlog for MVP, success metrics, technical architecture.',
    '',
    '### 7.4 Hypothesis-Driven Development',
    '',
    'Frame discovery and delivery work as hypotheses:',
    '',
    '**Hypothesis format:**',
    'We believe that [solution] for [user segment] will achieve [outcome] as measured by [metric]. We will know this is true when [specific success criterion].',
    '',
    '**Why hypotheses matter:**',
    '- They make assumptions explicit',
    '- They define success criteria upfront',
    '- They create shared understanding between engineering and product',
    '- They make it clear when to persevere vs. pivot',
    '- They force instrumentation and measurement',
    '',
    '### 7.5 Assumption Mapping',
    '',
    'Map assumptions on two axes:',
    '1. How critical is this assumption? (If wrong, does the whole thing fail?)',
    '2. How confident are we? (Evidence or guessing?)',
    '',
    'Focus testing on:',
    '- **Critical unknowns:** High criticality + Low confidence (test these first)',
    '- **Core beliefs:** High criticality + High confidence (monitor for disconfirming evidence)',
    '- **Nice-to-know:** Low criticality + Low confidence (test if time permits)',
    '- **Established facts:** Low criticality + High confidence (build on these)',
    '',
    '### 7.6 Discovery Techniques for Engineers',
    '',
    '**Technical spikes:** Build quick prototypes to test feasibility of unproven technology, third-party integration, or performance assumptions.',
    '',
    '**Data analysis:** Use analytics to validate problem assumptions - reach, frequency, baseline behavior, workarounds.',
    '',
    '**Prototyping:** Build functional prototypes for more accurate feedback than design mockups.',
    '',
    '**Wizard of Oz testing:** Build what appears to be automated but is manually operated.',
    '',
    '**Concierge testing:** Manually deliver the service to a small set of users.',
    '',
    '### 7.7 Discovery Governance',
    '',
    '**Stages and gates:**',
    '1. Problem definition - Gate: Problem statement signed off by product and engineering',
    '2. Solution hypothesis - Gate: Hypothesis documented with success criteria',
    '3. Technical feasibility - Gate: Spike completed or feasibility confirmed',
    '4. Assumption testing - Gate: Critical assumptions validated',
    '5. Validation - Gate: Beta confirms value proposition',
    '6. Launch - Gate: All success criteria defined, instrumentation in place',
    '',
    '### 7.8 Discovery Sprints',
    '',
    'A discovery sprint is a time-boxed period (1-4 weeks):',
    '',
    '**Week 1 - Understand:** Review data, conduct 8-12 interviews, map problem space, identify assumptions.',
    '',
    '**Week 2 - Ideate:** Brainstorm solutions, rapid prototyping, technical spikes, solution interviews.',
    '',
    '**Week 3 - Test:** Assumption testing experiments, usability testing of prototypes, refine hypothesis.',
    '',
    '**Week 4 - Decide:** Present findings, make go/no-go decisions, prepare delivery backlog.',
    '',
    '### 7.9 When to Stop Discovery',
    '',
    'Signs it is time to move to delivery:',
    '1. Confidence is high enough - critical assumptions validated',
    '2. Diminishing returns - each interview tells you less',
    '3. Time pressure - market window requires delivery to start',
    '4. Sufficient clarity - you know enough to move the metric',
    '5. Need to learn from real usage - some assumptions require shipping',
    '',
    '### 7.10 Discovery Outputs',
    '',
    'A discovery process should produce:',
    '1. Problem statement',
    '2. User segment definition',
    '3. Solution hypothesis',
    '4. Success metrics',
    '5. Assumptions and confidence levels',
    '6. Options considered',
    '7. Technical assessment (feasibility, effort, architecture)',
    '8. Delivery recommendations',
  ];
  lines.forEach(l => w(l));
}

// P8 - Technical Debt
function generateP8(w) {
  const lines = [
    '### 8.1 What Is Technical Debt in Product Terms',
    '',
    'Technical debt is the gap between the current state of the codebase and the ideal state required to efficiently deliver product value. Like financial debt, technical debt accumulates interest - paid in slower feature development, increased bug rates, and higher maintenance costs.',
    '',
    'The product engineer translates technical debt into product terms:',
    '- **Not:** "We need to refactor because it violates the single responsibility principle."',
    '- **But:** "Our authentication code slows every login feature by 40% because it is hard to change safely."',
    '',
    '### 8.2 Types of Technical Debt and Their Product Impact',
    '',
    '| Type | Description | Product Impact |',
    '|---|---|---|',
    '| Code debt | Poor structure, duplication, low test coverage | Slower development, more bugs, regressions |',
    '| Architecture debt | Tight coupling, missing abstractions | Harder to add features, fragile system |',
    '| Infrastructure debt | Manual deployment, missing monitoring | Longer lead times, unreliable releases |',
    '| Testing debt | Low coverage, slow suites, flaky tests | Low confidence, regressions reach production |',
    '| Documentation debt | Missing APIs, no runbooks | Onboarding friction, slow incident response |',
    '| Dependency debt | Outdated libraries, unsupported deps | Security vulnerabilities, migration urgency |',
    '| Data debt | Poor models, missing indexes, quality | Slow queries, inconsistent data |',
    '',
    '### 8.3 Quantifying Technical Debt in Product Terms',
    '',
    '**Velocity impact:**',
    '- Feature A takes 2 weeks instead of 1 = 50% velocity tax',
    '- Each feature requires touching 5 files instead of 2 = 150% more development time',
    '- 25% of sprint capacity consumed by debt-related work',
    '',
    '**Quality impact:**',
    '- 15% of deployments cause regressions requiring hotfixes',
    '- 3 production incidents per month from known architectural weaknesses',
    '- 40% of support tickets trace to known debt areas',
    '',
    '**Opportunity cost:**',
    '- Features not built because team is busy with debt',
    '- Slow response to competitive moves',
    '- Inability to experiment due to missing infrastructure',
    '',
    '### 8.4 The Technical Debt Register',
    '',
    'Maintain a living document with product-relevant information:',
    '',
    '| ID | Area | Description | Product Impact | Effort | Interest Rate | Priority |',
    '|---|---|---|---|---|---|---|',
    '| TD-001 | Auth | Monolithic auth service | Each auth feature takes 2x longer | 3 weeks | High | P1 |',
    '| TD-002 | Search | Missing search indexing | Slow search causing 20% bounce rate | 1 week | Medium | P2 |',
    '| TD-003 | CI/CD | Flaky test suite | 2 hours/week wasted on reruns | 2 weeks | Low | P3 |',
    '',
    '**Interest Rate:** High = paying more every sprint. Medium = stable but significant. Low = minimal and stable.',
    '',
    '### 8.5 Prioritizing Technical Debt',
    '',
    '**Criteria:**',
    '1. Product impact - how much does this debt degrade the product experience?',
    '2. Frequency of impact - how often does this debt cause pain?',
    '3. Number of features affected - how many areas are constrained?',
    '4. Fix complexity - how risky and time-consuming is the fix?',
    '5. Decay rate - is this debt getting worse over time?',
    '',
    '### 8.6 Communicating Debt to Product Stakeholders',
    '',
    '**Framework:**',
    '',
    '1. **Start with the impact:** "The checkout feature is taking longer because our payment code is hard to change safely."',
    '',
    '2. **Quantify the cost:** "This debt adds 3 days to every sprint - 15% fewer features per quarter."',
    '',
    '3. **Explain the fix in product terms:** "A 2-week refactoring will make each future payment feature ship 40% faster and reduce payment bugs by 60%."',
    '',
    '4. **Offer options:**',
    '   - Option A: Fix now - 2 weeks investment, then velocity improves',
    '   - Option B: Defer - accept current velocity tax',
    '   - Option C: Partial fix - worst parts now, defer the rest',
    '',
    '5. **Get agreement on trade-off:** "If we defer, the next two payment features will take 50% longer. Is that acceptable?"',
    '',
    '### 8.7 Building a Business Case for Debt Reduction',
    '',
    '**Template:**',
    '## Business Case: [Debt Reduction Initiative]',
    '### Current Situation [What is the current state?]',
    '### Cost of Inaction [Velocity impact, risk, opportunity cost]',
    '| Metric | Current | Projected (6mo) | Projected (12mo) |',
    '|---|---|---|---|',
    '| Feature velocity | X features/sprint | Y | Z |',
    '| Bug rate | A bugs/month | B | C |',
    '### Investment Required [Effort to fix]',
    '### Expected Benefits [Quantified improvements]',
    '### Recommendation [Go/no-go]',
    '',
    '### 8.8 The Boy Scout Rule',
    '',
    '"Leave the codebase cleaner than you found it."',
    '- When modifying a file, spend 10-15% improving its structure',
    '- Fix related debt when working in an area',
    '- Track deferred debt with TODO comments linked to the register',
    '- Budget 20% of each sprint for debt reduction ("golden 20%" rule)',
    '',
    '### 8.9 Strategic vs. Tactical Technical Debt',
    '',
    '**Strategic debt:** Deliberately incurred to achieve a product goal. Managed debt with known cost and repayment plan.',
    '',
    '**Tactical debt:** Unintentional debt from pressure, shortcuts, or lack of knowledge. Dangerous because it has no repayment plan.',
    '',
    'The product engineer: Strategic debt - document, set repayment plan. Tactical debt - fix it or add to register.',
    '',
    '### 8.10 When to Accept Technical Debt',
    '',
    '**Accept when:**',
    '1. Testing a hypothesis - rapid validation matters more than code quality',
    '2. Market window - genuine time-to-market advantage',
    '3. Exploratory feature - may be removed if it does not work',
    '4. Platform uncertainty - underlying tech is changing soon',
    '5. Small cost, large gain - easy to fix later',
    '',
    '**Decline when:**',
    '1. Core system - affects everything built on top',
    '2. Security or compliance - creates vulnerabilities',
    '3. Compound interest - others will build on flawed foundation',
    '4. Team productivity - slows the entire team',
    '5. Long-lived feature - expected to exist for years',
  ];
  lines.forEach(l => w(l));
}

// P9 - Engineering ROI
function generateP9(w) {
  const lines = [
    '### 9.1 What Is Engineering ROI',
    '',
    'Engineering ROI transforms engineering from a cost center to a value center by making explicit the value that engineering work creates.',
    '',
    '**The fundamental equation:** ROI = (Value Delivered - Cost of Delivery) / Cost of Delivery',
    '',
    '### 9.2 Cost of Delay',
    '',
    'Cost of Delay quantifies the cost of not shipping a feature.',
    '',
    '**Components:**',
    '1. **Revenue loss:** Direct revenue not captured while delayed',
    '2. **Cost savings delay:** Operational savings not realized until the feature ships',
    '3. **Competitive disadvantage:** Market share lost to competitors',
    '4. **Customer retention impact:** Users who churn because of delayed features',
    '5. **Opportunity cost:** Engineering time spent on this instead of something else',
    '',
    '**Cost of Delay template:**',
    '| Feature | Revenue/Month | Cost Savings/Month | Competitive Risk | Total Delay Cost/Month | Delay Duration | Total Cost |',
    '|---|---|---|---|---|---|---|',
    '| Feature A | $10K | $0 | High | $15K | 3 months | $45K |',
    '| Feature B | $0 | $5K | Low | $5K | 2 months | $10K |',
    '',
    '### 9.3 Feature Development Cost',
    '',
    '**Direct costs:** Engineering time (hours x blended hourly rate), design time, PM time, QA time.',
    '',
    '**Indirect costs:** Infrastructure and tooling, opportunity cost, coordination cost.',
    '',
    '**Maintenance cost (ongoing):** Bug fixes, support burden, monitoring and operations, feature maintenance, compliance.',
    '',
    '**Total Cost of Feature (3-year view):** Total = Development Cost + (Monthly Maintenance Cost x 36)',
    '',
    '### 9.4 Maintenance Cost Estimation',
    '',
    '**Rule of thumb:** Annual maintenance cost is typically 15-25% of initial development cost.',
    '',
    '**Factors that increase maintenance cost:** Tight coupling, external dependencies, complex configuration, heavy compliance, multiple platforms, high user visibility.',
    '',
    '**Factors that decrease maintenance cost:** Clean code, comprehensive test coverage, feature flags, good monitoring, documented decisions, simple scope.',
    '',
    '### 9.5 Opportunity Cost Analysis',
    '',
    'Every feature built means features not built. Opportunity cost is the value of the best alternative use of engineering time.',
    '',
    '**Framework:**',
    '1. Generate ranked list of potential features',
    '2. Opportunity cost of Feature A = value of Feature B (next best alternative)',
    '3. Compare: Is Value(A) - Cost(A) > Value(B) - Cost(B)?',
    '',
    '**Practical application:** When asked "Can we add X?", respond: "Adding X means deferring Y. Is that the right trade-off?"',
    '',
    '### 9.6 ROI Calculation Examples',
    '',
    '**Example 1: Automation feature**',
    'Feature: Automate invoice generation',
    'Development cost: $50,000 (8 weeks)',
    'Maintenance cost: $5,000/year',
    'Expected life: 3 years',
    'Total cost (3yr): $65,000',
    'Value: Saves 20 hours/week = $30,000/year, reduces errors = $5,000/year',
    'Total value (3yr): $105,000',
    'ROI = ($105,000 - $65,000) / $65,000 = 61.5%',
    '',
    '**Example 2: Growth experiment infrastructure**',
    'Development cost: $80,000 (3 months)',
    'Maintenance cost: $15,000/year',
    'Expected life: 5 years',
    'Total cost (5yr): $155,000',
    'Value: 20 experiments/year, 10 successful, 2% conversion improvement on $10M revenue',
    'Revenue improvement: $200,000/year',
    'Total value (5yr): $1,000,000',
    'ROI = ($1,000,000 - $155,000) / $155,000 = 545%',
    '',
    '**Example 3: Technical debt reduction**',
    'Development cost: $30,000 (3 weeks)',
    'Current cost of debt: 30% velocity tax ($10K/month) + 2 incidents/month ($5K/month) = $15K/month',
    'After refactor: 10% tax ($3K/month) + 0.5 incidents/month ($1.5K/month) = $4.5K/month',
    'Monthly savings: $10,500',
    'ROI (12-month): Savings = $126,000, Cost = $30,000, ROI = 320%',
    '',
    '### 9.7 ROI Communication for Product Decisions',
    '',
    '**Template:**',
    '## ROI Analysis: [Feature Name]',
    '### Investment',
    '- Development effort: [X weeks, Y engineers]',
    '- One-time cost: $[amount]',
    '- Ongoing cost: $[amount/month]',
    '### Expected Return',
    '- Revenue impact: $[amount/year] ([basis])',
    '- Cost savings: $[amount/year] ([basis])',
    '- Strategic value: [non-quantifiable benefits]',
    '### ROI Calculation',
    '- 1-year ROI: [X]%',
    '- 3-year ROI: [Y]%',
    '- Payback period: [Z months]',
    '### Recommendation',
    '[Proceed, proceed with caveats, or defer]',
    '',
    '### 9.8 Sensitivity Analysis',
    '',
    'Test how robust ROI is to assumption changes:',
    '- What if development takes 50% longer?',
    '- What if adoption is half of expected?',
    '- What if maintenance cost is double?',
    '',
    'If ROI remains acceptable even in worst case, the investment is robust.',
    '',
    '### 9.9 Non-Financial ROI Factors',
    '',
    '1. **Strategic alignment:** Does this move us toward our long-term product vision?',
    '2. **Learning value:** What will we learn, even if the feature does not succeed?',
    '3. **Platform value:** Does this enable other features or make them cheaper?',
    '4. **Brand value:** Does this improve brand perception?',
    '5. **Team morale:** Does this work energize or drain the team?',
    '6. **Technical debt impact:** Does this increase or decrease technical debt?',
    '',
    '### 9.10 ROI Decision Framework',
    '',
    '1. Estimate the value',
    '2. Estimate the cost (development + maintenance + opportunity)',
    '3. Calculate ROI: (Value - Cost) / Cost',
    '4. Check payback period',
    '5. Sensitivity analysis',
    '6. Compare to alternatives',
    '7. Strategic alignment check',
    '8. Make the decision: Go, no-go, or revise scope',
  ];
  lines.forEach(l => w(l));
}

// P10 - Product Strategy
function generateP10(w) {
  const lines = [
    '### 10.1 What Is Technical Product Strategy',
    '',
    'Technical product strategy is the intersection of technology strategy and product strategy. It answers: "What technical capabilities do we need to build to deliver our product vision, and in what order?"',
    '',
    '**Considerations:**',
    '- What features are enabled or constrained by technical choices',
    '- How technology investments compound to create competitive advantage',
    '- Which capabilities are differentiating (build) vs. table stakes (buy)',
    '- How architecture shapes the product future possibilities',
    '',
    '### 10.2 Platform vs. Product Thinking',
    '',
    '**Product thinking:** Build features that directly deliver user value. Risk: Short-term thinking, duplicative efforts.',
    '',
    '**Platform thinking:** Build capabilities that enable features to be built faster. Risk: Over-engineering abstractions nobody needs.',
    '',
    '**The balance:**',
    '- Early-stage: Heavy on product thinking (speed of learning matters)',
    '- Growth-stage: Increase platform investment (duplication becomes bottleneck)',
    '- Mature-stage: Balance both (platform enables efficient feature delivery)',
    '',
    '**Platform investment triggers:**',
    '- Three or more teams building similar capabilities independently',
    '- Feature delivery blocked by infrastructure limitations',
    '- New features taking longer because rebuilding foundational capabilities',
    '- Onboarding takes weeks due to system complexity',
    '',
    '### 10.3 API-First Strategy',
    '',
    'Design the API before building the implementation, treating the API as a first-class product.',
    '',
    '**Benefits:** Multiple clients consume the same API, parallel development, third-party integrations are natural, clear contracts, easier testing.',
    '',
    '**Principles:** Design API as product, version from day one, consistent patterns, comprehensive error handling, rate limiting from start, autogenerated docs.',
    '',
    '**API as product metrics:** Adoption (consumers, endpoints, integrations), Performance (latency, error rate), Developer experience (time to first call), Business (revenue, feature adoption).',
    '',
    '### 10.4 Extensibility as a Product Strategy',
    '',
    '**Forms of extensibility:**',
    '',
    '1. **Plugins and extensions:** Third-party capabilities. Examples: VS Code extensions, Shopify apps, Slack integrations.',
    '',
    '2. **Customization:** Users configure the product. Examples: Custom fields, workflows, templates.',
    '',
    '3. **Integrations:** Connect with other tools. Examples: Webhooks, OAuth, native integrations.',
    '',
    '4. **Embedded code:** Users inject custom scripts. Examples: Custom CSS, JavaScript injection.',
    '',
    '**Extensibility decision framework:**',
    '| Type | User Need | Complexity | Maintenance | Strategic Value |',
    '|---|---|---|---|---|',
    '| Custom fields | High | Low | Low | High |',
    '| Webhooks | High | Medium | Medium | High |',
    '| Plugin API | Medium | High | High | Very High |',
    '| Custom scripting | Low | Very High | Very High | Medium |',
    '',
    '### 10.5 Product-Led Growth Technical Enablers',
    '',
    '**1. Self-service onboarding:** Multi-tenant architecture, automated provisioning, guided flows, sample data.',
    '',
    '**2. Freemium and free trial:** Feature flags for tier gating, usage tracking, billing integration, graceful degradation at limits.',
    '',
    '**3. Viral loops:** Invitation system, shared workspaces, permission management, social sharing.',
    '',
    '**4. Usage-based pricing:** Usage tracking infrastructure, billing API, rate limiting, soft/hard limits.',
    '',
    '**5. Time-to-value optimization:** User segmentation, progressive onboarding, analytics to track time-to-value.',
    '',
    '### 10.6 Technical Moat',
    '',
    '**Types:**',
    '',
    '1. **Data network effects:** Product improves as more users use it. Technical requirement: Data pipeline, ML infrastructure, feedback loops.',
    '',
    '2. **Scale economics:** Product becomes cheaper to operate as usage grows. Technical requirement: Efficient architecture, auto-scaling.',
    '',
    '3. **Ecosystem lock-in:** Users invest in integrations tied to your platform. Technical requirement: Plugin API, integration SDK.',
    '',
    '4. **Performance advantage:** Product is faster or more reliable. Technical requirement: Performance engineering, CDN strategy.',
    '',
    '5. **Unique data:** Proprietary data competitors cannot access. Technical requirement: Data collection, data governance, privacy compliance.',
    '',
    '### 10.7 Technical Strategy Documentation',
    '',
    '**Template:**',
    '# Technical Product Strategy',
    '## Vision [Where are we going in 2-3 years?]',
    '## Strategic Principles [What guides our technical decisions?]',
    '## Current State Assessment [What is working? What is blocking us?]',
    '## Strategic Themes [Themes with success criteria]',
    '## Key Initiatives [12-month horizon with expected impact]',
    '## Technology Radar [Adopt, Trial, Assess, Hold]',
    '## Platform Investments [Roadmap]',
    '## Risks and Mitigations',
    '',
    '### 10.8 Strategic Bets vs. Tactical Moves',
    '',
    '**Strategic bets:** High investment, high uncertainty, high return. Create new capabilities or market positions.',
    '',
    '**Tactical moves:** Smaller investment, clearer ROI, lower risk. Incremental improvements.',
    '',
    '**Portfolio approach:** 70% tactical moves, 20% strategic bets, 10% exploratory work.',
    '',
    '### 10.9 Technical Strategy Review Cadence',
    '',
    '**Quarterly:** Review progress against strategic themes, assess competitive landscape, update radar, adjust priorities.',
    '',
    '**Annual:** Full strategy refresh, assess technical moat, major adoption decisions, platform roadmap, resource allocation.',
    '',
    '### 10.10 Communicating Technical Strategy to Stakeholders',
    '',
    '1. **Start with the product outcome:** "This strategy will let us ship features 3x faster."',
    '2. **Use analogies:** "Think of our platform as city infrastructure."',
    '3. **Show cost of not investing:** "Without this, we cannot support real-time features competitors already ship."',
    '4. **Break into phases:** "Phase 1 is foundational. Phase 2 delivers user-facing benefits."',
    '5. **State trade-offs:** "20% less feature capacity this quarter for 50% more next year."',
    '6. **Use metrics:** Tie to revenue, retention, speed, cost.',
  ];
  lines.forEach(l => w(l));
}

module.exports = { generateP5, generateP6, generateP7, generateP8, generateP9, generateP10 };
