// P16 - MVP Methodology
function generateP16(w) {
  const lines = [
    '### 16.1 What Is an MVP',
    '',
    'A Minimum Viable Product (MVP) is the smallest version of a product that can be shipped to validate a hypothesis and begin the build-measure-learn cycle.',
    '',
    '**Common misconceptions:**',
    '- MVP is not a prototype - it is a real product real users can use',
    '- MVP is not the first version of a finished product - it is a learning vehicle',
    '- MVP is not always a product - it can be a landing page, concierge service, or video',
    '- MVP is not about building less - it is about learning more per unit of effort',
    '',
    '### 16.2 MVP Scope Determination',
    '',
    '**Framework:**',
    '1. What is the core hypothesis we need to test?',
    '2. What is the smallest set of features that allows us to test that hypothesis?',
    '3. What is the minimum feature set that delivers value to early adopters?',
    '4. What can we do manually that we would otherwise automate?',
    '5. What can we skip entirely (polish, edge cases, scale)?',
    '',
    '**Scope criteria:**',
    '- Does this feature directly support the core hypothesis?',
    '- Can the product function without this feature?',
    '- Can we add this later without a complete rewrite?',
    '- Will early adopters tolerate the absence of this feature?',
    '- Does this feature significantly increase build time?',
    '',
    '### 16.3 Build-Measure-Learn in Practice',
    '',
    '**Build:** Ship the MVP with minimal features. Focus on speed over quality (within reason). Accept technical debt with a repayment plan. Instrument everything from day one.',
    '',
    '**Measure:** Track the metrics that test the hypothesis. Collect qualitative feedback from early users. Monitor usage patterns. Measure the funnel from awareness to value.',
    '',
    '**Learn:** Did the hypothesis validate? What did users actually do? What new questions emerged? Should we persevere, pivot, or kill?',
    '',
    '**Repeat:** Based on learnings, define the next hypothesis. Prioritize the next set of features. Ship, measure, learn again.',
    '',
    '### 16.4 Types of MVPs',
    '',
    '**1. Landing page MVP:** Create a landing page describing the product. Measure sign-ups. No product built. Best for: Testing demand before building.',
    '',
    '**2. Concierge MVP:** Manually deliver the service. No automation. Learn what users actually need. Best for: Complex services where automation is expensive.',
    '',
    '**3. Wizard of Oz MVP:** Appears automated but is manual. Users believe they interact with software. Best for: AI/ML products, complex workflows.',
    '',
    '**4. Single-feature MVP:** One core feature. No secondary features, configuration, or edge cases. Best for: Products with a focused value proposition.',
    '',
    '**5. Prototype MVP:** Interactive prototype that looks real. Limited or no backend - hardcoded data. Best for: Testing UX assumptions before building infrastructure.',
    '',
    '**6. Piecemeal MVP:** Use existing tools and platforms. No custom development - just integration. Best for: Testing market without engineering investment.',
    '',
    '### 16.5 Iterative Delivery',
    '',
    '**Iteration cycle:** Define hypothesis, identify smallest feature set, build and ship, measure outcomes, learn and decide, repeat.',
    '',
    '**Frequency:** Early-stage every 1-2 weeks, Growth-stage every 2-4 weeks, Mature every 2-4 weeks.',
    '',
    '**Scope management:** Fixed timebox, variable scope. Cut ruthlessly. Ship when core value proposition is testable, not when feature is "done."',
    '',
    '### 16.6 Pivots vs. Perseverance',
    '',
    '**Persevere when:** Metrics moving right direction, feedback positive and specific, hypothesis validated, learning velocity high, clear path to improvement.',
    '',
    '**Pivot when:** Metrics not moving, feedback negative or indifferent, hypothesis invalidated, better opportunity emerged, market changed.',
    '',
    '**Types of pivots:** Zoom-in (feature becomes product), Zoom-out (product becomes feature), Customer segment, Customer need, Platform, Business architecture, Value capture, Engine of growth, Channel, Technology.',
    '',
    '### 16.7 MVP Communication',
    '',
    '**Managing expectations:** Explain what MVP means and does not mean. Set expectations about quality and scope. Emphasize learning over shipping. Define success criteria before building.',
    '',
    '**Stakeholder responses:**',
    '- "This is too minimal" -> "The goal is to learn quickly. We will add based on evidence."',
    '- "This looks unpolished" -> "Polishing before validation is waste."',
    '- "What about edge cases?" -> "Edge cases come after validation."',
    '- "When will it be done?" -> "We ship when we can test the hypothesis."',
  ];
  lines.forEach(l => w(l));
}

// P17 - Product Analytics
function generateP17(w) {
  const lines = [
    '### 17.1 What Is Product Analytics',
    '',
    'Product analytics is the practice of collecting, analyzing, and acting on data about how users interact with your product.',
    '',
    '**Questions it answers:** What are users doing? What features do they use most? Where do they get stuck? What predicts retention? How do changes affect behavior?',
    '',
    '**Vs. other analytics:** Business analytics (revenue, profit), Marketing analytics (campaigns, channels), Product analytics (user behavior, engagement, retention).',
    '',
    '### 17.2 Event Tracking Architecture',
    '',
    '**Event types:** Page/view events, Interaction events, Business events, System events, State events.',
    '',
    '**Naming conventions:** [Entity].[Action] - user.signup, document.created. Consistent verb tense (past). Consistent casing. Hierarchical naming.',
    '',
    '**Properties schema:** Common (user_id, session_id, timestamp, app_version, platform), Entity properties, Action properties, Context properties.',
    '',
    '### 17.3 Funnel Analysis',
    '',
    'Tracks users through a sequence of steps to identify drop-off points.',
    '',
    '**Building a funnel:** Define steps (3-10 minimum), order them sequentially, track completion, calculate conversion between steps, identify largest drop-off.',
    '',
    '**Metrics per step:** Users entered, users proceeded, step conversion rate, overall conversion rate, time between steps.',
    '',
    '**Engineering:** Instrument each step, alert on significant drops, A/B test improvements to high-drop-off steps, track trends over time.',
    '',
    '### 17.4 Segmentation Analysis',
    '',
    'Breaks down metrics by user characteristics: Demographic, Behavioral, Acquisition, Plan, Cohort.',
    '',
    '**Why it matters:** Averages hide important differences. What works for one segment may not work for another.',
    '',
    '**Engineering:** Tag users at signup, track behavioral attributes over time, build segment-aware dashboards, support segment-specific experiments.',
    '',
    '### 17.5 Retention Analysis',
    '',
    '**Metrics:** Classic retention (% returning in period N), Rolling retention (% returning after day N), Unbounded retention (% who ever return), Return rate (% active in one period who return next).',
    '',
    '**Curves:** Flat = sticky (good), Decaying = losing interest (warning), Inverted = increase then crash (bad sign).',
    '',
    '**Actionable:** Segment retention by activation path, by feature adoption, before/after changes, monitor in real-time.',
    '',
    '### 17.6 Data Modeling for Product Analytics',
    '',
    '**Fact tables (events):** user_id, session_id, timestamp, event_name, event_properties, context.',
    '',
    '**Dimension tables:** Users (signup date, plan, demographics), Sessions (start, end, pages), Experiments (name, variant).',
    '',
    '**Aggregate tables:** DAU by segment, weekly retention by cohort, feature adoption rates.',
    '',
    '**Best practices:** Keep raw data accessible, pre-aggregate for performance, document the model, version the schema, test data quality.',
    '',
    '### 17.7 Instrumentation Quality',
    '',
    '**Dimensions:** Completeness (all events tracked?), Accuracy (correct values?), Consistency (across platforms?), Timeliness (available when needed?), Uniqueness (no duplicates?).',
    '',
    '**Monitoring:** Event volume alerts, null property rate, invalid values, latency monitoring, schema validation.',
    '',
    '**Testing:** Unit tests for event firing, integration tests for pipeline, staging validation, production dashboards, regular audits.',
    '',
    '### 17.8 Privacy and Compliance',
    '',
    '**Key considerations:** Consent (GDPR, CCPA), Opt-out capability, Data minimization, Anonymization of PII, Data retention policies, Access control, Data deletion workflows.',
    '',
    '**Engineering:** Consent management platform, server-side PII anonymization, configurable tracking respecting opt-out, data deletion workflows, audit logging, regular privacy impact assessments.',
  ];
  lines.forEach(l => w(l));
}

// P18 - Incident Impact
function generateP18(w) {
  const lines = [
    '### 18.1 Incidents Are Product Events',
    '',
    'Incidents (outages, performance degradation, data loss) are not just technical problems - they are product events that directly affect user experience, trust, and revenue.',
    '',
    '**Incident phases:** Detection, Response, Resolution, Recovery, Review.',
    '',
    '### 18.2 Customer Communication During Incidents',
    '',
    'Customers need to know:',
    '1. **What happened** - in plain language, not technical jargon',
    '2. **Impact** - who is affected and how',
    '3. **What we are doing** - actions being taken',
    '4. **When to expect resolution** - timeline (with uncertainty range)',
    '5. **Where to get updates** - status page, communication channel',
    '',
    '**Communication frequency:**',
    '- Critical incidents: Every 30-60 minutes',
    '- Major incidents: Every 2-4 hours',
    '- Minor incidents: At resolution',
    '',
    '### 18.3 SLA Impact and Management',
    '',
    '**SLA (Service Level Agreement)** defines the promised level of service and consequences for failing to meet it.',
    '',
    '**SLA metrics:** Uptime percentage (99.9%, 99.99%), Response time, Resolution time, Support response time.',
    '',
    '**When an SLA is breached:**',
    '1. Acknowledge the breach',
    '2. Calculate SLA credits or compensation',
    '3. Communicate with affected customers',
    '4. Include the breach in the incident report',
    '5. Implement preventive measures',
    '',
    '**Engineering responsibility:**',
    '- Monitor SLA metrics in real-time',
    '- Alert when approaching SLA thresholds',
    '- Build redundancy to meet SLA targets',
    '- Track SLA performance trends',
    '',
    '### 18.4 Incident Impact Assessment',
    '',
    '**Immediate impact:**',
    '- Users affected: count and segments',
    '- Downtime duration',
    '- Functionality degraded or unavailable',
    '- Data loss (if any)',
    '',
    '**Business impact:**',
    '- Revenue loss during downtime',
    '- Customer churn from dissatisfaction',
    '- Brand reputation damage',
    '- SLA penalty costs',
    '- Engineering time for resolution and recovery',
    '',
    '**Engineering metric impact:**',
    '- Deployment frequency may decrease (post-incident caution)',
    '- Change failure rate increases',
    '- Time to restore (MTTR) measured',
    '- Team morale and burnout risk',
    '',
    '### 18.5 Post-Incident Review Culture',
    '',
    '**Blameless post-mortems:**',
    '- Focus on systems and processes, not individuals',
    '- Ask "what allowed this to happen?" not "who did this?"',
    '- Identify contributing factors at multiple levels',
    '- Generate action items for prevention',
    '- Share learnings across the organization',
    '',
    '**Post-mortem template:**',
    '## Post-Incident Review: [Title]',
    '**Date:** [Date] **Duration:** [Duration] **Severity:** [SEV1/SEV2]',
    '**Summary:** [One-paragraph description]',
    '**Timeline:**',
    '- [Time] Detection: [How detected]',
    '- [Time] Response: [Actions taken]',
    '- [Time] Resolution: [How resolved]',
    '**Root cause:** [Technical and process factors]',
    '**Impact:** [Users affected, downtime, revenue, data]',
    '**Action items:**',
    '| Action | Owner | Due Date |',
    '|---|---|---|',
    '| [Action] | [Owner] | [Date] |',
    '',
    '### 18.6 Customer Compensation and Trust Restoration',
    '',
    '**Compensation options:**',
    '- Service credits (for SLA breaches)',
    '- Extended trial periods',
    '- Personalized apology from leadership',
    '- Early access to new features',
    '- Direct communication from engineering team',
    '',
    '**Trust restoration process:**',
    '1. Acknowledge the incident publicly and promptly',
    '2. Communicate transparently throughout',
    '3. Share detailed root cause analysis',
    '4. Share concrete prevention plan',
    '5. Follow up after prevention measures are implemented',
    '6. Monitor customer sentiment post-incident',
    '',
    '### 18.7 Engineering Response to Incidents',
    '',
    '**During the incident:**',
    '- Focus on mitigation, not root cause analysis',
    '- Communicate status to stakeholders regularly',
    '- Document actions in real-time',
    '- Escalate when needed',
    '- Do not deploy non-incident changes',
    '',
    '**After the incident:**',
    '- Participate in blameless post-mortem',
    '- Implement preventive measures',
    '- Improve monitoring and alerting',
    '- Update runbooks and documentation',
    '- Conduct incident drills based on learnings',
  ];
  lines.forEach(l => w(l));
}

// P19 - Platform Product Management
function generateP19(w) {
  const lines = [
    '### 19.1 Internal Product Thinking for Platforms',
    '',
    'Platform product management applies product thinking to internal platforms, treating developers and internal teams as customers. The product engineer building platforms thinks in terms of user needs, adoption metrics, and value delivery - just like building an external product.',
    '',
    '**Key differences from external products:**',
    '- Customers are internal (developers, teams)',
    '- Success is measured by adoption and efficiency, not revenue',
    '- Features are APIs, SDKs, tools, and infrastructure',
    '- Competitive pressure is reduced (but internal alternatives exist)',
    '- Value is indirect (enables faster feature delivery)',
    '',
    '### 19.2 Developer as Customer',
    '',
    'Treating developers as customers means understanding their needs, pain points, and workflows:',
    '',
    '**Developer customer segments:**',
    '- Frontend engineers (need clean APIs, good docs)',
    '- Backend engineers (need reliable services, clear contracts)',
    '- Data engineers (need data access, pipelines)',
    '- ML engineers (need compute, model serving)',
    '- QA engineers (need test environments, test data)',
    '- SRE/DevOps (need observability, deployment tooling)',
    '',
    '**Developer needs:**',
    '- Reliable, well-documented interfaces',
    '- Self-service capabilities (no ticket/triage required)',
    '- Fast feedback loops (CI/CD, local development)',
    '- Clear ownership and support paths',
    '- Minimal breaking changes',
    '- Production-grade reliability',
    '',
    '### 19.3 Platform Adoption Metrics',
    '',
    '**Adoption metrics:**',
    '- Number of teams using the platform',
    '- Number of services/applications on the platform',
    '- API call volume and growth',
    '- Feature adoption rate (what platform features are used)',
    '- Time to first successful call (developer onboarding)',
    '',
    '**Satisfaction metrics:**',
    '- Developer NPS (would you recommend this platform?)',
    '- Platform satisfaction survey scores',
    '- Support ticket volume and resolution time',
    '- Feature request volume',
    '',
    '**Efficiency metrics:**',
    '- Time to build and deploy a new service',
    '- Development velocity on the platform vs. alternatives',
    '- Platform-related incident frequency',
    '- Platform team throughput',
    '',
    '### 19.4 Platform Feature Requests and Prioritization',
    '',
    'Platform teams receive feature requests from internal teams, requiring prioritization:',
    '',
    '**Sources of requests:**',
    '- Direct requests from teams using the platform',
    '- Pain points observed in developer workflows',
    '- Architecture requirements from product roadmap',
    '- Technology upgrades and deprecations',
    '- Security and compliance requirements',
    '',
    '**Prioritization framework for platform features:**',
    '1. **Impact:** How many teams/developers benefit?',
    '2. **Urgency:** Is there a blocking dependency?',
    '3. **Effort:** How complex is the implementation?',
    '4. **Strategic value:** Does this enable future capabilities?',
    '5. **Maintenance cost:** What is the ongoing cost of not building this?',
    '',
    '**Say no to platform requests by:**',
    '- Explaining the trade-off transparently',
    '- Offering alternatives or workarounds',
    '- Deferring with a clear timeline or condition',
    '- Sharing the roadmap so requesters understand priorities',
    '',
    '### 19.5 Platform Roadmap Communication',
    '',
    '**Platform roadmap should include:**',
    '- Platform vision and strategy',
    '- Current capabilities and limitations',
    '- Upcoming features and improvements',
    '- Deprecations and migrations',
    '- How to give feedback and request features',
    '',
    '**Communication channels:**',
    '- Developer portal or internal website',
    '- Regular office hours or AMA sessions',
    '- Quarterly platform updates',
    '- Release notes and changelogs',
    '- Direct communication for breaking changes',
    '',
    '### 19.6 Platform Reliability and SLAs',
    '',
    'Internal platforms need reliability commitments too:',
    '',
    '**Platform SLA considerations:**',
    '- What uptime is promised? (99.9% for core platform services)',
    '- What is the incident response time?',
    '- How are outages communicated?',
    '- What is the support model?',
    '',
    '**Internal SLA vs. external SLA:**',
    '- Internal SLAs may have softer consequences',
    '- But internal platform outages affect customer-facing products',
    '- Treat internal reliability with equal seriousness',
    '',
    '### 19.7 Treating Internal Tools as Products',
    '',
    'Internal tools (deployment pipelines, monitoring dashboards, development environments) benefit from product thinking:',
    '',
    '**Product principles for internal tools:**',
    '- Understand user workflows (how do developers actually work?)',
    '- Reduce friction (automate common tasks, improve UX)',
    '- Measure adoption and satisfaction',
    '- Iterate based on feedback',
    '- Document and provide self-service',
    '',
    '**Common internal tool anti-patterns:**',
    '- Building for "the average developer" without understanding segments',
    '- Neglecting documentation and onboarding',
    '- Treating tools as "done" rather than continuously improving',
    '- Ignoring feedback from tool users',
    '- Over-engineering before understanding real needs',
    '',
    '### 19.8 Platform vs. Application Code Balance',
    '',
    'Platform teams must balance:',
    '',
    '**Platform work:** Building reusable capabilities (auth, search, messaging, data pipeline)',
    '',
    '**Application work:** Building user-facing features using the platform',
    '',
    '**Balance principles:**',
    '- 70% platform work (core capabilities)',
    '- 20% application work (scratching own itch, understanding problems)',
    '- 10% exploration (new technologies, proof-of-concepts)',
    '',
    '**When platform teams build too much application code:**',
    '- Platform quality suffers',
    '- Platform features are delayed',
    '- Team loses focus on platform vision',
    '- Application teams do not learn to use the platform',
    '',
    '**When platform teams do not build enough application code:**',
    '- Lose touch with developer needs',
    '- Build abstractions that do not solve real problems',
    '- Create platforms developers do not want to use',
    '- Miss opportunities for improvement',
  ];
  lines.forEach(l => w(l));
}

// P20 - Worked Examples
function generateP20(w) {
  const lines = [
    '### 20.1 Example: Feature Prioritization with RICE',
    '',
    '**Context:** A product team has four potential features for the next quarter. They need to prioritize which to build first.',
    '',
    '| Feature | Reach (users/month) | Impact | Confidence | Effort (weeks) | RICE Score |',
    '|---|---|---|---|---|---|',
    '| Search improvements | 10,000 | 3 (massive) | 100% | 4 | 10,000 x 3 x 1.0 / 4 = 7,500 |',
    '| Dark mode | 5,000 | 1 (low) | 80% | 2 | 5,000 x 1 x 0.8 / 2 = 2,000 |',
    '| Export to PDF | 2,000 | 2 (medium) | 50% | 3 | 2,000 x 2 x 0.5 / 3 = 667 |',
    '| API integration | 500 | 3 (massive) | 30% | 6 | 500 x 3 x 0.3 / 6 = 75 |',
    '',
    '**Result:** Search improvements (7,500) is the clear winner, followed by Dark mode (2,000).',
    '',
    '**Engineering considerations:**',
    '- Search improvements has high engineering confidence because we have analytics data proving usage',
    '- API integration has low confidence because we have not validated demand with partners',
    '- Dark mode is low effort and gives quick wins for the team',
    '',
    '### 20.2 Example: Build vs. Buy for Authentication',
    '',
    '**Context:** A startup building a B2B SaaS product needs user authentication.',
    '',
    '**Build option:** Custom auth system with PostgreSQL, JWT, bcrypt, session management.',
    '- Effort: 6 weeks engineering time ($60,000)',
    '- Ongoing: 1 week/month maintenance ($10,000/year)',
    '- Compliance: Must build SOC2-compliant auth (additional 4 weeks)',
    '- Risk: Security vulnerabilities, password policy, rate limiting',
    '',
    '**Buy option:** Auth0 (or similar)',
    '- Cost: $2,000/month for 10,000 users ($24,000/year)',
    '- Integration: 2 weeks engineering time ($20,000)',
    '- Compliance: SOC2 compliant out of the box',
    '- Risk: Vendor lock-in, pricing changes',
    '',
    '**TCO comparison (3 years):**',
    '- Build: $60,000 + ($10,000 x 3) = $90,000',
    '- Buy: $20,000 + ($24,000 x 3) = $92,000',
    '',
    '**Decision:** Buy. The costs are similar, but buy provides SOC2 compliance, faster time-to-market, and frees engineering to focus on core product features.',
    '',
    '### 20.3 Example: Technical Debt Business Case',
    '',
    '**Context:** The payment processing module has known architectural issues. Three payment features were delayed in the last quarter.',
    '',
    '**Current state:** Payment code is a monolith with tight coupling between logic, database, and third-party API calls.',
    '',
    '**Cost of debt:**',
    '- Each payment feature takes 50% longer than estimated',
    '- Average payment feature takes 6 weeks instead of 4',
    '- Payment-related bugs: 5 per month (compared to 2 for other modules)',
    '- One payment incident per quarter requiring hotfix',
    '',
    '**Proposed fix:** Refactor into three layers (API gateway, payment logic, provider abstraction) with comprehensive tests.',
    '',
    '**Investment:** 6 weeks for 2 engineers ($60,000)',
    '',
    '**Expected benefits:**',
    '- Payment features ship at estimated velocity (recapture 2 weeks per feature)',
    '- Payment bugs reduce to 2 per month',
    '- Payment incidents reduce to 1 per year',
    '',
    '**ROI:** Annual savings of ~$80,000 in engineering time vs. $60,000 investment. Payback period: 9 months.',
    '',
    '**Decision:** Go. The case is compelling, and the team clears 4 payment features in the upcoming roadmap.',
    '',
    '### 20.4 Example: Customer Interview Synthesis',
    '',
    '**Context:** A team is exploring a "team collaboration" feature for their project management tool.',
    '',
    '**Interviews conducted:** 8 interviews with project managers and team leads.',
    '',
    '**Key findings:**',
    '- 6/8 mentioned "status updates" as a pain point - they use Slack/email for updates',
    '- 5/8 said they would like automatic status summaries',
    '- 3/8 mentioned wanting to see who is working on what in real-time',
    '- 2/8 mentioned they still use spreadsheets for resource planning',
    '',
    '**Insights:**',
    '- The core problem is visibility, not collaboration',
    '- Users want automatic status aggregation, not another chat tool',
    '- Resource planning is a secondary need for power users',
    '',
    '**Recommendation:** Start with automatic status summaries based on task progress. Defer real-time presence and resource planning.',
    '',
    '### 20.5 Example: A/B Test Design',
    '',
    '**Context:** A SaaS product wants to test a new onboarding flow to improve activation.',
    '',
    '**Hypothesis:** "We believe that a guided onboarding wizard (vs. current blank canvas) for new users will increase activation rate (user creates first project within 7 days) by at least 15%."',
    '',
    '**Experiment design:**',
    '- Primary metric: Activation rate (project created within 7 days)',
    '- Secondary metrics: Time to first project, feature adoption at day 30',
    '- Guardrail metrics: Support ticket volume, page load time',
    '- Randomization unit: User',
    '- Sample size: 2,500 users per variant (baseline activation 20%, MDE 15%, power 80%, significance 95%)',
    '- Duration: 3 weeks (account for day-of-week and novelty effects)',
    '',
    '**Implementation:** Feature flag for wizard vs. current onboarding, track all onboarding events, monitor data quality.',
    '',
    '### 20.6 Example: Architecture Decision for Real-time Features',
    '',
    '**Context:** A team is adding real-time collaboration to a document editor.',
    '',
    '**Options:**',
    '1. **WebSockets:** Bidirectional, full control, requires custom infrastructure',
    '2. **Server-Sent Events:** One-way updates, simpler, but cannot handle client sends',
    '3. **Third-party service (Pusher, Ably):** Fastest to implement, ongoing cost, vendor dependency',
    '',
    '**Product considerations:**',
    '- Users expect sub-second sync',
    '- Need to show who is online and typing',
    '- Offline editing with sync is a future requirement',
    '',
    '**Decision:** WebSockets with CRDT-based conflict resolution.',
    '',
    '**Rationale:**',
    '- Offline sync requires CRDTs regardless of transport',
    '- WebSockets give full control for future features (cursor positions, chat)',
    '- Building in-house avoids vendor lock-in for a core feature',
    '',
    '**Trade-off:** 4 weeks to implement vs. 1 week with third-party service.',
    '',
    '### 20.7 Example: Product Metrics Tree',
    '',
    '**Context:** A note-taking app with North Star Metric: "Weekly active notes edited."',
    '',
    '**Metrics tree breakdown:**',
    '- New users editing notes',
    '  - Sign-up completion rate',
    '  - First note created rate',
    '  - First note edited within 24 hours',
    '- Existing users editing notes',
    '  - DAU rate',
    '  - Notes edited per session',
    '  - Note revisit rate (returning to edit existing notes)',
    '- Returning users editing notes',
    '  - D7 retention',
    '  - D30 retention',
    '  - Churn rate',
    '',
    '**Engineering implications:**',
    '- Instrument each level of the tree',
    '- Identify which team owns each sub-metric',
    '- Prioritize features that move the highest-leverage sub-metric',
    '',
    '### 20.8 Example: Experimentation Culture Implementation',
    '',
    '**Context:** A company wants to build an experimentation culture in a team of 20 engineers.',
    '',
    '**Phase 1 - Foundation (Month 1-2):**',
    '- Implement feature flag system (2 weeks)',
    '- Set up experiment framework and dashboard (3 weeks)',
    '- Train all engineers on experiment design (1 workshop)',
    '- Run first team experiment (simple button color test)',
    '',
    '**Phase 2 - Adoption (Month 3-4):**',
    '- Require experiment for any user-facing change',
    '- Weekly experiment reviews in team meetings',
    '- Celebrate failed experiments for learnings',
    '- Add experimentation to engineering onboarding',
    '',
    '**Phase 3 - Culture (Month 5-6):**',
    '- Teams autonomously designing and running experiments',
    '- Experiment backlog maintained by product',
    '- Quarterly experimentation retrospectives',
    '- Statistical training for advanced experiment design',
    '',
    '**Metrics tracked:**',
    '- Number of experiments run (target: 4 per team per quarter)',
    '- Percentage of features tested (target: >80%)',
    '- Experiment completion rate (target: >90% complete, not stopped early)',
    '- Team confidence in experiment design (survey)',
    '',
    '### 20.9 Example: Platform Adoption Strategy',
    '',
    '**Context:** A platform team built an internal service mesh but adoption is low.',
    '',
    '**Problem analysis:**',
    '- Only 2 of 10 teams using the mesh after 6 months',
    '- Documentation exists but is hard to find',
    '- No migration tooling - teams must manually adapt',
    '- Support response time is 2+ days',
    '',
    '**Changes made:**',
    '1. **Reduce friction:** Build migration scripts that auto-configure services',
    '2. **Improve onboarding:** Create interactive tutorial with sample service',
    '3. **Support commitment:** Guarantee 4-hour response time for platform issues',
    '4. **Demonstrate value:** Publish case studies of early adopter teams (showing 40% reduction in deployment time)',
    '5. **Internal marketing:** Present at all-hands, write internal blog posts, hold office hours',
    '',
    '**Results after 3 months:** 7 of 10 teams adopted, developer NPS improved from -20 to +40.',
    '',
    '### 20.10 Example: Incident Impact Assessment',
    '',
    '**Context:** A 45-minute outage of the payment system during peak hours (2-3 PM).',
    '',
    '**Impact assessment:**',
    '- Users affected: Approximately 5,000 users attempting checkout',
    '- Failed transactions: ~800 failed payment attempts',
    '- Revenue loss: ~$40,000 in missed transactions',
    '- Customer support: 120 support tickets created during outage',
    '- SLA breach: 99.9% monthly uptime breached (need to pay credits)',
    '',
    '**Compensation:**',
    '- SLA credits: 10% monthly credit for affected enterprise customers ($5,000)',
    '- Affected users: Personalized email with apology + $10 credit',
    '- Follow-up: Detailed root cause analysis shared publicly',
    '',
    '**Prevention:**',
    '- Add redundant payment provider',
    '- Improve monitoring for payment gateway latency',
    '- Add automatic failover mechanism',
    '- Run monthly payment system chaos engineering drills',
    '',
    '### 20.11 Example: Technical Requirements Validation',
    '',
    '**Context:** Building a file upload feature for a SaaS product.',
    '',
    '**Product requirement:** "Users should be able to upload files up to 100MB."',
    '',
    '**Technical requirements derived:**',
    '1. The system shall accept file uploads via multipart/form-data POST requests',
    '2. The system shall validate file size client-side (100MB) and server-side (100MB)',
    '3. The system shall scan uploaded files for malware',
    '4. The system shall store files in S3 with server-side encryption',
    '5. The system shall generate a signed URL for download that expires in 1 hour',
    '',
    '**Validation with stakeholders:**',
    '- PM confirms 100MB covers 95% of use cases',
    '- Security confirms malware scanning requirement',
    '- Legal confirms encryption requirement for compliance',
    '- UX confirms 1-hour expiration is acceptable (users download immediately)',
    '',
    '**Verification:**',
    '- Integration test: Upload file and confirm stored in S3',
    '- Load test: 100 concurrent 100MB uploads',
    '- Security test: Attempt upload of executable file (should be rejected)',
    '',
    '### 20.12 Example: Cost of Delay Calculation',
    '',
    '**Context:** A team is deciding between Feature A (automated reporting) and Feature B (API integration).',
    '',
    '**Feature A - Automated Reporting:**',
    '- Revenue impact: Enables premium tier upgrade for 200 existing customers at $50/month = $10,000/month',
    '- Cost savings: Saves 40 hours/week of manual report generation = $4,000/month',
    '- Delay cost: $14,000/month',
    '- Effort: 4 weeks',
    '- Cost of Delay: $3,500/week',
    '',
    '**Feature B - API Integration:**',
    '- Revenue impact: Enables partnership with 5 integration partners, estimated $5,000/month',
    '- Cost savings: None directly',
    '- Delay cost: $5,000/month + partnership risk (partners may lose interest)',
    '- Effort: 6 weeks',
    '- Cost of Delay: $833/week (escalating to $2,000/week after 3 months due to partnership risk)',
    '',
    '**WSJF analysis:**',
    '- Feature A: $3,500/week / 4 weeks = 875',
    '- Feature B: $833/week / 6 weeks = 139',
    '',
    '**Decision:** Feature A first (WSJF 875 vs 139). The reporting feature delivers immediate revenue and cost savings.',
  ];
  lines.forEach(l => w(l));
}

module.exports = { generateP16, generateP17, generateP18, generateP19, generateP20 };
