import os

path = r"C:\Users\Victo\Downloads\synarc-v4\synarc\plugins\ml-engineer\skills\SKILL.md"
lines = []

lines.append("")
lines.append("---")
lines.append("")
lines.append("## P15: MLOps Implementation Details")
lines.append("")
lines.append("### 15.1 Terraform Infrastructure for ML Platform")
lines.append("")
lines.append("Complete Terraform module for ML training infrastructure on AWS:")
lines.append("The module defines VPC, EKS cluster with GPU/CPU node groups,")
lines.append("S3 buckets for artifacts and data lake, RDS for MLflow metadata,")
lines.append("ElastiCache Redis for feature store, EFS for shared model storage,")
lines.append("and IAM roles with proper permissions.")
lines.append("")
lines.append("Key resources:")
lines.append("- VPC with public and private subnets across 3 AZs")
lines.append("- EKS cluster with multiple node groups (CPU, GPU training, GPU serving, CPU spot)")
lines.append("- S3 buckets for ML artifacts and data lake with lifecycle policies")
lines.append("- RDS PostgreSQL for MLflow tracking server metadata")
lines.append("- ElastiCache Redis for feature store online serving")
lines.append("- EFS for shared model storage across training and serving pods")
lines.append("- IAM roles with S3, ECR, CloudWatch permissions")
lines.append("")
lines.append("### 15.2 MLflow Helm Chart Configuration")
lines.append("")
lines.append("MLflow tracking server is deployed via Helm with:")
lines.append("- PostgreSQL backend for metadata storage")
lines.append("- S3 artifact store for models, plots, configs")
lines.append("- Gunicorn workers for production traffic")
lines.append("- Persistent volume for local caching")
lines.append("- Service and Ingress for external access")
lines.append("- IAM roles for S3 access via service account")
lines.append("- Environment variables for configuration")
lines.append("")
lines.append("### 15.3 CI/CD Pipeline for ML")
lines.append("")
lines.append("A complete ML CI/CD pipeline includes these stages:")
lines.append("")
lines.append("1. Code Quality: lint, type check, format, security scan")
lines.append("2. Unit Tests: pytest with coverage thresholds above 80 percent")
lines.append("3. Data Tests: Great Expectations suite for schema validation")
lines.append("4. Integration Tests: small end-to-end pipeline with sample data")
lines.append("5. Model Training Sanity: single epoch on small data subset")
lines.append("6. Model Evaluation: metrics computation and baseline comparison")
lines.append("7. Container Build: Docker image with model artifacts")
lines.append("8. Container Push: push to container registry")
lines.append("9. Staging Deploy: Helm upgrade to staging namespace")
lines.append("10. Smoke Tests: predict on sample inputs, check latency and throughput")
lines.append("11. Approval Gate: manual or auto-approval based on risk class")
lines.append("12. Production Deploy: canary rollout with progressive delivery")
lines.append("")
lines.append("Each stage has conditional execution based on branch, file changes,")
lines.append("and previous stage results. Secrets managed via CI/CD secrets store.")
lines.append("")
lines.append("### 15.4 Model Validation Gate Runner")
lines.append("")
lines.append("Model validation gates are implemented as a Python package")
lines.append("that runs as a step in the CI/CD pipeline. The gate runner:")
lines.append("- load_config: Load gate configuration from YAML file")
lines.append("- run_gate: Execute gate checks and return structured results")
lines.append("- report_results: Format results for CI/CD pipeline output")
lines.append("- should_block: Determine if failure should block promotion")
lines.append("- get_artifacts: Return evidence artifacts for audit trail")
lines.append("")
lines.append("Gate configuration is version-controlled alongside model code.")
lines.append("Each model has its own gate configuration file specifying")
lines.append("thresholds, checks, and severity levels for each pipeline stage.")
lines.append("")
lines.append("### 15.5 Drift Monitoring Dashboard")
lines.append("")
lines.append("Grafana dashboard panels for model monitoring:")
lines.append("")
lines.append("1. Model Health Overview: prediction count, error rate, latency p50/p95/p99")
lines.append("2. Feature Drift Heatmap: per-feature drift p-value over time")
lines.append("3. Prediction Distribution: histogram of scores compared to training set")
lines.append("4. Data Quality: null ratio, row count, schema violations over time")
lines.append("5. Performance Metrics: online accuracy, precision, recall (when labels available)")
lines.append("6. Resource Utilization: CPU, memory, GPU utilization per pod")
lines.append("7. Deployment History: model version timeline with deployment annotations")
lines.append("8. Alert History: alert count by severity over time")
lines.append("")
lines.append("### 15.6 Alerting Rules")
lines.append("")
lines.append("Prometheus alerting rules for model serving:")
lines.append("- ModelPredictionDrift: prediction drift p-value < 0.01 for 3 windows")
lines.append("- ModelLatencyHigh: p99 latency > SLA threshold for 5 minutes")
lines.append("- ModelErrorRateHigh: error rate > 1 percent for 5 minutes")
lines.append("- ModelThroughputLow: throughput drops below 50 percent of baseline")
lines.append("- DataQualityFailed: data quality check fails in production")
lines.append("- ModelMemoryHigh: memory usage > 90 percent for 10 minutes")
lines.append("- ModelGPUUtilLow: GPU utilization < 20 percent during inference")
lines.append("- ModelVersionRollback: automated rollback triggered")
lines.append("- FeatureStoreLatency: feature retrieval > 50ms for 5 minutes")
lines.append("- ModelRetrainingFailed: retraining pipeline failed")
lines.append("")
lines.append("Each alert has severity, summary, description, runbook URL,")
lines.append("and notification channel mapping to Slack and PagerDuty.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## P16: LLM Application Implementation Details")
lines.append("")
lines.append("### 16.1 Complete RAG System Architecture")
lines.append("")
lines.append("A production RAG system integrates document ingestion, vector storage,")
lines.append("retrieval, generation, and guardrails into a cohesive pipeline.")
lines.append("")
lines.append("Document ingestion pipeline:")
lines.append("1. Document parsing: support for PDF, DOCX, HTML, Markdown, plain text")
lines.append("2. Document chunking: recursive character splitter with configurable overlap")
lines.append("3. Embedding generation: batch embedding with rate limiting")
lines.append("4. Vector store ingestion: upsert with deduplication by document hash")
lines.append("5. Metadata extraction: title, source, date, author, section hierarchy")
lines.append("6. Index management: delta updates, full rebuilds on schema changes")
lines.append("")
lines.append("Query processing pipeline:")
lines.append("1. Query rewriting: expand abbreviations, correct typos, add conversation context")
lines.append("2. Query classification: factual, opinion, code, analysis task types")
lines.append("3. Retrieval: hybrid search (dense embedding + BM25) with top-K candidates")
lines.append("4. Reranking: cross-encoder model to improve retrieval precision")
lines.append("5. Context assembly: format retrieved chunks with source attribution")
lines.append("6. Prompt construction: system prompt + context + query + task instructions")
lines.append("7. LLM generation: streaming response with token usage tracking")
lines.append("8. Output validation: PII scan, toxicity check, factuality check")
lines.append("9. Response formatting: structured output with inline citations")
lines.append("")
lines.append("### 16.2 Chunking Strategy Comparison")
lines.append("")
lines.append("Chunk size affects retrieval quality, context relevance, and inference cost.")
lines.append("Optimal chunk size depends on document type and query patterns.")
lines.append("")
lines.append("Small chunks (128-256 tokens): high precision, exact matching, lower cost.")
lines.append("Best for: FAQ, code snippets, definitions, lookups.")
lines.append("")
lines.append("Medium chunks (512-1024 tokens): good balance of precision and recall.")
lines.append("Best for: general purpose, documentation, articles, blog posts.")
lines.append("")
lines.append("Large chunks (1024-2048 tokens): rich context, better for multi-fact queries.")
lines.append("Best for: long-form analysis, research papers, legal documents.")
lines.append("")
lines.append("Chunk overlap (10-20 percent): prevents information loss at chunk boundaries,")
lines.append("ensures sentences and paragraphs are complete.")
lines.append("")
lines.append("### 16.3 Embedding Model Selection Guide")
lines.append("")
lines.append("Selection criteria for embedding models:")
lines.append("")
lines.append("1. Dimension size:")
lines.append("   - 384-768 dims: fast, cheap, good for most tasks")
lines.append("   - 1024-1536 dims: better accuracy, higher cost")
lines.append("   - 3072+ dims: best accuracy, significant cost")
lines.append("")
lines.append("2. Max sequence length:")
lines.append("   - 128-256 tokens: short text, titles, queries")
lines.append("   - 512 tokens: standard documents, paragraphs")
lines.append("   - 8192+ tokens: long documents, full articles")
lines.append("")
lines.append("3. Language support: monolingual, multilingual, cross-lingual")
lines.append("")
lines.append("4. Domain specificity: general, domain-specific, fine-tuned")
lines.append("")
lines.append("5. Performance vs latency tradeoff:")
lines.append("   - Small models: 50-100ms per batch, good for real-time")
lines.append("   - Large models: 200-500ms per batch, better for batch")
lines.append("   - Distilled models: compromise between size and quality")
lines.append("")
lines.append("### 16.4 Prompt Template Management")
lines.append("")
lines.append("Production prompt management requires versioning, testing, and monitoring.")
lines.append("Prompts are stored as templates with variables and metadata.")
lines.append("")
lines.append("Prompt template structure:")
lines.append("- name: unique identifier for the prompt")
lines.append("- version: semantic version for tracking changes")
lines.append("- template: the prompt text with {{variable}} placeholders")
lines.append("- variables: expected variables with descriptions and types")
lines.append("- metadata: author, date, description, tags, performance metrics")
lines.append("- tests: expected input/output pairs for validation")
lines.append("- parent_prompt: base prompt if this is a variant")
lines.append("")
lines.append("Prompt versioning strategy:")
lines.append("- Each prompt change creates a new version in the prompt registry")
lines.append("- A/B testing between prompt versions for quality comparison")
lines.append("- Canary deployment of new prompts to subset of users")
lines.append("- Rollback to previous prompt version on metric regression")
lines.append("")
lines.append("### 16.5 Guardrail Implementation")
lines.append("")
lines.append("Input validation guardrails:")
lines.append("- PII detection: regex patterns + NER model for sensitive data")
lines.append("- Toxicity classification: BERT-based classifier for harmful content")
lines.append("- Prompt injection: classifier trained on injection attack examples")
lines.append("- Rate limiting: token bucket algorithm per user or API key")
lines.append("- Content policy: configurable rules for blocked topics and categories")
lines.append("- Language detection: ensure query is in supported languages")
lines.append("- Input length: reject queries exceeding max token limit")
lines.append("")
lines.append("Output validation guardrails:")
lines.append("- PII scanning: regex + NER on generated output before returning")
lines.append("- Toxicity filter: classifier on output, block if score above threshold")
lines.append("- Factuality check: compare output against knowledge base")
lines.append("- Format validation: ensure output matches expected JSON schema")
lines.append("- Length enforcement: truncate or reject outputs exceeding limit")
lines.append("- Repetition detection: check for repeating phrases or loops")
lines.append("- Citation verification: ensure claims have source attribution")
lines.append("")
lines.append("Each guardrail has configurable severity and action on violation.")
lines.append("Guardrail events are logged for monitoring and continuous improvement.")
lines.append("")
lines.append("### 16.6 LLM Cost Optimization")
lines.append("")
lines.append("Detailed strategies for reducing LLM inference cost:")
lines.append("")
lines.append("1. Prompt compression: remove unnecessary instructions, shorter examples,")
lines.append("   consolidate system prompts, strip whitespace.")
lines.append("")
lines.append("2. Output length control: set max_tokens minimum required, use stop sequences,")
lines.append("   request structured output, track token budget per session.")
lines.append("")
lines.append("3. Caching: semantic cache for common queries, exact cache for identical,")
lines.append("   TTL-based invalidation, monitor cache hit rate.")
lines.append("")
lines.append("4. Model tiering: simple queries use small model, complex use large,")
lines.append("   classification use fine-tuned smaller models.")
lines.append("")
lines.append("5. Retrieval optimization: rerank top-K, filter by metadata before search,")
lines.append("   use summary-level retrieval then detailed, compress context.")
lines.append("")
lines.append("6. Batching: group similar requests, use async for non-real-time tasks,")
lines.append("   implement request queuing for batch optimization.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## P17: Bias and Fairness")
lines.append("")
lines.append("### 17.1 Fairness Metrics for Classification")
lines.append("")
lines.append("Demographic Parity: equal positive prediction rate across groups.")
lines.append("P(Y_hat=1 | A=a) == P(Y_hat=1 | A=b) for all groups a, b.")
lines.append("Metric: max absolute difference in positive prediction rates.")
lines.append("Threshold: less than 0.05 for low risk, less than 0.10 for medium.")
lines.append("")
lines.append("Equal Opportunity: equal true positive rate across groups.")
lines.append("P(Y_hat=1 | Y=1, A=a) == P(Y_hat=1 | Y=1, A=b)")
lines.append("Metric: max absolute difference in TPR between groups.")
lines.append("Threshold: less than 0.05 for low risk, less than 0.10 for medium.")
lines.append("")
lines.append("Equalized Odds: equal TPR and FPR across groups.")
lines.append("TPR_a == TPR_b AND FPR_a == FPR_b for all groups.")
lines.append("Metric: max of TPR difference and FPR difference.")
lines.append("Threshold: less than 0.05 for both TPR and FPR.")
lines.append("")
lines.append("Disparate Impact: ratio of positive prediction rates.")
lines.append("P(Y_hat=1 | A=protected) / P(Y_hat=1 | A=reference)")
lines.append("Threshold: 0.8 to 1.25 for acceptable range.")
lines.append("")
lines.append("### 17.2 Bias Detection Pipeline")
lines.append("")
lines.append("The bias detection pipeline runs at multiple stages:")
lines.append("")
lines.append("1. Data stage: compute label distribution by group, check representation,")
lines.append("   detect missing data patterns, report data composition dashboard.")
lines.append("")
lines.append("2. Model stage: compute all fairness metrics on validation set, analyze")
lines.append("   intersectional groups, test statistical significance, generate report.")
lines.append("")
lines.append("3. Deployment stage: monitor fairness on production data, alert on")
lines.append("   degradation, regular fairness audits per risk classification.")
lines.append("")
lines.append("### 17.3 Bias Mitigation Techniques")
lines.append("")
lines.append("Pre-processing (data level): reweighting, resampling, data generation,")
lines.append("label correction, removal of features correlated with protected attributes.")
lines.append("")
lines.append("In-processing (model level): adversarial debiasing, equality of opportunity")
lines.append("regularization, fair representations, prejudice remover penalty.")
lines.append("")
lines.append("Post-processing (output level): threshold adjustment per group,")
lines.append("calibration by group, rejection option with confidence threshold.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## P18: ML Cost Optimization")
lines.append("")
lines.append("### 18.1 Training Cost Optimization")
lines.append("")
lines.append("Training cost is the largest ML expense. Key reduction strategies:")
lines.append("")
lines.append("1. Spot instances: 60-70 percent discount, checkpointing for resilience,")
lines.append("   spot diversity across instance types and AZs.")
lines.append("")
lines.append("2. Efficient training: mixed precision (2x speedup), gradient accumulation,")
lines.append("   gradient checkpointing, flash attention, torch.compile.")
lines.append("")
lines.append("3. Resource right-sizing: match GPU to model size, start smallest,")
lines.append("   profile memory usage, use multi-GPU only when necessary.")
lines.append("")
lines.append("4. Experiment management: early stopping (Hyperband, ASHA),")
lines.append("   tuning budget limits, shared compute pool, job prioritization.")
lines.append("")
lines.append("### 18.2 Inference Cost Optimization")
lines.append("")
lines.append("Inference cost dominates for high-traffic deployed models:")
lines.append("")
lines.append("1. Model compression: quantization (INT8 4x), pruning (50-90 percent),")
lines.append("   distillation, architecture search.")
lines.append("")
lines.append("2. Serving optimization: dynamic batching, response caching,")
lines.append("   continuous batching for LLMs, speculative decoding.")
lines.append("")
lines.append("3. Infrastructure: auto-scaling to zero, GPU sharing (Triton),")
lines.append("   spot for batch, CPU for small models, multi-region.")
lines.append("")
lines.append("4. Monitoring cycle: cost per prediction, budgets, regular review,")
lines.append("   load testing for right-sizing.")
lines.append("")
lines.append("### 18.3 GPU Pricing Reference")
lines.append("")
lines.append("Approximate GPU pricing per GPU-hour across cloud providers:")
lines.append("- T4: $0.35 on-demand, $0.11 spot")
lines.append("- L4: $0.56 on-demand, $0.17 spot")
lines.append("- A10G: $1.01 on-demand, $0.30 spot")
lines.append("- A100 40GB: $3.67 on-demand, $1.10 spot")
lines.append("- A100 80GB: $4.38 on-demand, $1.31 spot")
lines.append("- H100: $7.35 on-demand, $2.21 spot")

# Now add more content - P19 ML Testing
lines.append("")
lines.append("---")
lines.append("")
lines.append("## P19: ML Testing Framework")
lines.append("")
lines.append("### 19.1 Data Tests")
lines.append("")
lines.append("Automated data tests verify data quality at every pipeline stage:")
lines.append("")
lines.append("Schema tests:")
lines.append("- All required columns are present with correct data types")
lines.append("- No unexpected columns (schema drift detection)")
lines.append("- Column order is consistent (for positional formats)")
lines.append("- Nullable columns correctly marked")
lines.append("")
lines.append("Completeness tests:")
lines.append("- Row count within expected range (min/max bounds)")
lines.append("- No duplicate rows on primary key columns")
lines.append("- No NULL values in required columns")
lines.append("- Referential integrity with dimension tables")
lines.append("")
lines.append("Consistency tests:")
lines.append("- Date ranges are contiguous (no gaps)")
lines.append("- Sequential IDs are monotonic")
lines.append("- Categorical values match reference table")
lines.append("- Cross-column consistency (e.g., age vs birth_date)")
lines.append("")
lines.append("Timeliness tests:")
lines.append("- Data freshness within SLA (latest data available)")
lines.append("- No future dates in timestamp columns")
lines.append("- Update frequency matches expected cadence")
lines.append("- Backfill detection (data arriving out of order)")
lines.append("")
lines.append("### 19.2 Feature Tests")
lines.append("")
lines.append("Feature computation tests:")
lines.append("- Each feature computes correctly for known test cases")
lines.append("- Feature values are deterministic (same input, same output)")
lines.append("- Edge cases handled: empty input, null values, outliers")
lines.append("- Feature dtype and shape match expectations")
lines.append("")
lines.append("Feature distribution tests:")
lines.append("- Mean, std, min, max, quantiles within expected range")
lines.append("- Distribution shape matches reference (KS test, p > 0.05)")
lines.append("- No unexpected modes or spikes in distribution")
lines.append("- Correlation structure is stable (max delta < 0.1)")
lines.append("")
lines.append("Feature freshness tests:")
lines.append("- Features updated within SLA")
lines.append("- Staleness detection (feature value age > max_age)")
lines.append("- Online features match offline features (consistency check)")
lines.append("")
lines.append("### 19.3 Model Tests")
lines.append("")
lines.append("Model integrity tests:")
lines.append("- Model loads successfully from registry")
lines.append("- Model predict produces correct output shape")
lines.append("- Model is deterministic with fixed seed")
lines.append("- Model artifact size within expected range")
lines.append("")
lines.append("Model performance tests:")
lines.append("- Offline metrics meet minimum thresholds")
lines.append("- No significant regression vs baseline model")
lines.append("- Slice performance: all segments above minimum metric")
lines.append("- Calibration error within acceptable bounds")
lines.append("")
lines.append("Model robustness tests:")
lines.append("- Prediction stable under small input perturbations")
lines.append("- Handles missing features gracefully (fallback values)")
lines.append("- Handles out-of-distribution inputs")
lines.append("- Adversarial examples detected (confidence drop)")
lines.append("")
lines.append("### 19.4 Pipeline Tests")
lines.append("")
lines.append("Pipeline definition tests:")
lines.append("- DAG has no cycles (topologically sorted)")
lines.append("- All task dependencies are satisfied")
lines.append("- No orphaned tasks (unconnected nodes)")
lines.append("")
lines.append("Pipeline execution tests:")
lines.append("- Each task runs to completion within timeout")
lines.append("- Task retry behavior is correct (backoff, max retries)")
lines.append("- Error handling: task failure triggers correct downstream behavior")
lines.append("- Data passing between tasks is correct schema")
lines.append("")
lines.append("Pipeline resource tests:")
lines.append("- Resource requests are within cluster limits")
lines.append("- GPU resources requested only for GPU tasks")
lines.append("- Memory limits prevent OOM kills")
lines.append("")
lines.append("### 19.5 Integration Tests")
lines.append("")
lines.append("Full integration tests run on a small data sample:")
lines.append("- End-to-end pipeline: ingestion -> features -> training -> eval -> registry")
lines.append("- Feature store: write features, read features, PIT join")
lines.append("- Model registry: register, list, transition stages")
lines.append("- Serving: model loads, predicts, returns correct format")
lines.append("- Monitoring: metrics emitted, alerts configurable")
lines.append("- Retraining: triggered retraining produces valid model")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## P20: Expanded Worked Examples")
lines.append("")
lines.append("### Example 13: Real-Time Personalization with Feature Store")
lines.append("")
lines.append("Business: Serve personalized content recommendations in real-time.")
lines.append("Data: 50 million user events/day across web, mobile, and API.")
lines.append("Features: 200+ features from Feast feature store (Redis online store).")
lines.append("Model: Two-tower neural network with 128-dim embeddings.")
lines.append("Training: Daily incremental training with new user interactions.")
lines.append("Serving: TorchServe with ONNX Runtime, p99 latency < 20ms.")
lines.append("Monitoring: Feature freshness, embedding drift, CTR by segment.")
lines.append("Result: 22% increase in user engagement, 5x reduction in feature engineering time.")
lines.append("")
lines.append("### Example 14: LLM-Powered Code Review Assistant")
lines.append("")
lines.append("Business: Accelerate code review process with AI suggestions.")
lines.append("Data: 100k code reviews from internal repositories.")
lines.append("Architecture: RAG with code-specific chunking (function-level).")
lines.append("Retrieval: Hybrid search over code embeddings + docstrings.")
lines.append("Generation: Fine-tuned CodeLlama 13B with LoRA.")
lines.append("Guardrails: Code security scanner on generated suggestions.")
lines.append("Deployment: vLLM with continuous batching, 200ms per suggestion.")
lines.append("Result: 30% faster review cycles, 15% more bugs caught pre-merge.")
lines.append("")
lines.append("### Example 15: Multi-Task Model for Fraud and AML")
lines.append("")
lines.append("Business: Detect both fraud and money laundering in one model.")
lines.append("Architecture: Multi-task transformer with shared backbone + task-specific heads.")
lines.append("Features: 300 shared features + 50 task-specific features per task.")
lines.append("Training: Alternating task training with uncertainty weighting.")
lines.append("Evaluation: Separate metrics per task, no regression on either.")
lines.append("Deployment: Single model server, dual outputs, shared monitoring.")
lines.append("Result: 40% infrastructure cost reduction vs separate models.")
lines.append("")
lines.append("### Example 16: Automated Hyperparameter Optimization Platform")
lines.append("")
lines.append("Business: Centralize hyperparameter tuning across ML team.")
lines.append("Architecture: Optuna study management with shared PostgreSQL storage.")
lines.append("Features: Parallel trials across GPU cluster, automated pruning, best trial recovery.")
lines.append("Integration: MLflow for tracking, model registry for best model storage.")
lines.append("Scale: 1000+ concurrent trials, 100+ studies active simultaneously.")
lines.append("Result: 3x improvement in tuning velocity, 15% average AUC improvement.")
lines.append("")
lines.append("### Example 17: Drift Monitoring at Scale")
lines.append("")
lines.append("Business: Monitor 100+ models for data and concept drift.")
lines.append("Architecture: Centralized monitoring service with WhyLabs + custom dashboards.")
lines.append("Features: Automated drift detection, root cause analysis, retraining automation.")
lines.append("Scale: 10M+ predictions/day across multiple model types.")
lines.append("Integration: PagerDuty alerts, Slack notifications, automated Jira tickets.")
lines.append("Result: MTTR reduced from 4 hours to 15 minutes, 50% fewer degradation incidents.")
lines.append("")
lines.append("### Example 18: ML Platform Cost Optimization")
lines.append("")
lines.append("Business: Reduce ML platform costs by 40% while maintaining performance.")
lines.append("Strategies:")
lines.append("- Spot instances: 65% of training migrated to spot (60% savings)")
lines.append("- Model quantization: INT8 for all serving (4x throughput, 75% cost reduction)")
lines.append("- Auto-scaling: Scale to zero during non-business hours")
lines.append("- GPU right-sizing: Match GPU type to workload (A10G instead of A100 for small models)")
lines.append("- Storage lifecycle: Auto-tiering from Standard to Glacier for old artifacts")
lines.append("Result: 52% cost reduction, no degradation in model quality or latency SLA.")

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(lines))
    f.write("\n")

print("Content appended successfully")
