module.exports = {
  generateS13(w) {
    w('## S13 — QUALITY GATES');
    w('');
    w('Quality gates are mandatory checks that run on every interaction. Gates are organized in three tiers: Zero-Tolerance (always enforced), Standard Mandatory (enforced per WorkType), and Scale-Dependent (enforced based on project scale). No gate can be bypassed by user instruction.');
    w('');
    w('### Zero-Tolerance Gates (Always, Every Interaction)');
    w('');
    w('| Gate | Check | Violation Response |');
    w('|------|-------|-------------------|');
    w('| No execution before classification | Has S1+S2 run? | Block execution until classified |');
    w('| No invented context | Brain files contain only verified info | Remove unverified info, flag as speculative |');
    w('| No missing tests on fixes | Does a FIX include a test? | Flag missing test, suggest test type |');
    w('| No unabsorbed unplanned scope | Has UNPLANNED been surfaced? | Surface unplanned before continuing |');
    w('| No secrets in output | Check for credential patterns | Block output, request sanitization |');
    w('| No placeholder content | Is there "TODO" or "FIXME" in output? | Complete or flag for tracking |');
    w('| No hallucinated APIs | Does the API exist in the codebase? | Remove hallucinated reference |');
    w('| No fabricated imports | Are all imports resolvable? | Remove unresolvable imports |');
    w('| No broken markdown | Is output valid markdown? | Fix malformed markdown |');
    w('| No incomplete sentences | Is every sentence complete? | Complete truncated sentences |');
    w('');
    w('### Standard Mandatory Gates (Per WorkType)');
    w('');
    w('| WorkType | Required Gates |');
    w('|----------|----------------|');
    w('| FEATURE | Unit tests, type check, lint, contract check, snapshot if new contract |');
    w('| FIX | Test for fixed behavior, regression test, type check |');
    w('| REFACTOR | Same tests pass before/after, no new warnings, type check |');
    w('| SCHEMA | Migration rollback plan, data integrity validation, dry-run |');
    w('| CONTRACT | Contract tests, consumer verification, version compatibility |');
    w('| CONFIG | Dry-run validation, rollback plan, env var audit |');
    w('| INFRA | Plan review, state lock check, rollback verification |');
    w('| INCIDENT | Root cause analysis, monitoring gap review, postmortem |');
    w('| EXPERIMENT | Expiry date, cleanup plan, scope documentation |');
    w('| DOCS | Technical accuracy review, link validation |');
    w('| PLAN | Stakeholder review, ADR format, decision log |');
    w('');
    w('### Scale-Dependent Gates');
    w('');
    w('| Gate | NANO | MICRO | SMALL | MEDIUM | LARGE | ENTERPRISE |');
    w('|------|------|-------|-------|--------|-------|------------|');
    w('| Type check | Optional | Optional | Required | Required | Required | Required |');
    w('| Lint | Optional | Optional | Required | Required | Required | Required |');
    w('| Unit tests | Optional | Required | Required | Required | Required | Required |');
    w('| Integration tests | Skip | Skip | Optional | Required | Required | Required |');
    w('| Contract tests | Skip | Skip | Optional | Required | Required | Required |');
    w('| Security scan | Skip | Skip | Optional | Required | Required | Required |');
    w('| Performance test | Skip | Skip | Skip | Optional | Required | Required |');
    w('| Accessibility check | Skip | Skip | Optional | Required | Required | Required |');
    w('| E2E tests | Skip | Skip | Skip | Optional | Required | Required |');
    w('| Compliance audit | Skip | Skip | Skip | Skip | Optional | Required |');
    w('');
    w('### Quality Gate Failure Response');
    w('');
    w('When a quality gate fails:');
    w('1. State which gate failed and what the failure is');
    w('2. Provide the specific failure detail (line number, expected vs actual)');
    w('3. Suggest the fix approach');
    w('4. Do not proceed until the gate passes — gates are blocking');
    w('5. If the gate cannot pass (e.g., missing test infrastructure), flag as infrastructure gap');
    w('');
    w('Gate failures are tracked in the session ledger. Two or more gate failures on the same module flag the module as fragile. Three or more failures in the same session trigger a quality intervention checkpoint.');
    w('');
    w('Load references/testing-strategy.md for the complete quality gate specifications, per-language gate implementations, CI/CD integration patterns, and gate failure escalation procedures.');
    w('');
  }
};
