module.exports = {
  generateS15(w) {
    w('## S15 — TESTING STRATEGY');
    w('');
    w('Testing strategy defines what tests are required based on WorkType, risk level, scale, and module criticality. Tests are not optional — they are engineering deliverables. Every code change must include or update tests unless the change is ANALYSIS or zero-risk DOCS.');
    w('');
    w('### Risk-Based Test Requirements');
    w('');
    w('| Risk Level | Test Requirement | Minimum Test Type |');
    w('|-----------|-----------------|-------------------|');
    w('| INFO | No tests needed | — |');
    w('| LOW | Manual verification | Smoke test |');
    w('| MEDIUM | Unit tests for changed code | Unit |');
    w('| HIGH | Unit + integration + regression | Unit + Integration |');
    w('| CRITICAL | Full test suite + contract + perf | All types |');
    w('| BLOCKING | Full test suite + audit + compliance | All + external audit |');
    w('');
    w('### Test Type Selection by Change Type');
    w('');
    w('| Change Type | Primary Test Type | Secondary | When to Add |');
    w('|-------------|-------------------|-----------|-------------|');
    w('| New feature logic | Unit | Integration | In same PR |');
    w('| New API endpoint | Integration | Contract | In same PR |');
    w('| Bug fix | Unit (reproduce bug) | Regression | In same PR |');
    w('| Refactor | No new tests (existing must pass) | — | — |');
    w('| Schema change | Migration test | Integration | In same PR |');
    w('| Config change | Smoke test | — | Verify in deploy |');
    w('| Performance fix | Benchmark | Load test | In same PR |');
    w('| Security fix | Security unit test | Penetration | In same PR |');
    w('');
    w('### Test Coverage Guidelines');
    w('');
    w('- Core domain logic: 90%+ coverage target');
    w('- API handlers: 80%+ coverage target (integration level)');
    w('- Utility code: 70%+ coverage target');
    w('- Configuration: validation tests required');
    w('- Infrastructure: smoke tests + integration tests for critical paths');
    w('- Error handling: test error paths, not just happy paths');
    w('');
    w('### Test Gap Analysis');
    w('');
    w('When the user asks "what tests are missing?" or when a quality gate detects missing tests:');
    w('1. Identify all files changed this session');
    w('2. For each file, determine what test type would cover it');
    w('3. Check if target test file exists');
    w('4. If missing: recommend test type, describe what it should verify, suggest test name');
    w('5. Prioritize: high-risk modules first, then critical business logic, then utilities');
    w('');
    w('Load references/testing-strategy.md for the complete risk-based testing pyramid, per-language test framework recommendations, CI/CD integration patterns, contract testing protocols, and performance testing methodology.');
    w('');
  }
};
