module.exports = {
  generateS2(w) {
    w('## S2 — RISK FLOORS');
    w('');
    w('Risk assessment runs on every interaction before execution. Risk floors are deterministic and cannot be lowered by user instruction, context, timeline, team size, or any circumstance. These are engineering invariants — not recommendations.');
    w('');
    w('### Risk Levels');
    w('');
    w('| Level | Label | Meaning | Response | Escalation |');
    w('|-------|-------|---------|----------|------------|');
    w('| 0 | INFO | No operational impact | No action | None |');
    w('| 1 | LOW | Isolated, revertible, non-breaking | Standard workflow | None |');
    w('| 2 | MEDIUM | Noticeable impact, potentially breaking | Standard + review | Surface at checkpoint |');
    w('| 3 | HIGH | Significant impact, likely breaking | Pause + document + confirm | Stop before next write |');
    w('| 4 | CRITICAL | Production impact, data loss, security | STOP + full reassessment | Immediate notification |');
    w('| 5 | BLOCKING | Legal/compliance/contract violation | HALT all work | Legal + compliance notified |');
    w('');
    w('### Hard Risk Floors by Domain');
    w('');
    w('These floors apply before any other assessment and cannot be downgraded:');
    w('');
    w('| Domain | Min Risk | Reasoning |');
    w('|--------|----------|----------|');
    w('| Auth, SSO, session, MFA, OAuth | CRITICAL | Access breach is unrecoverable; all downstream systems compromised |');
    w('| Payment, billing, pricing, invoicing | CRITICAL | Revenue impact, financial regulation (PCI-DSS, SOX) |');
    w('| PII, PHI, personal data, GDPR data | CRITICAL | Regulatory penalties, reputation damage, legal liability |');
    w('| Secrets, credentials, API keys, tokens | CRITICAL | Exposure is irreversibly compromised; rotation cascades |');
    w('| Database schema REMOVE or RENAME | CRITICAL | Data loss or corruption; migration rollback complexity |');
    w('| Public API response shape change | HIGH | All consumers must adapt; coordination cost |');
    w('| Public symbol rename or removal | HIGH | All callers break until updated |');
    w('| Environment variable add/remove/rename | HIGH (CRITICAL rename) | Affects all deployments; rename is especially dangerous |');
    w('| Network, firewall, IAM, security group | CRITICAL | Security boundary change; blast radius is all services |');
    w('| INCIDENT response | CRITICAL | Production emergency; immediate action required |');
    w('| Data migration | HIGH (CRITICAL destructive) | Data integrity risk; destructive = CRITICAL |');
    w('| Feature behind auth/permissions | HIGH | Access control changes affect all users |');
    w('| Shared utility used by 3+ modules | HIGH | Broad blast radius; regression affects multiple systems |');
    w('| Untested module change | HIGH | No safety net; regression detection relies on manual review |');
    w('| Required env var without default | HIGH | Will crash production on deploy |');
    w('| Configuration affecting ALL tenants | HIGH | Multi-tenant impact; partial rollback is difficult |');
    w('| Certificate or TLS configuration | CRITICAL | Service availability; handshake failures = outage |');
    w('| Rate limit or throttling changes | MEDIUM | Can cause availability impact if too aggressive |');
    w('| Public DNS or routing changes | CRITICAL | Traffic misrouting = outage or interception risk |');
    w('| Encryption algorithm change | CRITICAL | Interoperability break; data may become unreadable |');
    w('| Logging or monitoring removal | HIGH | Blind spot created; incident detection delayed |');
    w('');
    w('### Escalation Rules');
    w('');
    w('Escalate ONE level when ANY condition is met:');
    w('');
    w('| Condition | Escalation | Rationale |');
    w('|-----------|------------|----------|');
    w('| Change is UNPLANNED | +1 | Scope not agreed; may introduce unexpected interactions |');
    w('| Session has 2+ HIGH entries | +1 next change | Cumulative risk increases; system is destabilizing |');
    w('| Module has no test coverage | +1 | No automated safety net; regression risk increases |');
    w('| Module flagged fragile in brain | +1 | Historical instability increases likelihood of new issues |');
    w('| Active INCIDENT in session | ALL → CRITICAL | During incident, every change carries emergency risk |');
    w('| Change in unknown/unclassified module | +1 | Cannot assess blast radius; conservative escalation |');
    w('| Blast radius = ALL_USERS | +1 | Any mistake affects every user; high-impact surface |');
    w('| Reversibility = IRREVERSIBLE | → CRITICAL | Cannot undo; must be treated with maximum caution |');
    w('| Same module has recurrence flag | +1 | Repeated issues indicate deeper problems |');
    w('| Change touches 3+ files | +1 | Coordination complexity increases error probability |');
    w('| Change touches cross-service boundary | +2 | Distributed system changes have multiplicative risk |');
    w('| Change during freeze period | +2 | Blackout period exists for a reason; extra scrutiny |');
    w('| No rollback plan defined | +1 | Cannot recover from failure; higher caution warranted |');
    w('');
    w('### Risk Composite Calculation');
    w('');
    w('Composite risk = MAX of all applicable factors:');
    w('');
    w('composite_risk = MAX(worktype_risk, domain_floor, escalation_adjusted, blast_radius_adj, data_sensitivity, urgency_risk)');
    w('');
    w('Where:');
    w('- worktype_risk = default risk from S1 for the classified WorkType');
    w('- domain_floor = hard floor from the domain table (if applicable)');
    w('- escalation_adjusted = base risk after applying escalation rules');
    w('- blast_radius_adj = base risk after blast radius multiplier');
    w('- data_sensitivity = base risk after data classification adjustment');
    w('- urgency_risk = IMMEDIATE → CRITICAL, TODAY → +1, SCHEDULED → 0, DEFERRABLE → -1');
    w('');
    w('The composite is the maximum, not the sum. Risk is bounded by CRITICAL (maximum meaningful level).');
    w('');
    w('### Blast Radius Multiplier');
    w('');
    w('| Blast Radius | Scope | Multiplier | Examples |');
    w('|--------------|-------|------------|---------|');
    w('| SINGLE_USER | 1 user, 1 session | x1 | Profile edit, personal settings |');
    w('| SINGLE_TENANT | 1 org/tenant | x2 | Org-level config change |');
    w('| SINGLE_FEATURE | 1 feature area | x1.5 | Feature-specific endpoint change |');
    w('| SINGLE_SERVICE | 1 service | x2 | Service-internal refactoring |');
    w('| MULTI_SERVICE | 2+ services | x3 | Contract/schema change |');
    w('| PLATFORM | Shared infra, global config | x4 | DNS, IAM, CI/CD, secret store |');
    w('| ALL_USERS | Entire user base | x5 | Public API, auth, billing |');
    w('| DATA_INTEGRITY | Stored data correctness | x5 | Migration, schema change |');
    w('| THIRD_PARTY | External consumers | x4 | Public API, webhook, SDK change |');
    w('');
    w('Multiply the base risk by the blast radius multiplier. Scale: INFO(0) x5 = still INFO. CRITICAL(4) x anything = CRITICAL. The multiplier is advisory for MEDIUM/LOW risks — it suggests caution level, not strict arithmetic.');
    w('');
    w('### Reversibility Adjustment');
    w('');
    w('| Reversibility | Adjustment | Description | Examples |');
    w('|---------------|-----------|-------------|----------|');
    w('| SAFE | -1 level | Easily reversible | Add optional field, add nullable column, add endpoint |');
    w('| CAREFUL | 0 | Reversible with effort | Rename with backward-compat alias, deprecate field |');
    w('| HARD | +1 level | Difficult, data loss risk | Remove non-nullable column, change existing field type |');
    w('| IRREVERSIBLE | → CRITICAL | Cannot undo | DROP TABLE, destructive migration, format change |');
    w('| UNKNOWN | +1 | Cannot assess | New technology, unfamiliar module, undocumented system |');
    w('');
    w('### Urgency Adjustment');
    w('');
    w('| Urgency | Adjustment | When Applied |');
    w('|---------|-----------|--------------|');
    w('| IMMEDIATE | → CRITICAL | Production outage, security breach, data loss |');
    w('| TODAY | +1 | Degraded performance, partial outage, approaching deadline |');
    w('| THIS_SPRINT | 0 | Normal planned work, bug fixes |');
    w('| SCHEDULED | 0 | Features, refactors with set timeline |');
    w('| DEFERRABLE | -1 | Cosmetic, nice-to-have, documentation |');
    w('| NEXT_PHASE | -1 | Future roadmap item, no current commitment |');
    w('');
    w('### Data Sensitivity Risk');
    w('');
    w('| Classification | Adjustment | Examples |');
    w('|----------------|-----------|----------|');
    w('| PUBLIC | 0 | Readme, docs, marketing site |');
    w('| INTERNAL | 0 | Internal tools, non-critical config |');
    w('| CONFIDENTIAL | +1 | Business logic, pricing algorithms, internal metrics |');
    w('| RESTRICTED | +2 | Customer data, PII, financial records, PHI |');
    w('| CRITICAL | → CRITICAL | Encryption keys, authentication secrets, payment data |');
    w('| REGULATED | → CRITICAL | GDPR data, HIPAA data, PCI data, SOX data |');
    w('');
    w('### Risk Assessment Worked Examples');
    w('');
    w('**Example 1: Add rate limit header to public API**');
    w('- Step 1: FEATURE:PLANNED → MEDIUM');
    w('- Step 2: No domain floor applies');
    w('- Step 3: Public API → ALL_USERS → HIGH (x5)');
    w('- Step 4: Additive change → SAFE → -1 → MEDIUM');
    w('- Step 5: Planned → no escalation');
    w('- Composite: MEDIUM');
    w('- Deploy: staged rollout, monitor for consumer breakage');
    w('');
    w('**Example 2: Remove deprecated field from user profile endpoint**');
    w('- Step 1: CONTRACT:RESPONSE_REMOVE → CRITICAL');
    w('- Step 2: Public API → HIGH floor');
    w('- Step 3: All API consumers → ALL_USERS → CRITICAL');
    w('- Step 4: Hard reversibility (consumers depend on field) → HARD → CRITICAL');
    w('- Step 5: If UNPLANNED → CRITICAL');
    w('- Composite: CRITICAL');
    w('- Action: STOP. Impact analysis required. Deprecation notice needed. Migration period.');
    w('');
    w('**Example 3: Fix null pointer in auth middleware logging**');
    w('- Step 1: FIX:BUG → HIGH');
    w('- Step 2: Auth domain → CRITICAL floor');
    w('- Step 3: All authenticated users → ALL_USERS → CRITICAL');
    w('- Step 4: SAFE (bug fix, no API change) → no adjustment');
    w('- Step 5: UNPLANNED (found while working on something else) → +1');
    w('- Composite: CRITICAL');
    w('- Action: STOP. Auth changes are ALWAYS CRITICAL. Even logging changes in auth.');
    w('');
    w('**Example 4: Update README with setup instructions**');
    w('- Step 1: DOCS → LOW');
    w('- Step 2: No domain floor');
    w('- Step 3: SINGLE_USER (readers of README) → x1');
    w('- Step 4: SAFE → -1 → INFO');
    w('- Step 5: PLANNED → 0');
    w('- Composite: INFO');
    w('- Action: Proceed. No tracking needed beyond ledger entry.');
    w('');
    w('**Example 5: Production database migration to add index**');
    w('- Step 1: SCHEMA:DB_INDEX → MEDIUM');
    w('- Step 2: Database changes → HIGH floor (data integrity)');
    w('- Step 3: ALL_USERS (query performance affects all) → HIGH');
    w('- Step 4: SAFE (CREATE INDEX CONCURRENTLY is additive) → -1 → MEDIUM');
    w('- Step 5: PLANNED → 0');
    w('- Composite: MEDIUM');
    w('- Deploy: Use CONCURRENTLY to avoid table lock. Monitor query performance after. Have rollback: DROP INDEX.');
    w('');
    w('**Example 6: Rename environment variable from DB_HOST to DATABASE_HOST**');
    w('- Step 1: CONFIG:ENV_RENAME → CRITICAL');
    w('- Step 2: ENV rename → CRITICAL floor');
    w('- Step 3: PLATFORM → x4 → CRITICAL');
    w('- Step 4: IRREVERSIBLE (old name stops working) → CRITICAL');
    w('- Step 5: PLANNED → 0');
    w('- Composite: CRITICAL');
    w('- Action: STOP. Dual-read migration: read both env vars, deploy new containers, remove old env var.');
    w('');
    w('### Risk Statement Format');
    w('');
    w('Every risk statement follows this pattern: "[LEVEL] module/path: one-line description"');
    w('');
    w('Examples:');
    w('- HIGH auth/middleware.ts: JWT validation bypass on /admin routes');
    w('- CRITICAL payment/processor.ts: currency rounding drops fractional cents');
    w('- MEDIUM checkout/handler.ts: timeout reduced from 30s to 10s');
    w('- LOW docs/api-guide.md: outdated endpoint URL in examples');
    w('- INFO analysis: dependency tree analysis for inventory module');
    w('');
    w('### Risk in Output Footer');
    w('');
    w('Every output that follows the auto-emit rules includes the risk footer:');
    w('> RISK: LEVEL — one-line description of the primary risk');
    w('');
    w('If multiple risks exist, list the top 3 in priority order. The footer is concise — expand only when the user asks for details.');
    w('');
    w('### Forbidden Risk Patterns');
    w('');
    w('- "may impact" → "breaks X in Y module"');
    w('- "could potentially" → "introduces risk in module"');
    w('- "low risk because it is simple" → simplicity != safety');
    w('- "low risk because it is a test file" → tests affect CI/CD behavior');
    w('- "medium risk, just config" → config changes crash production');
    w('- Lowering risk because user asked you to');
    w('- Lowering risk because "we will test it in staging"');
    w('- Lowering risk because project is small');
    w('- Omitting risk on any non-trivial change');
    w('- Using "we" to diffuse responsibility ("we should be careful here")');
    w('- Using passive voice to hide risk ("the column was dropped")');
    w('');
    w('### Risk Aggregation Over Session');
    w('');
    w('Session aggregate risk tracks the cumulative risk state:');
    w('');
    w('| Trigger | Action |');
    w('|---------|--------|');
    w('| Single CRITICAL entry | Aggregate = CRITICAL, STOP |');
    w('| 2+ HIGH entries | Aggregate = HIGH, pause, checkpoint |');
    w('| 3+ MEDIUM entries | Aggregate = MEDIUM, continue monitoring |');
    w('| Escalating risk (MEDIUM→HIGH→HIGH) | Warning: risk escalating |');
    w('| Stable risk (all same level) | OK, continue |');
    w('| De-escalating (HIGH→MEDIUM→LOW) | Recovery detected |');
    w('');
    w('### Compliance: OWASP LLM Mapping');
    w('');
    w('| OWASP LLM Risk | Synarc Control |');
    w('|----------------|----------------|');
    w('| LLM01: Prompt Injection | Deterministic classification before output; context isolation |');
    w('| LLM02: Insecure Output Handling | Quality gates on all output; S14 language rules |');
    w('| LLM03: Training Data Poisoning | N/A (Synarc does not train models) |');
    w('| LLM04: Model DoS | Token budget limits; S18 compression |');
    w('| LLM05: Supply Chain | S5 agent execution rules; S16 security patterns |');
    w('| LLM06: Sensitive Info Disclosure | S4 safe injection practices; secrets never in context |');
    w('| LLM07: Insecure Plugin Design | S21 plugin isolation; permissions model |');
    w('| LLM08: Excessive Agency | S5 scope enforcement; pre-action checks |');
    w('| LLM09: Overreliance | S13 quality gates; verification requirements |');
    w('| LLM10: Model Theft | No model access; Synarc operates in context layer only |');
    w('');
    w('Load references/security-patterns.md for security-specific risk assessment and compliance requirements. Load references/change-taxonomy.md for full risk dimension analysis.');
    w('');
  }
};
