module.exports = {
  generateS3(w) {
    w('## S3 — SESSION STATE');
    w('');
    w('Synarc maintains session state across the full interaction lifecycle. State is both in-memory (for fast access during active interactions) and persisted (for continuity across sessions, interruptions, and agent handoffs). Session state is the authoritative record of what happened, what is happening, and what remains to be done.');
    w('');
    w('### Session State Schema');
    w('');
    w('session:');
    w('  id: "YYYYMMDD-XXXX"');
    w('  started: ISO8601');
    w('  runtime: detected_platform');
    w('  repo: name_or_unknown');
    w('  scale: NANO|MICRO|SMALL|MEDIUM|LARGE|ENTERPRISE');
    w('  arch: monolith|modular|microservices|serverless|hybrid');
    w('  stack: primary_language/runtime');
    w('  task: declared_task_description');
    w('  work_type: WorkType:PLANNED|UNPLANNED');
    w('  risk: CRITICAL|HIGH|MEDIUM|LOW|INFO');
    w('  scope:');
    w('    files: [file1, file2]');
    w('    modules: [module-a, module-b]');
    w('    risk_cap: LEVEL');
    w('    contract_changes_allowed: false');
    w('  files_touched: []');
    w('  contracts_touched: []');
    w('  modules_touched: []');
    w('  risks_introduced: []');
    w('  risks_resolved: []');
    w('  breaking_changes: []');
    w('  ledger: [{seq, tool, file, worktype, risk, breaking, timestamp, note}]');
    w('  checkpoints: [{id, timestamp, tool_call, risk}]');
    w('  aggregate_risk: LEVEL');
    w('  status: init|active|paused|complete|abandoned');
    w('  last_activity: ISO8601');
    w('');
    w('### Session State Machine');
    w('');
    w('INIT → DETECT → CLASSIFY → DECLARE_SCOPE → ACTIVE');
    w('ACTIVE → (per-tool-call loop): pre_action_check → execute → post_action_track');
    w('ACTIVE → PAUSED: risk threshold, checkpoint needed, user interrupt');
    w('PAUSED → ACTIVE: user resumes, confirms, loads checkpoint');
    w('ACTIVE → COMPLETE: all tasks done, summary emitted, ledger archived');
    w('ACTIVE → ABANDONED: task terminated mid-way, checkpoint written, reason noted');
    w('COMPLETE → archive to brain/CHANGE_LEDGER.md');
    w('');
    w('### State Transitions');
    w('');
    w('| Transition | Trigger | Actions |');
    w('|------------|---------|---------|');
    w('| INIT → ACTIVE | Classification complete | Begin ledger, set scope, load brain files |');
    w('| ACTIVE → COMPLETE | Task declared complete | Emit summary, archive ledger, update brain files |');
    w('| ACTIVE → ABANDONED | User interrupts, error, timeout | Write checkpoint, note reason, save partial state |');
    w('| ACTIVE → PAUSED | Risk threshold, checkpoint trigger | Write checkpoint, surface state to user |');
    w('| PAUSED → ACTIVE | User resumes, confirms | Load checkpoint, verify scope, verify file integrity |');
    w('| ACTIVE → ACTIVE | Tool call completes | Update ledger, update aggregate risk, check thresholds |');
    w('| COMPLETE → (new) | New task starts | Begin new session, reference prior session ID |');
    w('');
    w('### Session ID Format');
    w('');
    w('Format: YYYYMMDD-XXXX (date + 4-character random alphanumeric suffix).');
    w('Example: 20270525-a3f2. Random suffix prevents collision across parallel sessions. Generated at session start, immutable for the session lifetime. Included in all ledger entries and checkpoint files.');
    w('');
    w('### Persistence by Scale');
    w('');
    w('| Scale | In-Memory | Persisted | Storage Target |');
    w('|-------|-----------|-----------|----------------|');
    w('| NANO | Full | Never | Volatile — conversation only |');
    w('| MICRO | Full | Never | Volatile — conversation only |');
    w('| SMALL | Full | On session end | brain/CHANGE_LEDGER.md |');
    w('| MEDIUM | Full | On session end + checkpoint | brain/CHANGE_LEDGER.md + brain/ |');
    w('| LARGE | Full | Every 5 calls + each HIGH+ | brain/snapshots/ + brain/CHANGE_LEDGER.md |');
    w('| ENTERPRISE | Full | Every 3 calls + every change | brain/snapshots/ + brain/CHANGE_LEDGER.md + audit |');
    w('');
    w('### Checkpoint Protocol');
    w('');
    w('Checkpoints are serialized session state snapshots that enable recovery after interruption. Each checkpoint contains: session ID, completed steps, ledger entries to date, current scope, aggregate risk, file integrity verification state, and rollback commands for completed changes.');
    w('');
    w('**Checkpoint triggers:**');
    w('- Every 5 tool calls executed (10 for ENTERPRISE)');
    w('- Aggregate risk reaches HIGH');
    w('- Any CRITICAL risk introduced');
    w('- Scope expands beyond declared boundaries');
    w('- 3+ files written in sequence');
    w('- Contract or schema change detected');
    w('- User requests checkpoint explicitly');
    w('- Session pause or abandon');
    w('- Before destructive operation');
    w('- Before multi-file coordinated change');
    w('');
    w('**Checkpoint format (brain/snapshots/):**');
    w('Filename: YYYY-MM-DDTHH-mm-ss-ckpt-[session-id].md');
    w('Contains: metadata, session state, ledger to date, file integrity, rollback commands, cognitive summary');
    w('');
    w('### Ledger Entry Format');
    w('');
    w('[timestamp | seq] WorkType:subtype | Risk | File path (+lines, -lines) | Breaking: yes/no | Note');
    w('');
    w('Examples:');
    w('[2026-05-26 14:00:00 | 001] FEATURE:PLANNED | MEDIUM | src/auth/router.ts (+12, -3) | Breaking: no | Add rate limiting');
    w('[2026-05-26 14:05:00 | 002] FIX:BUG | HIGH | src/auth/middleware.ts (+5, -0) | Breaking: no | Fix null pointer in JWT verify');
    w('[2026-05-26 14:10:00 | 003] CONTRACT:RESPONSE | CRITICAL | src/api/users.ts (+2, -1) | Breaking: yes | Changed user profile response shape');
    w('');
    w('### Session State Recovery');
    w('');
    w('After interruption or crash:');
    w('1. On session start, check for checkpoint files in brain/ or conversation state');
    w('2. Load most recent checkpoint for this project');
    w('3. Verify all modified files are still present and parseable');
    w('4. Restore session state: scope, ledger, aggregate risk, active tasks');
    w('5. Present recovery summary: "Resuming session [ID] from [timestamp]. [N] files changed, aggregate risk [LEVEL]"');
    w('6. Continue from the next unexecuted step');
    w('');
    w('### Session Commands (Internal)');
    w('');
    w('These commands are processed by Synarc without requiring user invocation. They trigger automatically on conditions.');
    w('');
    w('| Automatic Trigger | Command | Response |');
    w('|------------------|---------|----------|');
    w('| Session starts | session_init | Load or create session state |');
    w('| Tool call completes | session_track | Append to ledger, update state |');
    w('| Risk crosses threshold | session_checkpoint | Write checkpoint, surface warning |');
    w('| Scope expands | session_scope_update | Re-declare scope, note expansion |');
    w('| Contract break | session_contract_break | Flag breaking change, emit impact |');
    w('| Error occurs | session_error | Log error, attempt recovery |');
    w('| Session ends | session_finalize | Archive ledger, emit summary |');
    w('');
    w('### Multi-Session Continuity');
    w('');
    w('When a new session begins after a previous session completed:');
    w('1. Load the previous session ledger from brain/CHANGE_LEDGER.md');
    w('2. Extract cognitive summary of previous session');
    w('3. Note: "Previous session [ID]: [summary]. [N] files changed, [M] risks introduced."');
    w('4. New session starts fresh — previous session never overlaps');
    w('5. Reference previous session by ID when discussing ongoing work');
    w('');
    w('Load references/session-tracking.md for multi-session continuity protocols, crash recovery procedures, and session persistence format details across all supported runtimes.');
    w('');
  }
};
