module.exports = {
  generateS4(w) {
    w('## S4 — CONTEXT INJECTION');
    w('');
    w('Context injection populates the Synarc Context Block into internal reasoning at the start of every interaction. The context block is never displayed unless the user explicitly requests it with "show synarc context." The injection is internal — it shapes output quality without polluting output verbosity.');
    w('');
    w('### Synarc Context Block (Internal)');
    w('');
    w('This block is constructed at every interaction and injected into reasoning. It is not included in the visible output unless requested.');
    w('');
    w('  runtime  : detected or configured');
    w('  repo     : name or unknown');
    w('  scale    : NANO|MICRO|SMALL|MEDIUM|LARGE|ENTERPRISE');
    w('  arch     : monolith|modular|microservices|serverless|hybrid');
    w('  stack    : primary language + runtime');
    w('  work     : WorkType:PLANNED|UNPLANNED');
    w('  risk     : CRITICAL|HIGH|MEDIUM|LOW|INFO');
    w('  session  : session-id or "new"');
    w('  changed  : files or modules touched this session');
    w('  contracts: contracts affected this session');
    w('  risks    : top risks, comma-separated');
    w('  breaks   : breaking changes, comma-separated');
    w('  next     : recommended next action or "none"');
    w('');
    w('### Injection Levels');
    w('');
    w('| Level | Tokens | Content | When Used |');
    w('|-------|--------|---------|-----------|');
    w('| SILENT | ~10 | Classification only (WorkType + Risk) | Read-only ANALYSIS, SILENT tool calls |');
    w('| COMPACT | ~50 | WorkType, Risk, Scale, Task, Files, ΔRisk | Per tool call in agent mode |');
    w('| STANDARD | ~200 | Full context block + recent ledger + scope | Session start, new task, scope change |');
    w('| FULL | ~500 | All STANDARD + brain excerpts + architecture | LARGE/ENTERPRISE, complex changes |');
    w('');
    w('### SILENT Injection Details');
    w('');
    w('SILENT injection means classification still runs and the ledger still appends for mutations, but no context is injected into reasoning. The AI knows the WorkType and Risk but sees no context block. Used for: grep, ls, read_file, git log, cat, ANALYSIS worktype. Even in SILENT mode, the pipeline executes — DETECT, CLASSIFY, SCAN, TRACK still run. Only INJECT is suppressed.');
    w('');
    w('### COMPACT Injection Format');
    w('');
    w('WT:[FEATURE] R:[HIGH] #[3] S:[MEDIUM]');
    w('Task: Add rate limiting to payment API');
    w('Files: src/payment/middleware.ts, src/payment/types.ts');
    w('DeltaRisk: [+1 from last call — contract break detected]');
    w('');
    w('COMPACT is the default injection for agent mode tool calls. It fits in approximately 50 tokens and provides just enough context for the AI to make correct decisions without consuming the context window.');
    w('');
    w('### STANDARD Injection Format');
    w('');
    w('WorkType: FIX:UNPLANNED');
    w('Risk: HIGH');
    w('Scale: MEDIUM');
    w('Task: Fix timeout error in checkout service');
    w('Scope: src/checkout/*, src/payment/client.ts');
    w('Session: 20270525-a3f2');
    w('Recent ledger:');
    w('  [1] src/checkout/handler.ts — FIX — MEDIUM');
    w('  [2] src/payment/client.ts — FIX — HIGH (contract break)');
    w('  [3] src/checkout/types.ts — REFACTOR — LOW');
    w('Contracts affected: checkout/processCheckout (response shape)');
    w('Risk sum: HIGH (1 HIGH active)');
    w('Brain files loaded: CURRENT_STATE.md, MODULE_MAP.md, API_CONTRACTS.md');
    w('');
    w('STANDARD is used at session start, new task declarations, and scope boundary changes. It provides the AI with session context, recent history, and active risks.');
    w('');
    w('### FULL Injection Additions');
    w('');
    w('Architecture context:');
    w('  - Service boundary: checkout → payment (HTTP)');
    w('  - Payment client has no retry, no circuit breaker');
    w('  - Checkout handler has no timeout on payment call');
    w('Invariants:');
    w('  - Checkout.total must equal sum of line items');
    w('  - Payment must be idempotent (orderId as idempotency key)');
    w('Relevant CURRENT_STATE.md:');
    w('  - Payment module flagged fragile (2 incidents last month)');
    w('  - Checkout module has 85% test coverage');
    w('');
    w('FULL injection is reserved for LARGE and ENTERPRISE scale projects, complex cross-boundary changes, and architecture-impacting decisions. It loads the full context including architecture summaries and brain file excerpts.');
    w('');
    w('### Context Injection Priority');
    w('');
    w('When the context window is constrained, inject in this priority order. Drop from the bottom when budget is exhausted:');
    w('');
    w('1. WorkType + Risk (2 lines) — always injected, even in SILENT');
    w('2. Task + Scope (2 lines)');
    w('3. Scale (1 line)');
    w('4. Recent ledger entries (last 3, newest first)');
    w('5. Aggregate risk + contract break count');
    w('6. Most relevant brain file snippet (3 lines max)');
    w('7. File list and module boundaries');
    w('8. Architecture context (FULL only)');
    w('');
    w('### Budget-Based Injection');
    w('');
    w('| Context Budget | Injection Level | Notes |');
    w('|---------------|----------------|-------|');
    w('| > 60% remaining | STANDARD or FULL | Load full context |');
    w('| 40-60% remaining | COMPACT | Load essentials only |');
    w('| 20-40% remaining | COMPACT compressed | Drop ledger, keep WorkType + Risk + Task |');
    w('| < 20% remaining | SILENT | Classification only |');
    w('| Near capacity | SILENT + 1-line summary | Minimal injection |');
    w('');
    w('### Auto-Emit Rules');
    w('');
    w('Auto-emit rules trigger additional output appended to the primary response. Auto-emit is always additive — it never replaces the primary answer. Each rule has a maximum output length of 20 lines.');
    w('');
    w('| Trigger | Auto-Emit Content |');
    w('|---------|-------------------|');
    w('| SCHEMA change detected | Schema change warning + impact summary |');
    w('| CONTRACT change detected | Breaking change analysis + migration path |');
    w('| FIX on HIGH/CRITICAL risk | Error Intelligence report from S12 |');
    w('| INCIDENT worktype | Full incident snapshot |');
    w('| 3+ files changed in session | Session summary + ledger excerpt |');
    w('| PLANNED feature completed | Feature log entry |');
    w('| Architecture change (LARGE+) | Architecture delta note |');
    w('| "what happened" query | Full session cognitive summary |');
    w('| Risk crosses MEDIUM→HIGH | Risk escalation notice |');
    w('| Contract break introduced | Breaking change impact block |');
    w('| First file write in session | Session start confirmation |');
    w('| UNPLANNED scope expansion | UNPLANNED flag notice |');
    w('| Aggregate risk = CRITICAL | STOP + full incident mode |');
    w('| Checkpoint written | Checkpoint confirmation + state summary |');
    w('| Session complete | Session summary + ledger count |');
    w('');
    w('### Safe Injection — What NEVER Enters Context');
    w('');
    w('- Database connection strings or credentials');
    w('- API keys, tokens, or secrets of any kind');
    w('- PII (names, emails, SSNs, addresses, phone numbers)');
    w('- Internal IP addresses or hostnames (use service names)');
    w('- Full file contents (inject summaries and excerpts, not raw code)');
    w('- Session tokens or authentication headers');
    w('- Private keys, certificates, or key material');
    w('- Network topology or internal infrastructure layout');
    w('- Encryption keys or seed values');
    w('- Internal URLs with embedded credentials');
    w('- Configuration values that are secrets (use placeholder references)');
    w('- Customer data or user records');
    w('');
    w('### Safe Injection Practices');
    w('');
    w('- Inject module names, not file paths with credentials');
    w('- Inject contract names, not authentication tokens');
    w('- Inject risk levels, not access control rules');
    w('- Inject architecture summaries, not network topology');
    w('- For secrets: use placeholder references ("DB_PASSWORD from secrets manager")');
    w('- For URLs: inject endpoint names, not full URLs with embedded secrets');
    w('- For IDs: use internal IDs, not public-facing identifiers');
    w('- For errors: sanitize error messages before injecting (remove stack traces that contain credentials)');
    w('');
    w('### Cross-Runtime Injection Variations');
    w('');
    w('| Runtime | Injection Mechanism | Format | Max Size |');
    w('|---------|--------------------|--------|----------|');
    w('| Claude Code | Internal reasoning input | Text block | ~2000 lines |');
    w('| Claude Web | Session state block | Text block | ~100 lines |');
    w('| Codex CLI | AGENTS.md context | ASCII prefix | ~500 lines |');
    w('| Cursor | IDE rules injection | Footer | ~50 lines |');
    w('| Windsurf | IDE rules injection | Footer | ~50 lines |');
    w('| Claude API | Structured context field | JSON | ~10KB |');
    w('| Copilot | AGENTS.md context | ASCII prefix | ~500 lines |');
    w('');
    w('Load references/injection-protocol.md for full injection level specifications, context window management strategies, and compression patterns for all supported runtimes.');
    w('');
  }
};
