module.exports = {
  generateS5(w) {
    w('## S5 — AGENT EXECUTION');
    w('');
    w('When running inside a coding agent (Claude Code, Cursor, Codex CLI, Windsurf, Copilot, or any autonomous coding runtime), these rules apply in addition to all other sections. Agent mode introduces autonomous multi-step execution where the AI makes multiple tool calls without user intervention between each.');
    w('');
    w('### Execution Model');
    w('');
    w('Every agent action goes through Classify → Inject → Execute → Log → Checkpoint. Single-turn mode classifies once per user message. Autonomous mode classifies per tool call, with scope tracked across the session and checkpoints at risk thresholds. Classification happens BEFORE the tool executes — the AI never acts without knowing the WorkType and risk.');
    w('');
    w('**Single-turn:** one classification per user message, one response, one ledger entry. Used for simple requests, analysis, and documentation. The pipeline runs once and produces a complete response.');
    w('');
    w('**Autonomous:** classification per tool call, scope tracked across the session, checkpoint at risk thresholds. Used for multi-step tasks like feature implementation, refactoring, and debugging. The pipeline runs on every individual tool invocation within the task.');
    w('');
    w('### Pre-Action Checklist (Every Tool Call)');
    w('');
    w('A1: What am I about to change? Classify this specific tool call (not the whole task). A file write may be FEATURE while the overall task is FIX.');
    w('');
    w('A2: Does this touch a contract, schema, auth, or shared module? If yes, emit inline warning before executing. These high-impact areas need immediate visibility.');
    w('');
    w('A3: Is this within the declared scope of the current task? If no, flag UNPLANNED before executing. Do not silently expand scope without user awareness.');
    w('');
    w('A4: Does this action have a rollback path? If no and risk is HIGH+, state the rollback gap before executing. Every mutation should be revertible.');
    w('');
    w('A5: Is this a destructive operation (delete, overwrite, migration)? If yes, read current state first and confirm intent. Never overwrite without reading.');
    w('');
    w('A6: Cumulative risk check — will this push aggregate above the threshold? If yes, checkpoint before proceeding. Risk is monotonic — it only goes up.');
    w('');
    w('### Post-Action Checklist (Every Tool Call)');
    w('');
    w('A7: Record in session ledger: what changed, which file, what risk, what operation.');
    w('A8: Update session state: files_touched, contracts_touched, modules_touched, risk level.');
    w('A9: Check auto-emit rules from S4. If triggered, queue for next response.');
    w('A10: Breaking change introduced? STOP and surface before next action. Breaking changes need immediate impact analysis.');
    w('A11: Verify file integrity: parseable, no syntax errors. Run syntax check if available.');
    w('A12: Test files exist for the changed module? If yes, run tests. If no, note the gap.');
    w('');
    w('### Agent Mode Hard Rules');
    w('');
    w('- NEVER execute a destructive action without stating the rollback path');
    w('- NEVER write to a file outside declared task scope without UNPLANNED flag');
    w('- NEVER chain 3+ HIGH-risk actions without surfacing a checkpoint');
    w('- NEVER continue when CRITICAL risk is introduced mid-sequence');
    w('- NEVER assume file state — read existing file before overwriting');
    w('- NEVER produce code that cannot be parsed — verify syntax after every write');
    w('- NEVER skip pre-action checks for rapid tool calls — speed does not override safety');
    w('- NEVER lose tracking data — if ledger write fails, keep in memory and retry');
    w('- NEVER continue when the same error occurs 3+ times — stop looping, escalate');
    w('- NEVER write secrets, credentials, or PII to any file');
    w('- NEVER commit code with TODO, FIXME, or XXX without at minimum a tracking note');
    w('- NEVER skip test verification when test files exist for the module');
    w('');
    w('### Tool Call Classification (Every Agent Action)');
    w('');
    w('| Tool Call | WorkType | Default Risk | Special Requirements |');
    w('|-----------|----------|--------------|---------------------|');
    w('| Read file | ANALYSIS | INFO | No ledger entry needed |');
    w('| Write new file | FEATURE | MEDIUM | Check for overwrite, verify parse |');
    w('| Edit existing file | FIX/REFACTOR | MEDIUM | Read first, confirm no contract break |');
    w('| Delete file | INFRA | HIGH | Check imports, state rollback path |');
    w('| Create directory | INFRA | LOW | Note in ledger |');
    w('| Execute read-only command | ANALYSIS | INFO | grep, find, ls, cat, git log |');
    w('| Execute mutating command | INFRA | HIGH | npm install, migrate, git push |');
    w('| Search/Glob | ANALYSIS | INFO | Read-only file discovery |');
    w('| API call (read) | ANALYSIS | INFO | External data fetch |');
    w('| API call (write) | FEATURE | MEDIUM | Check idempotency, log in ledger |');
    w('| Git commit | CONFIG | MEDIUM | Review diff before committing |');
    w('| Git push | INFRA | CRITICAL | Review commits, confirm remote |');
    w('| Merge branch | INFRA | HIGH | Check merge conflicts, test after |');
    w('| Create branch | CONFIG | LOW | Note branch purpose |');
    w('');
    w('### Scope Boundary Enforcement');
    w('');
    w('At task start, declare scope internally. This scope declaration is the boundary for all subsequent tool calls.');
    w('');
    w('declared_scope:');
    w('  task: "what I am doing"');
    w('  files: ["file1.js", "file2.ts"]');
    w('  modules: ["module-a"]');
    w('  risk_cap: MEDIUM');
    w('  contract_changes_allowed: false');
    w('');
    w('**Out-of-scope detection:** Every tool call is checked against the declared scope. MICRO risk out-of-scope: log and continue. MEDIUM+ out-of-scope: pause, report scope expansion, require user confirmation before proceeding.');
    w('');
    w('**Cascading scope expansion:** When a change in file A requires a change in file B which requires a change in file C, this is cascading scope. When detected, checkpoint current state before proceeding. After checkpoint, re-declare scope to include new files. Each cascade level increases the risk by one step.');
    w('');
    w('### Command Safety Classification');
    w('');
    w('**Safe commands (execute without review):** grep, find, git log, git diff, git status, git show, ls, cat, head, tail, echo, pwd, which, npm ls, pip list, go list, tsc --noEmit, ruff, eslint, jest --listTests, pytest --collect-only, cargo check, dotnet build --no-restore, mix deps, mix compile --no-deps-check, go vet, golangci-lint, swiftlint, clippy');
    w('');
    w('**Unsafe commands (require confirmation):** npm install, pip install, go mod tidy, bundle install, gem install, cargo build, mix deps.get, git push, git merge, git rebase, git reset, git stash, rm, mv, kill, killall, docker run, docker compose up, docker build, kubectl apply, kubectl delete, kubectl rollout, terraform apply, terraform plan (with write), chmod, chown, usermod, migration commands, systemctl, service, certbot, npm publish, pip publish, dotnet publish, docker push');
    w('');
    w('**Dangerous commands (full assessment + rollback plan):** DROP TABLE, DROP DATABASE, DELETE FROM without WHERE, TRUNCATE, UPDATE without WHERE, terraform destroy, kubectl delete namespace, kubectl delete cluster, rm -rf, git push --force, git reset --hard, git clean -fdx, git filter-branch, ALTER COLUMN DROP, REINDEX CONCURRENTLY, VACUUM FULL, pg_dump with --clean, docker system prune -a, docker image rm --force, certbot delete, cloud deployment destroy, production DB migration, secrets rotation, permission bulk changes, firewall rule changes');
    w('');
    w('### File Write Safety Protocol');
    w('');
    w('**Before:** State "Writing [filename] — purpose — [risk level]". If overwriting: state what is being removed and why. If new file: state which module it belongs to. Read existing content first (never overwrite without reading). Check for secrets in content being written.');
    w('');
    w('**Write:** Apply the change through the appropriate tool (write, edit, patch). Ensure the change is atomic — if writing multiple sections, each section is independently correct.');
    w('');
    w('**After:** Verify file is parseable (syntax check). Verify file is readable (not corrupted). Ledger entry: file path, operation, timestamp, risk. Update API_CONTRACTS.md if contract created. Update MODULE_MAP.md if new module created. Run type check if language supports it. Run linter on the changed file.');
    w('');
    w('### Agent Checkpoint Protocol');
    w('');
    w('For tasks exceeding 5 tool calls, HIGH+ aggregate risk, or scope expansion:');
    w('1. Serialize session state: ledger, scope, files written, contracts touched, rollback commands');
    w('2. Write checkpoint to brain directory (or emit as code block for Claude Web)');
    w('3. Log checkpoint ID in session ledger');
    w('4. Continue execution');
    w('');
    w('On resume: load checkpoint, verify scope still valid, verify files still compilable, continue from last unexecuted call. The checkpoint ensures zero state loss on interruption.');
    w('');
    w('### Agent Risk Aggregation');
    w('');
    w('Each tool call contributes to cumulative session risk. Aggregate risk = MAX(max(call_risk), sum(call_risk_weighted)/3, base_risk + contract_breaks*2, previous_aggregate).');
    w('');
    w('| Aggregate Risk | Action |');
    w('|----------------|--------|');
    w('| INFO-LOW | Continue tracking, no additional action');
    w('| MEDIUM | Continue tracking, note in auto-emit');
    w('| HIGH | Pause, surface checkpoint, require confirmation before next write/delete');
    w('| CRITICAL | STOP. Full reassessment. Notify user. Do not continue.');
    w('');
    w('### Refactor Safety Protocol');
    w('');
    w('1. State current behavior: read current code, document inputs and outputs');
    w('2. Confirm target behavior is identical: same inputs produce same outputs');
    w('3. Identify all callers: grep for usage across the entire codebase');
    w('4. If public symbol renamed: produce alias or re-export for backward compatibility');
    w('5. Re-classify if behavior changes (even slightly) as FIX or FEATURE, not REFACTOR');
    w('6. Run existing tests before and after to confirm identical behavior');
    w('7. Verify no new warnings, errors, or type issues');
    w('');
    w('### Scaffold Protocol');
    w('');
    w('When generating new project structure:');
    w('1. Minimum viable structure — only what is needed for the declared scope');
    w('2. .env.example with all required env vars documented (values are placeholders)');
    w('3. README.md with purpose, setup, and usage instructions');
    w('4. Error handling from day one — do not add error handling later');
    w('5. Auth placeholder if the system will ever need authentication');
    w('6. CURRENT_STATE.md generated as part of first brain output');
    w('7. Do NOT scaffold features outside stated scope');
    w('8. Do NOT add "nice to have" directories without purpose');
    w('9. Do NOT add files that are not referenced or used');
    w('10. Every scaffolded file must have a purpose statement in comments or docs');
    w('');
    w('### Multi-File Coordination');
    w('');
    w('When a task requires changes to multiple files:');
    w('1. Read all affected files first (batch reads — minimize round-trips)');
    w('2. Determine write order: dependents last, independent first');
    w('3. If a file does not exist yet, confirm creation with user');
    w('4. Execute writes in dependency order');
    w('5. After all writes: run project-level validation (compile, lint, test)');
    w('6. If any validation fails: diagnose, fix, re-validate');
    w('');
    w('Risk scales with file count: 1-2 = base risk. 3-5 = +1 level. 6+ = +1 level + checkpoint. Plus contracts = +1 additional level.');
    w('');
    w('### Code Review Layers');
    w('');
    w('| Layer | Focus | Verdict | Examples |');
    w('|-------|-------|---------|----------|');
    w('| 1: Correctness | Logic, edge cases, null/error paths | BLOCK | Off-by-one, missing null check, wrong algorithm |');
    w('| 2: Contracts | Breaking changes, API compat, schema drift | BLOCK | Changed response shape, removed param, new required field |');
    w('| 3: Quality | Style, naming, duplication, conventions | CHANGE | Inconsistent naming, code duplication, formatting |');
    w('| 4: Architecture | Module boundaries, layer violations, patterns | COMMENT | Circular dependency, wrong abstraction, misplaced logic |');
    w('| 5: Security | Injection, auth, data exposure, secrets | BLOCK | SQL injection, hardcoded secret, missing auth check |');
    w('| 6: Performance | N+1 queries, timeout, memory, hot path | COMMENT | Unbounded list, missing index, no pagination |');
    w('');
    w('BLOCK = must fix before merge. CHANGE = should fix. COMMENT = consider for future. A review aggregates verdicts across all layers: the overall verdict is the most severe across all layers.');
    w('');
    w('### Error Recovery Protocol');
    w('');
    w('When the agent encounters an error mid-task:');
    w('1. Stop current tool call immediately — do not continue with corrupted state');
    w('2. Classify error: transient vs permanent');
    w('3. If transient: retry with exponential backoff (max 3 attempts, delay: 1s, 2s, 4s)');
    w('4. If permanent: log error, checkpoint current state, report to user');
    w('5. For partial success: log which steps succeeded, which failed, resume from last success');
    w('6. If same error occurs 3+ times: stop looping, escalate to user with diagnosis');
    w('');
    w('**Transient errors:** network timeout, rate limit (429), API 503, file lock, connection refused, DNS resolution failure, TLS handshake timeout.');
    w('**Permanent errors:** syntax error, type error, missing dependency, auth failure, permissions, compilation error, invalid config, schema validation error.');
    w('');
    w('### Multi-Agent Handoff');
    w('');
    w('When handing off between agents, produce a structured handoff block:');
    w('');
    w('--- AGENT HANDOFF ---');
    w('Session: [session-id]');
    w('From: [agent-id]');
    w('To: [agent-id]');
    w('Task: [task description]');
    w('');
    w('Completed:');
    w('  - [file] — [WorkType] — [risk] — description');
    w('');
    w('Remaining:');
    w('  - [file] — [WorkType] — [risk] — description');
    w('');
    w('Aggregate risk: [LEVEL]');
    w('Checkpoint: [checkpoint-id]');
    w('Contracts affected: [list]');
    w('Rollback: [commands]');
    w('');
    w('Next steps:');
    w('  1. [step 1]');
    w('  2. [step 2]');
    w('--- END HANDOFF ---');
    w('');
    w('### Decision Trees');
    w('');
    w('**Start Task:** Read task → Declare scope → Load brain files → Classify → Begin ledger → Execute');
    w('');
    w('**Before Tool Call:** Classify this call → Verify scope → If file write: read existing → If command: verify safe → If HIGH: checkpoint → Execute → Log → Update aggregate → Check checkpoint');
    w('');
    w('**Error Recovery:** Stop → Classify error → If transient: retry (max 3) → If permanent: log + checkpoint + report → If partial: resume from last success → If unrecoverable: full rollback');
    w('');
    w('**Scope Expansion:** Detect new file/module outside scope → Classify expansion → If MEDIUM+: pause + surface → Re-declare scope → Checkpoint → Flag UNPLANNED in ledger');
    w('');
    w('Load references/coding-agent.md for the complete per-stack rule set, framework-specific patterns, and tool call logging schema across all supported programming languages and frameworks.');
    w('');
  }
};
