module.exports = {
  generateS6(w) {
    w('## S6 — BRAIN DOCUMENTS');
    w('');
    w('The brain directory stores persistent engineering intelligence about the codebase. It is the canonical source of truth for architecture, contracts, risks, and change history. Brain files are version-controlled, append-only where applicable, and readable by any agent in any session.');
    w('');
    w('### Brain Directory Structure');
    w('');
    w('/brain/');
    w('  CURRENT_STATE.md — Living architecture snapshot, updated on significant changes');
    w('  SYSTEM_MAP.md — Structural boundary map, dependencies, data flow');
    w('  ARCHITECTURE.md — Principles, layers, failure modes, mitigations');
    w('  MODULE_MAP.md — Module index, ownership, risks, test coverage');
    w('  API_CONTRACTS.md — All contracts, schemas, invariants, endpoints');
    w('  FEATURE_LOG.md — Feature timeline, planned and unplanned');
    w('  CHANGE_LEDGER.md — Session-by-session change history, append-only');
    w('  ERROR_INTELLIGENCE.md — Error classification, root cause, fix, recurrence');
    w('  INCIDENT_LOG.md — Production incidents, severity, timeline, lessons');
    w('  SERVICE_REGISTRY.md — All services (ENTERPRISE scale only)');
    w('  ANALYSIS_LOG.md — Error analyses and recurrence patterns');
    w('  snapshots/ — Immutable checkpoints with full state at point in time');
    w('');
    w('### CURRENT_STATE.md');
    w('');
    w('The primary cognitive memory document. Contains: Active Architecture (one-line description of current system style), Major Modules table (module name, purpose, tech, owner, test coverage), Important Contracts (list of key contracts with stability status), Current Risks (table by level: CRITICAL through INFO, each with owner and mitigation), Extension Paths (safe vs avoid patterns for extending the system), Invariants (truths that must not be broken), and a Cognitive Summary paragraph at the end.');
    w('');
    w('Updated on: new module, contract change, risk level change, architecture change, new invariant discovered. Never contains placeholder content — every field is populated from actual codebase analysis.');
    w('');
    w('### SYSTEM_MAP.md');
    w('');
    w('Static structural map of the system. Contains: Overview paragraph, Boundaries table (internal vs external systems), Modules table (type: service/library/function, responsibility, runtime, language), Dependencies table (internal dependency, type, direction), Data Flow description (key request paths and data movement), External Integrations table (service, protocol, data sensitivity), and Cognitive Summary.');
    w('');
    w('Generated on initial scan. Updated when boundaries change, new dependencies added, or integrations modified. The map is structural — it describes what connects to what, not how they behave.');
    w('');
    w('### ARCHITECTURE.md');
    w('');
    w('Architectural principles and design decisions. Contains: Principles (up to 10 architectural principles the project follows), Layers table (layer name, responsibility, technology), Services table (service name, type, responsibility, data owned), Contracts table (contract name, type, stability, consumers), Data Flow (end-to-end request path through layers), Failure Modes table (mode, impact, mitigation, detection), and Cognitive Summary.');
    w('');
    w('Each principle includes a rationale and an example of application. Failure modes are documented with real scenarios, not hypotheticals. Updated on significant architectural decisions or when failure modes are discovered in production.');
    w('');
    w('### MODULE_MAP.md');
    w('');
    w('Module index for the entire codebase. Contains: Module List table (name, path, type, owner, status: stable/unstable/deprecated/experimental), Responsibilities per module (bullet list of what the module owns), Entry Points table (entry, type, consumers), Dependencies table (module, depends on, type), Ownership table (module, team, slack channel, on-call rotation), Risks table per module (risk, level, status, mitigation), and Test Coverage notes.');
    w('');
    w('Modules are classified by type: service, library, utility, configuration, infrastructure, or deprecated. Coverage notes include percentage, critical paths tested, and known gaps. Updated on every significant change to module structure or ownership.');
    w('');
    w('### API_CONTRACTS.md');
    w('');
    w('All boundary contracts in the system. Contains: Auth method (how authentication works for all endpoints), Endpoints table (method, path, purpose, auth, rate limit, idempotency key, request schema, response schema, status codes, error codes), Events/Queues table (event name, producer, consumer, schema, delivery guarantee), Invariants across contracts (truths that span multiple endpoints), and Cognitive Summary.');
    w('');
    w('Contracts are the source of truth for integration. Every public endpoint, event, and queue is documented. Private/internal APIs are documented if consumed by multiple services. Updated on every contract change — the contract is updated BEFORE the implementation.');
    w('');
    w('### FEATURE_LOG.md');
    w('');
    w('Feature timeline. Per feature: Name, Date implemented, Purpose (one sentence), Systems Affected (list of modules), Change Summary (what changed), Risks Introduced and Resolved, and Snapshot Link. Both planned and unplanned features are logged. Updated when a feature reaches completion (not when work starts).');
    w('');
    w('### CHANGE_LEDGER.md');
    w('');
    w('Curated change history, organized by session. Per session: Session ID, Date, Cognitive Summary, Scope, Ledger table (seq, file, worktype, risk, breaking, note), Aggregate Risk at session end, Checkpoints created, Rollback info, and Cross-session references. Append-only — entries are never modified after creation. This is the immutable audit trail.');
    w('');
    w('### ERROR_INTELLIGENCE.md');
    w('');
    w('All errors analyzed with root cause, impact, fix, and recurrence detection. Per error: Error ID (ERR-NNN), Class (bug/crash/security/performance/data/config/dependency), Location (file:line or module), Root Cause (technical root cause, 1-3 sentences), Impact (what the error affected), Fix (what was changed to resolve), Test (was a test added? what type?), Recurrence Flag (first occurrence or recurrence of a known pattern), and Follow-up Items. Updated after every FIX or INCIDENT.');
    w('');
    w('### INCIDENT_LOG.md');
    w('');
    w('Production incidents log. Per incident: Timestamp, Severity (CRITICAL/HIGH/MEDIUM/LOW), Systems Affected, Root Cause, Timeline (detection → triage → mitigation → resolution), Impact (users affected, revenue impact, data loss), Mitigation (what was done to resolve), Lessons Learned (what went well, what went wrong), Action Items (preventive measures with owners and deadlines). LARGE and ENTERPRISE scale only.');
    w('');
    w('### Brain File Generation Rules');
    w('');
    w('- Generate on first full scan of a new project — do not skip even for small projects');
    w('- Update on significant changes: FEATURE, SCHEMA, CONTRACT, ARCHITECTURE');
    w('- Never update with placeholder content — every field must contain analyzed information');
    w('- Never invent module names, contracts, or relationships that do not exist in code');
    w('- Every .md file must have YAML frontmatter between --- delimiters');
    w('- Every file must have an H1 title and H2 sections with consistent structure');
    w('- Tables use consistent column alignment (left-aligned text, right-aligned numbers)');
    w('- Cognitive Summary at the end of every file: one paragraph, present tense, 4-6 sentences');
    w('- Snapshots are immutable — once written, never edited');
    w('');
    w('### Brain File Maintenance Triggers');
    w('');
    w('| Trigger | File to Update |');
    w('|---------|----------------|');
    w('| New module or file created | MODULE_MAP.md |');
    w('| New API endpoint or route added | API_CONTRACTS.md |');
    w('| New feature completed | FEATURE_LOG.md |');
    w('| Session ends (SMALL+) | CHANGE_LEDGER.md |');
    w('| ERROR analysis complete | ERROR_INTELLIGENCE.md |');
    w('| INCIDENT occurs | INCIDENT_LOG.md |');
    w('| Architecture changes | ARCHITECTURE.md + CURRENT_STATE.md |');
    w('| Module risk changes | MODULE_MAP.md risks table |');
    w('| Snapshot requested | snapshots/YYYY-MM-DDTHH-mm-ss-name.md |');
    w('| Dependency changes | SYSTEM_MAP.md |');
    w('| Contract changes | API_CONTRACTS.md |');
    w('');
    w('### Snapshot Protocol');
    w('');
    w('Snapshots are immutable architecture records. Once written, they are never edited. Naming: YYYY-MM-DDTHH-mm-ss-descriptive-name.md. Required sections: Metadata (timestamp, commit SHA, branch, author, PR link), Purpose (why this snapshot exists), Systems Affected (modules, contracts, config, schema), Architecture Changes (structural changes, new boundaries), Data Flow (before/after request path), Dependencies Added (type, name, used by, purpose), Extension Points (where future features can be added safely), Risks Introduced (level, risk, affected module), Breaking Changes (what breaks, who is affected, migration path), and Cognitive Summary.');
    w('');
    w('Load references/schemas.md for the canonical schema of every brain file, including field types, required vs optional fields, and example content for each document type.');
    w('');
  }
};
